### ISSUE TITLE
SSL Certification Issue while running azd up

### ISSUE THREAD

**Issue by varunr02** [Azure-Samples/azure-search-openai-demo#1031]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

These are the locations I selected. US East 2 was not working. 
Select an Azure location to use: as 34. (Europe) West Europe (westeurope)
Enter a value for the 'openAiResourceGroupLocation' infrastructure parameter: as 3. (Europe) France Central (francecentral)

### Any log messages given by the failure
>

I got 3 traceback error while running azd up. 

The issue is with predocs.py

traceback 1:

Running "prepdocs.py"
Processing files...
Using local files in ./data/*
/Users/varun/Documents/rentalApp/./scripts/prepdocs.py:257: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
Ensuring search index gptkbindex exists
Traceback (most recent call last):
  File "/Users/varun/Documents/rentalApp/scripts/.venv/lib/python3.10/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 1089, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 1119, in _create_connection_transport
    await waiter
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/sslproto.py", line 534, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/sslproto.py", line 188, in feed_ssldata
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 974, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

traceback 2:

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/varun/Documents/rentalApp/scripts/.venv/lib/python3.10/site-packages/azure/core/pipeline/transport/_aiohttp.py", line 280, in send
    result = await self.session.request(  # type: ignore
  File "/Users/varun/Documents/rentalApp/scripts/.venv/lib/python3.10/site-packages/aiohttp/client.py", line 574, in _request
    conn = await self._connector.connect(
  File "/Users/varun/Documents/rentalApp/scripts/.venv/lib/python3.10/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/Users/varun/Documents/rentalApp/scripts/.venv/lib/python3.10/site-packages/aiohttp/connector.py", line 911, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/Users/varun/Documents/rentalApp/scripts/.venv/lib/python3.10/site-packages/aiohttp/connector.py", line 1235, in _create_direct_connection
    raise last_exc
  File "/Users/varun/Documents/rentalApp/scripts/.venv/lib/python3.10/site-packages/aiohttp/connector.py", line 1204, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/Users/varun/Documents/rentalApp/scripts/.venv/lib/python3.10/site-packages/aiohttp/connector.py", line 994, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host gptkb-r7fgohvt2im5e.search.windows.net:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')]

traceback 3:

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/varun/Documents/rentalApp/./scripts/prepdocs.py", line 258, in <module>
    loop.run_until_complete(main(file_strategy, azd_credential, args))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/varun/Documents/rentalApp/./scripts/prepdocs.py", line 131, in main
    await strategy.setup(search_info)
  File "/Users/varun/Documents/rentalApp/scripts/prepdocslib/filestrategy.py", line 48, in setup
    await search_manager.create_index()
  File "/Users/varun/Documents/rentalApp/scripts/prepdocslib/searchmanager.py", line 122, in create_index
    if self.search_info.index_name not in [name async for name in search_index_client.list_index_names()]:
  File "/Users/varun/Documents/rentalApp/scripts/prepdocslib/searchmanager.py", line 122, in <listcomp>
    if self.search_info.index_name not in [name async for name in search_index_client.list_index_names()]:
  File "/Users/varun/Documents/rentalApp/scripts/.venv/lib/python3.10/site-packages/azure/core/async_paging.py", line 142, in __anext__
    return await self.__anext__()
  File "/Users/varun/Documents/rentalApp/scripts/.venv/lib/python3.10/site-packages/azure/core/async_paging.py", line 145, in __anext__
    self._page = await self._page_iterator.__anext__()
  File "/Users/varun/Documents/rentalApp/scripts/.venv/lib/python3.10/site-packages/azure/core/async_paging.py", line 94, in __anext__
    self._response = await self._get_next(self.continuation_token)
  File "/Users/varun/Documents/rentalApp/scripts/.venv/lib/python3.10/site-packages/azure/search/documents/indexes/_generated/aio/operations/_indexes_operations.py", line 291, in get_next
    pipeline_response: PipelineResponse = await self._client._pipeline.run(  # pylint: disable=protected-access
  File "/Users/varun/Documents/rentalApp/scripts/.venv/lib/python3.10/site-packages/azure/core/pipeline/_base_async.py", line 221, in run
    return await first_node.send(pipeline_request)
  File "/Users/varun/Documents/rentalApp/scripts/.venv/lib/python3.10/site-packages/azure/core/pipeline/_base_async.py", line 69, in send
    response = await self.next.send(request)
  File "/Users/varun/Documents/rentalApp/scripts/.venv/lib/python3.10/site-packages/azure/core/pipeline/_base_async.py", line 69, in send
    response = await self.next.send(request)
  File "/Users/varun/Documents/rentalApp/scripts/.venv/lib/python3.10/site-packages/azure/core/pipeline/_base_async.py", line 69, in send
    response = await self.next.send(request)
  [Previous line repeated 2 more times]
  File "/Users/varun/Documents/rentalApp/scripts/.venv/lib/python3.10/site-packages/azure/core/pipeline/policies/_redirect_async.py", line 73, in send
    response = await self.next.send(request)
  File "/Users/varun/Documents/rentalApp/scripts/.venv/lib/python3.10/site-packages/azure/core/pipeline/policies/_retry_async.py", line 205, in send
    raise err
  File "/Users/varun/Documents/rentalApp/scripts/.venv/lib/python3.10/site-packages/azure/core/pipeline/policies/_retry_async.py", line 179, in send
    response = await self.next.send(request)
  File "/Users/varun/Documents/rentalApp/scripts/.venv/lib/python3.10/site-packages/azure/core/pipeline/policies/_authentication_async.py", line 94, in send
    response = await self.next.send(request)
  File "/Users/varun/Documents/rentalApp/scripts/.venv/lib/python3.10/site-packages/azure/core/pipeline/_base_async.py", line 69, in send
    response = await self.next.send(request)
  File "/Users/varun/Documents/rentalApp/scripts/.venv/lib/python3.10/site-packages/azure/core/pipeline/_base_async.py", line 69, in send
    response = await self.next.send(request)
  File "/Users/varun/Documents/rentalApp/scripts/.venv/lib/python3.10/site-packages/azure/core/pipeline/_base_async.py", line 69, in send
    response = await self.next.send(request)
  [Previous line repeated 2 more times]
  File "/Users/varun/Documents/rentalApp/scripts/.venv/lib/python3.10/site-packages/azure/core/pipeline/_base_async.py", line 106, in send
    await self._sender.send(request.http_request, **request.context.options),
  File "/Users/varun/Documents/rentalApp/scripts/.venv/lib/python3.10/site-packages/azure/core/pipeline/transport/_aiohttp.py", line 317, in send
    raise ServiceRequestError(err, error=err) from err
azure.core.exceptions.ServiceRequestError: Cannot connect to host gptkb-r7fgohvt2im5e.search.windows.net:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')]

**ERROR: failed running post hooks: 'postprovision' hook failed with exit code: '1', Path: './scripts/prepdocs.sh'. : exit code: 1**

### Expected/desired behavior
>

Need azd up to work properly without any error

### OS and Version?
> macOS Sanoma

### azd version?
> run `azd version` and copy paste here.
 1.5.0

### Versions
>

### Mention any other details that might be useful

I tried multiple solutions. But nothing worked. 

Troubleshooting Steps Taken

Upgraded Python to latest version 3.10
Upgraded azure-search-documents to latest version using pip install --upgrade
Set AZURE_VERIFY_CERTS=false environment variable but still saw same error
Tried explicitly disabling cert verification in code using os.environ['AZURE_VERIFY_CERTS'] = "false"
Searched similar Azure Search Python issues on GitHub/StackOverflow with no solution working yet
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Did you try the steps suggested in the troubleshooting section of the readme?

"You see CERTIFICATE_VERIFY_FAILED when the prepdocs.py script runs. That's typically due to incorrect SSL certificates setup on your machine. Try the suggestions in this [StackOverflow answer](https://stackoverflow.com/questions/35569042/ssl-certificate-verify-failed-with-python3/43855394#43855394)."

**Comment by varunr02** [comment]
Hey. Thank you so much. The solution worked. The application is deployed properly. 

But right now it says this:

:( Application Error
If you are the application administrator, you can access the [diagnostic resources](https://app-backend-r7fgohvt2im5e.scm.azurewebsites.net/detectors).

Maybe I have to wait for some time.
