### ISSUE TITLE
setting virtual environment when deploying

### ISSUE THREAD

**Issue by MarusaOrazem** [Azure-Samples/azure-search-openai-demo#1040]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ x ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> I have build and deployed the application. It is running locally, but not on endpoint. Seems like the problem is in the packages installed in the virtual environment. 

### Any log messages given by the failure
>
```
2023-12-07T12:26:47.343442523Z    _____
2023-12-07T12:26:47.343472024Z   /  _  \ __________ _________   ____
2023-12-07T12:26:47.343477724Z  /  /_\  \\___   /  |  \_  __ \_/ __ \
2023-12-07T12:26:47.343482724Z /    |    \/    /|  |  /|  | \/\  ___/
2023-12-07T12:26:47.343487324Z \____|__  /_____ \____/ |__|    \___  >
2023-12-07T12:26:47.343492324Z         \/      \/                  \/
2023-12-07T12:26:47.343496824Z A P P   S E R V I C E   O N   L I N U X
2023-12-07T12:26:47.343518325Z
2023-12-07T12:26:47.343522725Z Documentation: http://aka.ms/webapp-linux
2023-12-07T12:26:47.343527225Z Python 3.11.4
2023-12-07T12:26:47.343531525Z Note: Any data outside '/home' is not persisted
2023-12-07T12:26:49.520633153Z Starting OpenBSD Secure Shell server: sshd.
2023-12-07T12:26:49.690044337Z Site's appCommandLine: python3 -m gunicorn main:app
2023-12-07T12:26:50.075184584Z Starting periodic command scheduler: cron.
2023-12-07T12:26:50.091640232Z Launching oryx with: create-script -appPath /home/site/wwwroot -output /opt/startup/startup.sh -virtualEnvName antenv -defaultApp /opt/defaultsite -userStartupCommand 'python3 -m gunicorn main:app'
2023-12-07T12:26:50.360368717Z Could not find build manifest file at '/home/site/wwwroot/oryx-manifest.toml'
2023-12-07T12:26:50.360429218Z Could not find operation ID in manifest. Generating an operation id...
2023-12-07T12:26:50.360436618Z Build Operation ID: f45d986a-7908-496f-8dfe-b5ca64d77e91
2023-12-07T12:26:50.848495273Z Oryx Version: 0.2.20230707.1, Commit: 0bd28e69919b5e8beba451e8677e3345f0be8361, ReleaseTagName: 20230707.1
2023-12-07T12:26:50.880020137Z Writing output script to '/opt/startup/startup.sh'
2023-12-07T12:26:50.937407809Z WARNING: Could not find virtual environment directory /home/site/wwwroot/antenv.
2023-12-07T12:26:50.939354563Z WARNING: Could not find package directory /home/site/wwwroot/__oryx_packages__.
2023-12-07T12:26:53.175997543Z
2023-12-07T12:26:53.176035144Z Error: class uri 'uvicorn.workers.UvicornWorker' invalid or not found:
2023-12-07T12:26:53.176041744Z
2023-12-07T12:26:53.176046744Z [Traceback (most recent call last):
2023-12-07T12:26:53.176051344Z   File "/opt/python/3/lib/python3.11/site-packages/gunicorn/util.py", line 99, in load_class
2023-12-07T12:26:53.176056144Z     mod = importlib.import_module('.'.join(components))
2023-12-07T12:26:53.176066445Z           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-07T12:26:53.176071045Z   File "/opt/python/3/lib/python3.11/importlib/__init__.py", line 126, in import_module
2023-12-07T12:26:53.176075745Z     return _bootstrap._gcd_import(name[level:], package, level)
2023-12-07T12:26:53.176080145Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-07T12:26:53.176084645Z   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
2023-12-07T12:26:53.176100646Z   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
2023-12-07T12:26:53.176105446Z   File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
2023-12-07T12:26:53.176110146Z   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2023-12-07T12:26:53.176114646Z   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
2023-12-07T12:26:53.176119046Z   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
2023-12-07T12:26:53.176123646Z   File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
2023-12-07T12:26:53.176128246Z ModuleNotFoundError: No module named 'uvicorn'
2023-12-07T12:26:53.176132646Z ]
2023-12-07T12:26:53.176136947Z

2023-12-07T12:26:53.820Z ERROR - Container app-backend-lxxxxxxxxx for site app-backend-lxxxxxxxxx has exited, failing site start
```
### Expected/desired behavior
> Found the right virtual environment so all the packages are installed for running the application.

### OS and Version?
> Windows 11

### azd version?
> azd version 1.5.0

### Versions
>

### Mention any other details that might be useful

 In the logs there is a line: WARNING: Could not find virtual environment directory /home/site/wwwroot/antenv. How do I copy packages to this virtual environment? Or how do I change it? What are my options? In the other logs found in other github issues, I have found:  Found build manifest file at '/home/site/wwwroot/oryx-manifest.toml'. Deserializing it...
Is this the step that I am missing? How could I fix this?
Thanks for you help.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
When you see "no module named uvicorn", that indicates that the deployment failed. Please go to the Azure Portal, select Deployment Center from the left nav, and select Logs. I expect you will see that the most recent deploy failed. You can click on it to see details to make sure the issue isn't with your code, but the error is more often on the App Service end.

In this situation, I typically run `azd deploy` to force a new deploy.

More details about deployment logs can be found in this blog post:
https://blog.pamelafox.org/2023/06/tips-for-debugging-flask-deployments-to.html

**Comment by MarusaOrazem** [comment]
Thanks. It is failing on cairo.pc.

log:
    Building wheels for collected packages: pycairo
        Building wheel for pycairo (pyproject.toml): started
       Building wheel for pycairo (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error\n      
        × Building wheel for pycairo (pyproject.toml) did not run successfully.\n        │ exit code: 1
        ╰─> [15 lines of output]\n            running bdist_wheel\n            running build\n            running build_py\n            creating build\n            creating build/lib.linux-x86_64-cpython-311\n            creating build/lib.linux-x86_64-cpython-311/cairo\n            copying cairo/__init__.py -> build/lib.linux-x86_64-cpython-311/cairo\n            copying cairo/__init__.pyi -> build/lib.linux-x86_64-cpython-311/cairo\n            copying cairo/py.typed -> build/lib.linux-x86_64-cpython-311/cairo\n            running build_ext\n            Package cairo was not found in the pkg-config search path.\n            Perhaps you should add the directory containing `cairo.pc'
            to the PKG_CONFIG_PATH environment variable
            No package 'cairo' found
            Command '['pkg-config', '--print-errors', '--exists', 'cairo >= 1.15.10']' returned non-zero exit status 1.
            [end of output]\n      \n        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for pycairo\n      Failed to build pycairo\n      ERROR: Could not build wheels for pycairo, which is required to install pyproject.toml-based projects\n   

Where do i need to install these things ?
I have run 
sudo apt install libcairo2-dev
sudo apt install libgirepository1.0-dev
sudo apt install libcairo2-dev pkg-config python3-dev
 sudo apt-get install libcairo2-dev libjpeg-dev libgif-dev

in the terminal in docker container in my Docker Desktop. All installed sucessfully. 

Is this not the right place to install those libraries?

**Comment by avi-arora** [comment]
Same is happening with me as well. 

tried using this thread as well: https://github.com/microsoft/Oryx/issues/1400

Still the issue is unresolved.
