### ISSUE TITLE
Error Parsing Headers

### ISSUE THREAD

**Issue by GangQ** [Azure-Samples/azure-search-openai-demo#1054]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> ./scripts/prepdoc.sh

### Any log messages given by the failure
> 
Traceback (most recent call last):
  File "/home/adm_gqu/openai01/./scripts/prepdocs.py", line 257, in <module>
    loop.run_until_complete(main(file_strategy, azd_credential, args))
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/adm_gqu/openai01/./scripts/prepdocs.py", line 132, in main
    await strategy.run(search_info)
  File "/home/adm_gqu/openai01/scripts/prepdocslib/filestrategy.py", line 63, in run
    await search_manager.update_content(sections)
  File "/home/adm_gqu/openai01/scripts/prepdocslib/searchmanager.py", line 150, in update_content
    embeddings = await self.embeddings.create_embeddings(
  File "/home/adm_gqu/openai01/scripts/prepdocslib/embeddings.py", line 122, in create_embeddings
    return await self.create_embedding_batch(texts)
  File "/home/adm_gqu/openai01/scripts/prepdocslib/embeddings.py", line 87, in create_embedding_batch
    async for attempt in AsyncRetrying(
  File "/home/adm_gqu/openai01/scripts/.venv/lib/python3.10/site-packages/tenacity/_asyncio.py", line 71, in __anext__
    do = self.iter(retry_state=self._retry_state)
  File "/home/adm_gqu/openai01/scripts/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 314, in iter
    return fut.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/adm_gqu/openai01/scripts/prepdocslib/embeddings.py", line 96, in create_embedding_batch
    emb_response = await client.embeddings.create(model=self.open_ai_model_name, input=batch.texts)
  File "/home/adm_gqu/openai01/scripts/.venv/lib/python3.10/site-packages/openai/resources/embeddings.py", line 198, in create
    return await self._post(
  File "/home/adm_gqu/openai01/scripts/.venv/lib/python3.10/site-packages/openai/_base_client.py", line 1546, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
  File "/home/adm_gqu/openai01/scripts/.venv/lib/python3.10/site-packages/openai/_base_client.py", line 1316, in request
    return await self._request(
  File "/home/adm_gqu/openai01/scripts/.venv/lib/python3.10/site-packages/openai/_base_client.py", line 1368, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: <html>
  <head>
    <title>Bad Request</title>
  </head>
  <body>
    <h1><p>Bad Request</p></h1>
    Error parsing headers: &#x27;limit request headers fields size&#x27;
  </body>
</html>

### Expected/desired behavior
>  this worked in the simpler version of prepdoc back in Sep, now it is failing in Centos 7 and Ubuntu 22.04.3

### OS and Version?
> Ubuntu 22.04.3

### azd version?
> run `azd version` and copy paste here.

### Versions
> 1.5.0

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by mattmsft** [comment]
thanks for reporting this - we'll investigate. Can you try using key authentication and see if that helps?

**Comment by mattmsft** [comment]
Hi @GangQ ,

can you please let us know
1. Are you using OpenAI embeddings, or Azure OpenAI embeddings?
2. Did you customize your data or use the existing sample data

**Comment by marufkilic** [comment]
Hello @mattmsft, we've encountered a similar issue. We're getting the following error during the embedding creation process. We're directly using Azure OpenAI. I've also attached a screenshot of the services we're using.

![image](https://github.com/Azure-Samples/azure-search-openai-demo/assets/8219567/44a62d06-3abd-4047-a1f4-ae548a601e79)

> batch texts: ['This is a really small pdf'] modelname: text-embedding-ada-002
INFO:httpx:HTTP Request: POST https://cog-s3vh6rhlyzisa.openai.azure.com/openai/deployments/embedding/embeddings?api-version=2023-05-15 "HTTP/1.1 400 model_error"
ERROR:app:Exception on request POST /upload
Traceback (most recent call last):
  File "/workspaces/azure_with_vision/app/backend/backend_env/lib/python3.11/site-packages/quart/app.py", line 1376, in handle_request
    return await self.full_dispatch_request(request_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/azure_with_vision/app/backend/backend_env/lib/python3.11/site-packages/quart/app.py", line 1414, in full_dispatch_request
    result = await self.handle_user_exception(error)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/azure_with_vision/app/backend/backend_env/lib/python3.11/site-packages/quart/app.py", line 1007, in handle_user_exception
    raise error
  File "/workspaces/azure_with_vision/app/backend/backend_env/lib/python3.11/site-packages/quart/app.py", line 1412, in full_dispatch_request
    result = await self.dispatch_request(request_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/azure_with_vision/app/backend/backend_env/lib/python3.11/site-packages/quart/app.py", line 1506, in dispatch_request
    return await self.ensure_async(handler)(**request_.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/azure_with_vision/app/backend/app.py", line 292, in fileUpload
    await main(file_strategy, azure_credential, args)
  File "/workspaces/azure_with_vision/app/backend/app.py", line 713, in main
    await strategy.run(search_info)
  File "/workspaces/azure_with_vision/app/backend/scripts/prepdocslib/filestrategy.py", line 76, in run
    await search_manager.update_content(sections, blob_image_embeddings)
  File "/workspaces/azure_with_vision/app/backend/scripts/prepdocslib/searchmanager.py", line 170, in update_content
    embeddings = await self.embeddings.create_embeddings(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/azure_with_vision/app/backend/scripts/prepdocslib/embeddings.py", line 122, in create_embeddings
    return await self.create_embedding_batch(texts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/azure_with_vision/app/backend/scripts/prepdocslib/embeddings.py", line 89, in create_embedding_batch
    async for attempt in AsyncRetrying(
  File "/workspaces/azure_with_vision/app/backend/backend_env/lib/python3.11/site-packages/tenacity/_asyncio.py", line 71, in __anext__
    do = self.iter(retry_state=self._retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/azure_with_vision/app/backend/backend_env/lib/python3.11/site-packages/tenacity/__init__.py", line 314, in iter
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/workspaces/azure_with_vision/app/backend/scripts/prepdocslib/embeddings.py", line 98, in create_embedding_batch
    emb_response = await client.embeddings.create(model=self.open_ai_model_name, input=batch.texts)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/azure_with_vision/app/backend/backend_env/lib/python3.11/site-packages/openai/resources/embeddings.py", line 198, in create
    return await self._post(
           ^^^^^^^^^^^^^^^^^
  File "/workspaces/azure_with_vision/app/backend/backend_env/lib/python3.11/site-packages/openai/_base_client.py", line 1542, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/azure_with_vision/app/backend/backend_env/lib/python3.11/site-packages/openai/_base_client.py", line 1316, in request
    return await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/azure_with_vision/app/backend/backend_env/lib/python3.11/site-packages/openai/_base_client.py", line 1368, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: <html>
  <head>
    <title>Bad Request</title>
  </head>
  <body>
    <h1><p>Bad Request</p></h1>
    Error parsing headers: &#x27;limit request headers fields size&#x27;
  </body>
</html>

**Comment by marufkilic** [comment]
@mattmsft also u can see the file content in belove

![image](https://github.com/Azure-Samples/azure-search-openai-demo/assets/8219567/f8f431f7-3874-4d32-a881-fb28e8f2001b)
