### ISSUE TITLE
How to fix missing modules in your Python environment issue?

### ISSUE THREAD

**Issue by kajasherif** [Azure-Samples/azure-search-openai-demo#106]
```
Running "prepdocs.py"
ModuleNotFoundError: No module named '_cffi_backend'
thread '<unnamed>' panicked at 'Python API call failed', C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\pyo3-0.15.2\src\err\mod.rs:582:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "D:\CodeSpace\Azure\azure-search-openai-demo\scripts\prepdocs.py", line 9, in <module>       
    from azure.identity import AzureDeveloperCliCredential
  File "D:\CodeSpace\Azure\azure-search-openai-demo\scripts\.venv\Lib\site-packages\azure\identity\__init__.py", line 10, in <module>
    from ._credentials import (
  File "D:\CodeSpace\Azure\azure-search-openai-demo\scripts\.venv\Lib\site-packages\azure\identity\_credentials\__init__.py", line 5, in <module>
    from .authorization_code import AuthorizationCodeCredential
  File "D:\CodeSpace\Azure\azure-search-openai-demo\scripts\.venv\Lib\site-packages\azure\identity\_credentials\authorization_code.py", line 9, in <module>
    from .._internal.aad_client import AadClient
  File "D:\CodeSpace\Azure\azure-search-openai-demo\scripts\.venv\Lib\site-packages\azure\identity\_internal\__init__.py", line 5, in <module>
    from .aad_client import AadClient
  File "D:\CodeSpace\Azure\azure-search-openai-demo\scripts\.venv\Lib\site-packages\azure\identity\_internal\aad_client.py", line 11, in <module>
    from .aad_client_base import AadClientBase
  File "D:\CodeSpace\Azure\azure-search-openai-demo\scripts\.venv\Lib\site-packages\azure\identity\_internal\aad_client_base.py", line 23, in <module>
    from .aadclient_certificate import AadClientCertificate
  File "D:\CodeSpace\Azure\azure-search-openai-demo\scripts\.venv\Lib\site-packages\azure\identity\_internal\aadclient_certificate.py", line 7, in <module>
    from cryptography import x509
  File "D:\CodeSpace\Azure\azure-search-openai-demo\scripts\.venv\Lib\site-packages\cryptography\x509\__init__.py", line 6, in <module>
    from cryptography.x509 import certificate_transparency
  File "D:\CodeSpace\Azure\azure-search-openai-demo\scripts\.venv\Lib\site-packages\cryptography\x509\certificate_transparency.py", line 10, in <module>
    from cryptography.hazmat.bindings._rust import x509 as rust_x509
pyo3_runtime.PanicException: Python API call failed

Executing predeploy hook => C:\Users\kajas\AppData\Local\Temp\azd-predeploy-1074636764.ps1

```

I tried ``` D:\CodeSpace\Azure\azure-search-openai-demo\scripts\.venv\scripts\python.exe -m pip install cffi ```
but not working in this method, again I will get same issue...

**Comment by krepko7** [comment]
I have this same issue once I moved to a new laptop.

**Comment by vhvb1989** [comment]
Try adding cffi to [requeriments](https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/scripts/requirements.txt)

According to [this](https://stackoverflow.com/questions/34370962/no-module-named-cffi-backend), you might need also: paramiko and cryptography

After you add the libs to requeriments, delete the .venv folder and run prepdocs.ps1 again

**Comment by Pancat007** [comment]
I tried to run the project in VS code locally, but I have similar issue but the module that I missed is quart,
I have added quart in /app/requirements.txt, /scripts/requirements.txt, but none of them worked,
I have manually install via pip install, still useless, anyone know how to fix this?

**Comment by pamelafox** [comment]
@Pancat007 Are you using a virtual environment or VS Code?  Can you share the full results of running ./start.sh? That should have installed quart for you, so I'm curious if there are any errors there. What Python version are you using?

**Comment by NicoPlattner** [comment]
I also had an issue with quart and had the following error when trying to run the project locally:
C:\Users\ ... \app\backend\backend_env\scripts\python.exe: No module named quart

Turned out that I had a build error due to missing build tools (on Windows 10 btw)

>       error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
>       [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
>   ERROR: Failed building wheel for multidict
> Failed to build frozenlist multidict
> ERROR: Could not build wheels for frozenlist, multidict, which is required to install pyproject.toml-based projects

This is because quart depends on aiohttps and because aiohttps depends on multidict

After installing the Build tools everything worked fine

**Comment by pamelafox** [comment]
Update: This issue can happen if you originally open the repo in a Dev Container, and then you re-open in a local folder. When that happens, delete your .venv and let the scripts re-create it.
