### ISSUE TITLE
prep docs step is failing during azd up

### ISSUE THREAD

**Issue by vrajroutu** [Azure-Samples/azure-search-openai-demo#1068]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

`azd up`

```
File "/Users/desk/Downloads/multimodal/scripts/prepdocslib/blobmanager.py", line 85, in upload_pdf_blob_images
    font = ImageFont.truetype("arial.ttf", 20)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vrajkishorerv/Downloads/multimodal/scripts/.venv/lib/python3.11/site-packages/PIL/ImageFont.py", line 797, in truetype
    return freetype(font)
           ^^^^^^^^^^^^^^
  File "/Users/desk/Downloads/multimodal/scripts/.venv/lib/python3.11/site-packages/PIL/ImageFont.py", line 794, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/desk/Downloads/multimodal/scripts/.venv/lib/python3.11/site-packages/PIL/ImageFont.py", line 226, in __init__
    self.font = core.getfont(
                ^^^^^^^^^^^^^
OSError: cannot open resource

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/desk/Downloads/multimodal/./scripts/prepdocs.py", line 310, in <module>
    loop.run_until_complete(main(file_strategy, azd_credential, args))
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/desk/Downloads/multimodal/./scripts/prepdocs.py", line 160, in main
    await strategy.run(search_info)
  File "/Users/desk/Downloads/multimodal/scripts/prepdocslib/filestrategy.py", line 72, in run
    blob_sas_uris = await self.blob_manager.upload_blob(file)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/desk/Downloads/multimodal/scripts/prepdocslib/blobmanager.py", line 51, in upload_blob
    return await self.upload_pdf_blob_images(service_client, container_client, file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/desk/Downloads/multimodal/scripts/prepdocslib/blobmanager.py", line 87, in upload_pdf_blob_images
    font = ImageFont.truetype("/usr/share/fonts/truetype/freefont/FreeMono.ttf", 20)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/desk/Downloads/multimodal/scripts/.venv/lib/python3.11/site-packages/PIL/ImageFont.py", line 797, in truetype
    return freetype(font)
           ^^^^^^^^^^^^^^
  File "/Users/desk/Downloads/multimodal/scripts/.venv/lib/python3.11/site-packages/PIL/ImageFont.py", line 794, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/desk/Downloads/multimodal/scripts/.venv/lib/python3.11/site-packages/PIL/ImageFont.py", line 226, in __init__
    self.font = core.getfont(
                ^^^^^^^^^^^^^
OSError: cannot open resource
```

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Ah I fixed that in a branch, but didnt merge that branch. You can set font = None and it works fine, in my experience. Thanks for filing, I'll send a PR!
