### ISSUE TITLE
Azure Document Intelligence failed. ---Bad Request

### ISSUE THREAD

**Issue by toby080508050805** [Azure-Samples/azure-search-openai-demo#1097]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Follow the document to run azd up

### Any log messages given by the failure
>

Splitting 'test4.pdf' into sections
        Uploading blob for whole file -> test4.pdf
Traceback (most recent call last):
  File "/workspaces/azure-search-openai-demo/./scripts/prepdocs.py", line 310, in <module>
    loop.run_until_complete(main(file_strategy, azd_credential, args))
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/workspaces/azure-search-openai-demo/./scripts/prepdocs.py", line 160, in main
    await strategy.run(search_info)
  File "/workspaces/azure-search-openai-demo/scripts/prepdocslib/filestrategy.py", line 76, in run
    await search_manager.update_content(sections, blob_image_embeddings)
  File "/workspaces/azure-search-openai-demo/scripts/prepdocslib/searchmanager.py", line 170, in update_content
    embeddings = await self.embeddings.create_embeddings(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/azure-search-openai-demo/scripts/prepdocslib/embeddings.py", line 118, in create_embeddings
    return await self.create_embedding_batch(texts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/azure-search-openai-demo/scripts/prepdocslib/embeddings.py", line 89, in create_embedding_batch
    async for attempt in AsyncRetrying(
  File "/workspaces/azure-search-openai-demo/scripts/.venv/lib/python3.11/site-packages/tenacity/_asyncio.py", line 71, in __anext__
    do = self.iter(retry_state=self._retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/azure-search-openai-demo/scripts/.venv/lib/python3.11/site-packages/tenacity/__init__.py", line 314, in iter
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/workspaces/azure-search-openai-demo/scripts/prepdocslib/embeddings.py", line 96, in create_embedding_batch
    emb_response = await client.embeddings.create(model=self.open_ai_model_name, input=batch.texts)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/azure-search-openai-demo/scripts/.venv/lib/python3.11/site-packages/openai/resources/embeddings.py", line 198, in create
    return await self._post(
           ^^^^^^^^^^^^^^^^^
  File "/workspaces/azure-search-openai-demo/scripts/.venv/lib/python3.11/site-packages/openai/_base_client.py", line 1542, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/azure-search-openai-demo/scripts/.venv/lib/python3.11/site-packages/openai/_base_client.py", line 1316, in request
    return await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/azure-search-openai-demo/scripts/.venv/lib/python3.11/site-packages/openai/_base_client.py", line 1368, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: <html>
  <head>
    <title>Bad Request</title>
  </head>
  <body>
    <h1><p>Bad Request</p></h1>
    Error parsing headers: &#x27;limit request headers fields size&#x27;
  </body>
</html>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

Linux cc45c391c6c7 5.15.133.1-microsoft-standard-WSL2 #1 SMP Thu Oct 5 21:02:42 UTC 2023 x86_64 GNU/Linux

### azd version?
> run `azd version` and copy paste here.

azd version 1.5.1 (commit 3856d1e98281683b8d112e222c0a7c7b3e148e96)
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by mattmsft** [comment]
Thanks for reporting this - we'll investigate.

In the meantime - can you try using key-based authentication? If you add --formrecognizerkey YOUR_DOCUMENT_INTELLIGENCE_KEY to the prepdocs command line, let us know if that works

**Comment by mattmsft** [comment]
Hi @toby080508050805 ,

can you please let us know
1. Are you using OpenAI embeddings, or Azure OpenAI embeddings?
2. Did you customize your data or use the existing sample data

**Comment by toby080508050805** [comment]
Hi Matt,

Thanks for your reply.

1.If you add --formrecognizerkey YOUR_DOCUMENT_INTELLIGENCE_KEY to the prepdocs command line, let us know if that works  <== May I know how to do it ??  

2.  I followed the instruction from readme.md  to create the docker and did not change anything.

Start Docker Desktop (install it if not already installed)
Open the project: Open in Dev Containers
In the VS Code window that opens, once the project files show up (this may take several minutes), open a terminal window
Run azd auth login
Now you can follow the instructions in [Deploying from scratch](https://github.com/Azure-Samples/azure-search-openai-demo?tab=readme-ov-file#deploying-from-scratch) below


3.I apply the sample data have the issue so I create my own test data which only have few lines to test.

**Comment by toby080508050805** [comment]
I add the parameter you mention at very end of prepdocs.sh but it still not work.
--formrecognizerkey "e55d4b6b1******************9d9b3"  \

**Comment by mattgotteiner** [comment]
Hi @toby080508050805 ,

can you please let us know

Are you using OpenAI embeddings, or Azure OpenAI embeddings?
Did you customize your data or use the existing sample data

**Comment by giuliotosato** [comment]
@mattgotteiner I have the same issue here, 

1. I downloaded the repository with docker, 
2. I have not modified the data folder, 
3. I am using Azure openai embeddings. 

This is my first time that I do azd up after that the gpt4 with vision was introduced previously this repo was working like a charm, this is the problem:

Packaging services (azd package)


up to date, audited 260 packages in 1s

found 0 vulnerabilities
  |=======| Packaging service backend
> frontend@0.0.0 build
> tsc && vite build

  |     ==| Packaging service backendvite v4.5.1 building for production...
✓ 4200 modules transformed.
../backend/static/index.html                             0.76 kB │ gzip:   0.38 kB
../backend/static/assets/github-fab00c2d.svg             0.96 kB │ gzip:   0.52 kB
../backend/static/assets/OneShot-daa12333.css            0.83 kB │ gzip:   0.39 kB
../backend/static/assets/index-54ce2544.css              7.28 kB │ gzip:   2.25 kB
../backend/static/assets/NoPage-ea4b1efc.js              0.18 kB │ gzip:   0.18 kB │ map:     0.35 kB
../backend/static/assets/OneShot-efb8c1be.js             4.87 kB │ gzip:   2.06 kB │ map:    20.88 kB
../backend/static/assets/fluentui-icons-e67e11a4.js      5.67 kB │ gzip:   2.56 kB │ map: 4,322.77 kB
../backend/static/assets/index-67467094.js              24.98 kB │ gzip:   8.86 kB │ map:    97.05 kB
../backend/static/assets/fluentui-react-63b3d3f8.js    337.68 kB │ gzip:  95.09 kB │ map: 1,480.88 kB
../backend/static/assets/vendor-7810ac01.js          1,687.91 kB │ gzip: 535.84 kB │ map: 5,151.39 kB

(!) Some chunks are larger than 500 kBs after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
✓ built in 13.41s
  (✓) Done: Packaging service backend
  - Package Output: /tmp/azure-search-openai-demo-backend-azddeploy-1704791032.zip
Checking if authentication should be setup...
Loading azd .env file from current environment...
AZURE_USE_AUTHENTICATION is not set, skipping authentication setup.

Provisioning Azure resources (azd provision)
Provisioning Azure resources can take some time.

Subscription: Azure subscription 1 (7db609df-53d4-4345-857e-68d76c86f557)
Location: France Central

? Enter a value for the 'openAiResourceGroupLocation' infrastructure parameter:  4. (Europe) France Central (francecentral)
? Save the value in the environment for future use No

  You can view detailed progress in the Azure Portal:
  https://portal.azure.com*******************************

  (✓) Done: Resource group: rg-***************
  (✓) Done: Storage account: st3***************
  (✓) Done: Search service: gptkb-37***************
  (✓) Done: App Service plan: plan-37***************
  (✓) Done: Log Analytics workspace: log-37***************
  (✓) Done: Azure OpenAI: cog-37***************
  (✓) Done: Application Insights: appi-37***************
  (✓) Done: Form recognizer: cog-fr-37***************
  (✓) Done: Portal dashboard: dash-37k***************
  (✓) Done: App Service: app-backend-37k***************
Loading azd .env file from current environment...
Creating Python virtual environment "scripts/.venv"...
Installing dependencies from "requirements.txt" into virtual environment (in quiet mode)...






Not updating authentication.
Loading azd .env file from current environment...
Creating Python virtual environment "scripts/.venv"...
Installing dependencies from "requirements.txt" into virtual environment (in quiet mode)...
Running "prepdocs.py"
Processing files...
Using local files in ./data/*
Ensuring search index gptkbindex exists
Creating gptkbindex search index
Extracting text from './data/GPT4V_Examples/Financial Market Analysis Report 2023.pdf' using Azure Document Intelligence
Splitting 'Financial Market Analysis Report 2023.pdf' into sections
        Uploading blob for whole file -> Financial Market Analysis Report 2023.pdf
Traceback (most recent call last):
  File "/workspaces/azure_with_vision/./scripts/prepdocs.py", line 310, in <module>
    loop.run_until_complete(main(file_strategy, azd_credential, args))
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/workspaces/azure_with_vision/./scripts/prepdocs.py", line 160, in main
    await strategy.run(search_info)
  File "/workspaces/azure_with_vision/scripts/prepdocslib/filestrategy.py", line 76, in run
    await search_manager.update_content(sections, blob_image_embeddings)
  File "/workspaces/azure_with_vision/scripts/prepdocslib/searchmanager.py", line 170, in update_content
    embeddings = await self.embeddings.create_embeddings(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/azure_with_vision/scripts/prepdocslib/embeddings.py", line 118, in create_embeddings
    return await self.create_embedding_batch(texts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/azure_with_vision/scripts/prepdocslib/embeddings.py", line 89, in create_embedding_batch
    async for attempt in AsyncRetrying(
  File "/workspaces/azure_with_vision/scripts/.venv/lib/python3.11/site-packages/tenacity/_asyncio.py", line 71, in __anext__
    do = self.iter(retry_state=self._retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/azure_with_vision/scripts/.venv/lib/python3.11/site-packages/tenacity/__init__.py", line 314, in iter
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/workspaces/azure_with_vision/scripts/prepdocslib/embeddings.py", line 96, in create_embedding_batch
    emb_response = await client.embeddings.create(model=self.open_ai_model_name, input=batch.texts)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/azure_with_vision/scripts/.venv/lib/python3.11/site-packages/openai/resources/embeddings.py", line 198, in create
    return await self._post(
           ^^^^^^^^^^^^^^^^^
  File "/workspaces/azure_with_vision/scripts/.venv/lib/python3.11/site-packages/openai/_base_client.py", line 1542, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/azure_with_vision/scripts/.venv/lib/python3.11/site-packages/openai/_base_client.py", line 1316, in request
    return await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/azure_with_vision/scripts/.venv/lib/python3.11/site-packages/openai/_base_client.py", line 1368, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: <html>
  <head>
    <title>Bad Request</title>
  </head>
  <body>
    <h1><p>Bad Request</p></h1>
    Error parsing headers: &#x27;limit request headers fields size&#x27;
  </body>
</html>

**Comment by giuliotosato** [comment]
@mattgotteiner 
**Update**: the issue disappear when I use openai api key instead of azure openai. In our organization, the only person that is able to run the repo with azure openai is the owner of the entire azure system, all the other people have the previous error.
