### ISSUE TITLE
:( Application Error If you are the application administrator, you can access the diagnostic resources

### ISSUE THREAD

**Issue by reshma67** [Azure-Samples/azure-search-openai-demo#1222]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by reshma67** [comment]
2024-02-02T08:37:48.853Z INFO  - Waiting for response to warmup request for container app-backend-2mac5eed5qoz4_0_771da43a. Elapsed time = 17.1448596 sec/home/LogFiles/2024_02_02_lw0sdlwk00014T_easyauth_docker.log  (https://app-backend-2mac5eed5qoz4.scm.azurewebsites.net/api/vfs/LogFiles/2024_02_02_lw0sdlwk00014T_easyauth_docker.log)/home/LogFiles/2024_02_02_lw0sdlwk00014T_msi_docker.log  (https://app-backend-2mac5eed5qoz4.scm.azurewebsites.net/api/vfs/LogFiles/2024_02_02_lw0sdlwk00014T_msi_docker.log)Ending Log Tail of existing logs ---Starting Live Log Stream ---
:31.709Z INFO  - Initiating warmup request to container app-backend-2mac5eed5qoz4_0_771da43a_msiProxy for site app-backend-2mac5eed5qoz4
2024-02-02T08:37:31.942Z INFO  - Container app-backend-2mac5eed5qoz4_0_771da43a_msiProxy for site app-backend-2mac5eed5qoz4 initialized successfully and is ready to serve requests.
2024-02-02T08:37:31.942Z INFO  - Initiating warmup request to container app-backend-2mac5eed5qoz4_0_771da43a for site app-backend-2mac5eed5qoz4
2024-02-02T08:37:48.853Z INFO  - Waiting for response to warmup request for container app-backend-2mac5eed5qoz4_0_771da43a. Elapsed time = 17.1448596 sec
2024-02-02 08:37:56,725  [MainThread] [DEBUG] : Initializating AppServiceAppLogging
2024-02-02 08:37:56,726  [MainThread] [DEBUG] : Initialized AppServiceAppLogging
2024-02-02 08:37:56,741  [Thread-1 (] [DEBUG] : Did not find any previously bound socket
2024-02-02T08:37:23.251997439Z    _____
2024-02-02T08:37:23.252071644Z   /  _  \ __________ _________   ____
2024-02-02T08:37:23.252077744Z  /  /_\  \\___   /  |  \_  __ \_/ __ \
2024-02-02T08:37:23.252082645Z /    |    \/    /|  |  /|  | \/\  ___/
2024-02-02T08:37:23.252087245Z \____|__  /_____ \____/ |__|    \___  >
2024-02-02T08:37:23.252102246Z         \/      \/                  \/
2024-02-02T08:37:23.252112647Z A P P   S E R V I C E   O N   L I N U X
2024-02-02T08:37:23.252117147Z
2024-02-02T08:37:23.252121347Z Documentation: http://aka.ms/webapp-linux
2024-02-02T08:37:23.252125648Z Python 3.11.4
2024-02-02T08:37:23.252129748Z Note: Any data outside '/home' is not persisted
2024-02-02T08:37:30.180817676Z Starting OpenBSD Secure Shell server: sshd.
2024-02-02T08:37:30.527725324Z App Command Line not configured, will attempt auto-detect
2024-02-02T08:37:30.527756226Z Launching oryx with: create-script -appPath /home/site/wwwroot -output /opt/startup/startup.sh -virtualEnvName antenv -defaultApp /opt/defaultsite
2024-02-02T08:37:30.882689423Z Found build manifest file at '/home/site/wwwroot/oryx-manifest.toml'. Deserializing it...
2024-02-02T08:37:30.899964706Z Build Operation ID: af8708eb2f0d4b5d
2024-02-02T08:37:30.901643321Z Oryx Version: 0.2.20230707.1, Commit: 0bd28e69919b5e8beba451e8677e3345f0be8361, ReleaseTagName: 20230707.1
2024-02-02T08:37:30.902613587Z Output is compressed. Extracting it...
2024-02-02T08:37:30.920137587Z Extracting '/home/site/wwwroot/output.tar.gz' to directory '/tmp/8dc23c40559009e'...
2024-02-02T08:37:54.278491463Z App path is set to '/tmp/8dc23c40559009e'
2024-02-02T08:37:54.301576851Z Detected an app based on Flask
2024-02-02T08:37:54.302625891Z Generating `gunicorn` command for 'app:app'
2024-02-02T08:37:54.329751034Z Writing output script to '/opt/startup/startup.sh'
2024-02-02T08:37:54.726209777Z Using packages from virtual environment antenv located at /tmp/8dc23c40559009e/antenv.
2024-02-02T08:37:54.726246778Z Updated PYTHONPATH to '/opt/startup/app_logs:/tmp/8dc23c40559009e/antenv/lib/python3.11/site-packages'
2024-02-02T08:37:56.705334332Z [2024-02-02 08:37:56 +0000] [73] [INFO] Starting gunicorn 20.1.0
2024-02-02T08:37:56.731514538Z [2024-02-02 08:37:56 +0000] [73] [INFO] Listening at: http://0.0.0.0:8000 (73)
2024-02-02T08:37:56.733329908Z [2024-02-02 08:37:56 +0000] [73] [INFO] Using worker: sync
2024-02-02T08:37:56.754148207Z [2024-02-02 08:37:56 +0000] [76] [INFO] Booting worker with pid: 76
2024-02-02T08:37:56.772276404Z [2024-02-02 08:37:56 +0000] [77] [INFO] Booting worker with pid: 77
2024-02-02T08:37:56.893238551Z [2024-02-02 08:37:56 +0000] [78] [INFO] Booting worker with pid: 78
2024-02-02T08:38:33.515183614Z Failed to find attribute 'app' in 'app'.
2024-02-02T08:38:33.515710248Z [2024-02-02 08:38:33 +0000] [78] [INFO] Worker exiting (pid: 78)
2024-02-02T08:38:33.536160493Z Failed to find attribute 'app' in 'app'.
2024-02-02T08:38:33.555115939Z [2024-02-02 08:38:33 +0000] [77] [INFO] Worker exiting (pid: 77)
2024-02-02T08:38:33.800401967Z Failed to find attribute 'app' in 'app'.
2024-02-02T08:38:33.806834890Z [2024-02-02 08:38:33 +0000] [76] [INFO] Worker exiting (pid: 76)
2024-02-02T08:38:37.926353088Z Traceback (most recent call last):
2024-02-02T08:38:37.926393191Z   File "/opt/python/3.11.4/lib/python3.11/site-packages/gunicorn/arbiter.py", line 209, in run
2024-02-02T08:38:37.935559365Z     self.sleep()
2024-02-02T08:38:37.936721538Z   File "/opt/python/3.11.4/lib/python3.11/site-packages/gunicorn/arbiter.py", line 357, in sleep
2024-02-02T08:38:37.944183206Z     ready = select.select([self.PIPE[0]], [], [], 1.0)
2024-02-02T08:38:37.945550291Z             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-02T08:38:37.945569592Z   File "/opt/python/3.11.4/lib/python3.11/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
2024-02-02T08:38:37.945575493Z     self.reap_workers()
2024-02-02T08:38:37.953232673Z   File "/opt/python/3.11.4/lib/python3.11/site-packages/gunicorn/arbiter.py", line 528, in reap_workers
2024-02-02T08:38:37.954045324Z     raise HaltServer(reason, self.APP_LOAD_ERROR)
2024-02-02T08:38:37.954061425Z gunicorn.errors.HaltServer: <HaltServer 'App failed to load.' 4>
2024-02-02T08:38:37.954068025Z
2024-02-02T08:38:37.954072725Z During handling of the above exception, another exception occurred:
2024-02-02T08:38:37.964228862Z
2024-02-02T08:38:37.964249663Z Traceback (most recent call last):
2024-02-02T08:38:37.964255463Z   File "/opt/python/3/bin/gunicorn", line 8, in <module>
2024-02-02T08:38:37.964260764Z     sys.exit(run())
2024-02-02T08:38:37.964265364Z              ^^^^^
2024-02-02T08:38:37.964269664Z   File "/opt/python/3.11.4/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
2024-02-02T08:38:37.964274365Z     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
2024-02-02T08:38:37.964278865Z   File "/opt/python/3.11.4/lib/python3.11/site-packages/gunicorn/app/base.py", line 231, in run
2024-02-02T08:38:37.966722718Z     super().run()
2024-02-02T08:38:37.986845079Z   File "/opt/python/3.11.4/lib/python3.11/site-packages/gunicorn/app/base.py", line 72, in run
2024-02-02T08:38:37.986878881Z     Arbiter(self).run()
2024-02-02T08:38:37.986885682Z   File "/opt/python/3.11.4/lib/python3.11/site-packages/gunicorn/arbiter.py", line 229, in run
2024-02-02T08:38:37.986890882Z     self.halt(reason=inst.reason, exit_status=inst.exit_status)
2024-02-02T08:38:37.986895682Z   File "/opt/python/3.11.4/lib/python3.11/site-packages/gunicorn/arbiter.py", line 342, in halt
2024-02-02T08:38:37.986900483Z     self.stop()
2024-02-02T08:38:37.986914683Z   File "/opt/python/3.11.4/lib/python3.11/site-packages/gunicorn/arbiter.py", line 393, in stop
2024-02-02T08:38:37.986919484Z     time.sleep(0.1)
2024-02-02T08:38:37.986923784Z   File "/opt/python/3.11.4/lib/python3.11/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
2024-02-02T08:38:37.986928484Z [2024-02-02 08:38:37 +0000] [73] [WARNING] Worker with pid 76 was terminated due to signal 15
2024-02-02T08:38:37.986933085Z     self.reap_workers()
2024-02-02T08:38:37.986937585Z   File "/opt/python/3.11.4/lib/python3.11/site-packages/gunicorn/arbiter.py", line 528, in reap_workers
2024-02-02T08:38:37.986942185Z     raise HaltServer(reason, self.APP_LOAD_ERROR)
2024-02-02T08:38:37.986951886Z gunicorn.errors.HaltServer: <HaltServer 'App failed to load.' 4>
2024-02-02T08:38:38.989Z ERROR - Container app-backend-2mac5eed5qoz4_0_771da43a for site app-backend-2mac5eed5qoz4 has exited, failing site start
2024-02-02T08:38:38.989Z INFO  - Initiating warmup request to container app-backend-2mac5eed5qoz4_0_771da43a_middleware for site app-backend-2mac5eed5qoz4
2024-02-02T08:38:39.357Z INFO  - Container app-backend-2mac5eed5qoz4_0_771da43a_middleware for site app-backend-2mac5eed5qoz4 initialized successfully and is ready to serve requests.
2024-02-02T08:38:39.367Z ERROR - Container app-backend-2mac5eed5qoz4_0_771da43a didn't respond to HTTP pings on port: 8000, failing site start. See container logs for debugging.
2024-02-02T08:38:39.478Z INFO  - Stopping site app-backend-2mac5eed5qoz4 because it failed during startup.
2024-02-02 08:38:39.063 +00:00 [Debug] Microsoft.AspNetCore.Server.Kestrel.Connections: Connection id "0HN13P9D9VCK3" accepted.
2024-02-02 08:38:39.072 +00:00 [Debug] Microsoft.AspNetCore.Server.Kestrel.Connections: Connection id "0HN13P9D9VCK3" started.
2024-02-02 08:38:39.188 +00:00 [Information] Microsoft.AspNetCore.Hosting.Diagnostics: Request starting HTTP/1.1 GET http://169.254.130.11:8181/robots933456.txt - -
2024-02-02T08:39:52  No new trace in the past 1 min(s).

**Comment by mattgotteiner** [comment]
Seems like app services failed to deploy correctly here. Can you please try re-running `azd deploy`?

**Comment by reshma67** [comment]
its resolved now

**Comment by VirajVaitha123** [comment]
How did you resolve this?
