### ISSUE TITLE
Is there a PDF file size or page limit? Errors occur for larger files when uploading documents.

### ISSUE THREAD

**Issue by bixinhaner** [Azure-Samples/azure-search-openai-demo#124]
Is there a PDF file size or page limit? Errors occur for larger files when uploading documents.

Below is the error:
       ......
       Uploading blob for page 639 -> 3G Evolution_HSPA and LTE for Mobile Broadband_2ed-639.pdf
        Uploading blob for page 640 -> 3G Evolution_HSPA and LTE for Mobile Broadband_2ed-640.pdf
        Uploading blob for page 641 -> 3G Evolution_HSPA and LTE for Mobile Broadband_2ed-641.pdf
        Uploading blob for page 642 -> 3G Evolution_HSPA and LTE for Mobile Broadband_2ed-642.pdf
        Uploading blob for page 643 -> 3G Evolution_HSPA and LTE for Mobile Broadband_2ed-643.pdf
        Uploading blob for page 644 -> 3G Evolution_HSPA and LTE for Mobile Broadband_2ed-644.pdf
        Uploading blob for page 645 -> 3G Evolution_HSPA and LTE for Mobile Broadband_2ed-645.pdf
        Uploading blob for page 646 -> 3G Evolution_HSPA and LTE for Mobile Broadband_2ed-646.pdf
        Uploading blob for page 647 -> 3G Evolution_HSPA and LTE for Mobile Broadband_2ed-647.pdf
        Uploading blob for page 648 -> 3G Evolution_HSPA and LTE for Mobile Broadband_2ed-648.pdf
        Uploading blob for page 649 -> 3G Evolution_HSPA and LTE for Mobile Broadband_2ed-649.pdf
        Uploading blob for page 650 -> 3G Evolution_HSPA and LTE for Mobile Broadband_2ed-650.pdf
Extracting text from 'D:\Enterprise-Knowledge-Base-Search-main\Enterprise-Knowledge-Base-Search-main/data\3G Evolution_HSPA and LTE for Mobile Broadband_2ed.pdf' using Azure Form Recognizer
Unable to retrieve continuation token: cannot pickle '_io.BufferedReader' object
Traceback (most recent call last):
  File "D:\Enterprise-Knowledge-Base-Search-main\Enterprise-Knowledge-Base-Search-main\scripts\.venv\Lib\site-packages\azure\core\pipeline\policies\_universal.py", line 607, in deserialize_from_text
    return json.loads(data_as_str)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 43854900 (char 43854899)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Enterprise-Knowledge-Base-Search-main\Enterprise-Knowledge-Base-Search-main\scripts\prepdocs.py", line 313, in <module>
    page_map = get_document_text(filename)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Enterprise-Knowledge-Base-Search-main\Enterprise-Knowledge-Base-Search-main\scripts\prepdocs.py", line 130, in get_document_text
    form_recognizer_results = poller.result()
                              ^^^^^^^^^^^^^^^
  File "D:\Enterprise-Knowledge-Base-Search-main\Enterprise-Knowledge-Base-Search-main\scripts\.venv\Lib\site-packages\azure\core\polling\_poller.py", line 230, in result
    self.wait(timeout)
  File "D:\Enterprise-Knowledge-Base-Search-main\Enterprise-Knowledge-Base-Search-main\scripts\.venv\Lib\site-packages\azure\core\tracing\decorator.py", line 76, in wrapper_use_tracer
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Enterprise-Knowledge-Base-Search-main\Enterprise-Knowledge-Base-Search-main\scripts\.venv\Lib\site-packages\azure\core\polling\_poller.py", line 249, in wait
    raise self._exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Enterprise-Knowledge-Base-Search-main\Enterprise-Knowledge-Base-Search-main\scripts\.venv\Lib\site-packages\azure\core\polling\_poller.py", line 169, in _start
    self._polling_method.run()
  File "D:\Enterprise-Knowledge-Base-Search-main\Enterprise-Knowledge-Base-Search-main\scripts\.venv\Lib\site-packages\azure\core\polling\base_polling.py", line 466, in run
    self._poll()
  File "D:\Enterprise-Knowledge-Base-Search-main\Enterprise-Knowledge-Base-Search-main\scripts\.venv\Lib\site-packages\azure\core\polling\base_polling.py", line 497, in _poll
    self.update_status()
  File "D:\Enterprise-Knowledge-Base-Search-main\Enterprise-Knowledge-Base-Search-main\scripts\.venv\Lib\site-packages\azure\core\polling\base_polling.py", line 536, in update_status
    self._pipeline_response = self.request_status(self._operation.get_polling_url())
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Enterprise-Knowledge-Base-Search-main\Enterprise-Knowledge-Base-Search-main\scripts\.venv\Lib\site-packages\azure\core\polling\base_polling.py", line 564, in request_status
    return self._client._pipeline.run(  # pylint: disable=protected-access
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Enterprise-Knowledge-Base-Search-main\Enterprise-Knowledge-Base-Search-main\scripts\.venv\Lib\site-packages\azure\core\pipeline\_base.py", line 202, in run
    return first_node.send(pipeline_request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Enterprise-Knowledge-Base-Search-main\Enterprise-Knowledge-Base-Search-main\scripts\.venv\Lib\site-packages\azure\core\pipeline\_base.py", line 70, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Enterprise-Knowledge-Base-Search-main\Enterprise-Knowledge-Base-Search-main\scripts\.venv\Lib\site-packages\azure\core\pipeline\_base.py", line 70, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Enterprise-Knowledge-Base-Search-main\Enterprise-Knowledge-Base-Search-main\scripts\.venv\Lib\site-packages\azure\core\pipeline\_base.py", line 70, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 1 more time]
  File "D:\Enterprise-Knowledge-Base-Search-main\Enterprise-Knowledge-Base-Search-main\scripts\.venv\Lib\site-packages\azure\core\pipeline\_base.py", line 75, in send
    _await_result(self._policy.on_response, request, response)
  File "D:\Enterprise-Knowledge-Base-Search-main\Enterprise-Knowledge-Base-Search-main\scripts\.venv\Lib\site-packages\azure\core\pipeline\_tools.py", line 35, in await_result
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Enterprise-Knowledge-Base-Search-main\Enterprise-Knowledge-Base-Search-main\scripts\.venv\Lib\site-packages\azure\core\pipeline\policies\_universal.py", line 712, in on_response
    response.context[self.CONTEXT_NAME] = self.deserialize_from_http_generics(
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Enterprise-Knowledge-Base-Search-main\Enterprise-Knowledge-Base-Search-main\scripts\.venv\Lib\site-packages\azure\core\pipeline\policies\_universal.py", line 677, in deserialize_from_http_generics
    return cls.deserialize_from_text(response.text(encoding), mime_type, response=response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Enterprise-Knowledge-Base-Search-main\Enterprise-Knowledge-Base-Search-main\scripts\.venv\Lib\site-packages\azure\core\pipeline\policies\_universal.py", line 609, in deserialize_from_text
    raise DecodeError(
azure.core.exceptions.DecodeError: JSON is invalid: Unterminated string starting at: line 1 column 43854900 (char 43854899)
Content: {"status":"succeeded","createdDateTime":"2023-04-17T20:09:42Z","lastUpdatedDateTime":"2023-04-17T20:10:53Z","analyzeResult":{"apiVersion":"2022-08-31","modelId":"prebuilt-layout","stringIndexType":"unicodeCodePoint","content":"Second edition\n3G Evolution\nHSPA and LTE for Mobile Broadband\nErik Dahlman Stefan Parkvall Johan Sköld Per Beming\n3G EVOLUTION : HSPA AND LTE FOR MOBILE BROADBAND\nThis page intentionally left blank\n3G Evolution\nHSPA and LTE for Mobile Broadband\nSecond edition Erik Dahlman, Stefan Parkvall, Johan Sköld and Per Beming\nAMSTERDAM • BOSTON • HEIDELBERG • LONDON • NEW YORK • OXFORD PARIS • SAN DIEGO • SAN FRANCISCO • SINGAPORE • SYDNEY • TOKYO ELSEVIER\nAcademic Press is an imprint of Elsevier\nAP\nAcademic Press is an imprint of Elsevier Linacre House, Jordan Hill, Oxford, OX2 8DP 30 Corporate Drive, Burlington, MA 01803\nFirst edition 2007 Second edition 2008\nCopyright © 2008. Erik Dahlman, Stefan Parkvall, Johan Sköld and Per Beming. Published by Elsevier Ltd. All rights reserved\nThe right of Erik Dahlman, Stefan Parkvall, Johan Sköld and Per Beming to be identified as the authors of this work has been asserted in accordance with the Copyright, Designs and Patents Act 1988\nNo part of this publication may be reproduced, stored in a retrieval system or transmitted in any form or by any means electronic, mechanical, photocopying, recording or otherwise without the prior written permission of the publisher\nPermission may be sought directly from Elsevier’s Science & Technology Rights Department in Oxford, UK: phone ( 44) (0) 1865 843830; fax ( 44) (0) 1865 853333; email: permissions@elsevier.com. Alternatively you can submit your request online by visiting the Elsevier website at http://www.elsevier.com/locate/permissions , and selecting Obtaining permission to use Elsevier material +\nNotice\nNo responsibility is assumed by the publisher for any injury and/or damage to persons or property

**Comment by bixinhaner** [comment]
I repeated the test several times. Found that pdf's with more than 500 pages give errors. Does anyone know where I can change this limit?

**Comment by jimmylevell** [comment]
I have stumbled upon a similar issue. In my case I was able to solve the issue by updating the related [pypdf](https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/scripts/requirements.txt) (pypdf==3.7.1) dependency.

**Comment by bixinhaner** [comment]
@jimmylevell This issue is perfectly solved. Thanks a lot!

**Comment by llmon22** [comment]
Now with pypdf==3.9.0 I also have issues uploading larger PDFs (in my case 360 pages) via prepdocs.ps1. Does someone have the same problem? Might there be another solution/workaround except splitting the PDF into 2 PDFs before running the script?
