### ISSUE TITLE
Cannot Perform Search on User Interface due to Authorization Failure

### ISSUE THREAD

**Issue by amarpatel-xx** [Azure-Samples/azure-search-openai-demo#1299]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
azd auth login
azd env set OPENAI_HOST openai
azd env set OPENAI_ORGANIZATION XX
azd env set OPENAI_API_KEY sk-XX
azd up
cd app
./start.sh

Then when accessing http://localhost:50505 and performing a search an error happens:

### Any log messages given by the failure
>
Error on the user interface:
Error: The app encountered an error processing your request.
If you are an administrator of the app, view the full error in the logs. See aka.ms/appservice-logs for more information.
Error type: <class 'azure.core.exceptions.HttpResponseError'>

Error on the console:
ERROR:root:Exception while generating response stream: () Authorization failed.
Code: 
Message: Authorization failed.
Traceback (most recent call last):
  File "/Users/amarppatel/workspace/saathratri-app-holder/hotelchatbot/app/backend/app.py", line 151, in format_as_ndjson
    async for event in r:
  File "/Users/amarppatel/workspace/saathratri-app-holder/hotelchatbot/app/backend/approaches/chatapproach.py", line 152, in run_with_streaming
    extra_info, chat_coroutine = await self.run_until_final_call(
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amarppatel/workspace/saathratri-app-holder/hotelchatbot/app/backend/approaches/chatreadretrieveread.py", line 152, in run_until_final_call
    results = await self.search(top, query_text, filter, vectors, use_semantic_ranker, use_semantic_captions)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amarppatel/workspace/saathratri-app-holder/hotelchatbot/app/backend/approaches/approach.py", line 136, in search
    async for page in results.by_page():
  File "/Users/amarppatel/workspace/saathratri-app-holder/hotelchatbot/app/backend/backend_env/lib/python3.11/site-packages/azure/core/async_paging.py", line 94, in __anext__
    self._response = await self._get_next(self.continuation_token)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amarppatel/workspace/saathratri-app-holder/hotelchatbot/app/backend/backend_env/lib/python3.11/site-packages/azure/search/documents/aio/_paging.py", line 108, in _get_next_cb
    return await self._client.documents.search_post(search_request=self._initial_query.request, **self._kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amarppatel/workspace/saathratri-app-holder/hotelchatbot/app/backend/backend_env/lib/python3.11/site-packages/azure/core/tracing/decorator_async.py", line 88, in wrapper_use_tracer
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amarppatel/workspace/saathratri-app-holder/hotelchatbot/app/backend/backend_env/lib/python3.11/site-packages/azure/search/documents/_generated/aio/operations/_documents_operations.py", line 417, in search_post
    raise HttpResponseError(response=response, model=error)
azure.core.exceptions.HttpResponseError: () Authorization failed.
Code: 
Message: Authorization failed.

### Expected/desired behavior
>
The search should show results on the user interface.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
macOS Darwin

### azd version?
> run `azd version` and copy paste here.
azd version 1.6.1 

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
@amarpatel-xx The "azd up" should have set up role-based access control for your local account to access the search service, but that doesn't seem to be working. Please go into portal.azure.com, open the search service, select "Access control", then "View my access". That should list all your roles. This is what I see:

![Screenshot 2024-02-21 at 12 19 47 PM](https://github.com/Azure-Samples/azure-search-openai-demo/assets/297042/04cc2767-6e0a-4d13-ad60-444e0ac887ef)

In particular, make sure you have the three search-related roles listed there, especially Search Index Data Reader. Do you see them?

**Comment by pamelafox** [comment]
Ah, I just saw your comment in other thread:

`azure.identity.aio._credentials.environment:Environment is configured for ClientSecretCredential`

Do you mean that you're using keys to access search service? Then you wouldn't see the roles I mentioned, and you'd need to check your keyvault instead.

**Comment by amarpatel-xx** [comment]
@pamelafox I did check the below resource and it does have the permissions like yours (please see screenshot below):
![Screenshot 2024-02-22 at 1 58 28 PM](https://github.com/Azure-Samples/azure-search-openai-demo/assets/1010740/2f9d48c7-b30a-45b3-bbb0-f6e81227be13)

I am not sure if I am using ClientSecretCredential or not, but I do get the below message when I run the following command:
$ ./start.sh

...
Starting backend

 * Serving Quart app 'app'
 * Debug mode: False
 * Please use an ASGI server (e.g. Hypercorn) directly in production
 * Running on http://localhost:50505 (CTRL + C to quit)
INFO:azure.identity.aio._credentials.environment:Environment is configured for ClientSecretCredential
INFO:azure.identity.aio._credentials.managed_identity:ManagedIdentityCredential will use IMDS
[2024-02-22 13:48:24 -0500] [22854] [INFO] Running on http://127.0.0.1:50505 (CTRL + C to quit)
INFO:hypercorn.error:Running on http://127.0.0.1:50505 (CTRL + C to quit)
...

**Comment by pamelafox** [comment]
Ahh interesting. I think there must be some environment variables that's making it choose to use ClientSecretCredential. We expect it to instead use AzureDeveloperCLICredential when running locally. You could either try clearing local environment variables, or change DefaultAzureCredential() in app.py to DefaultAzureCredential(exclude_environment_credential=True)
