### ISSUE TITLE
Update api version for azure-search-openai-demo

### ISSUE THREAD

**Issue by Taylor520180** [Azure-Samples/azure-search-openai-demo#1358]
Hi, I'm using the azure-search-openai-demo to deploy azure web app. Now I'm trying to update the api_version from the original api_version="2023-07-01-preview" to api_version="2023-12-01". But the web app returns error after I made the change. "openai.NotFoundError". When I checked the failure message on Application Insights, i saw the following message in details.
"Traceback (most recent call last):
  File "/tmp/8dc3a157ee5fa6d/app.py", line 158, in format_as_ndjson
    async for event in r:
  File "/tmp/8dc3a157ee5fa6d/approaches/chatapproach.py", line 144, in run_with_streaming
    extra_info, chat_coroutine = await self.run_until_final_call(
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/8dc3a157ee5fa6d/approaches/chatreadretrieveread.py", line 127, in run_until_final_call
    chat_completion: ChatCompletion = await self.openai_client.chat.completions.create(
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/8dc3a157ee5fa6d/antenv/lib/python3.11/site-packages/openai/resources/chat/completions.py", line 1199, in create
    return await self._post(
           ^^^^^^^^^^^^^^^^^
  File "/tmp/8dc3a157ee5fa6d/antenv/lib/python3.11/site-packages/openai/_base_client.py", line 1542, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/8dc3a157ee5fa6d/antenv/lib/python3.11/site-packages/openai/_base_client.py", line 1316, in request
    return await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/tmp/8dc3a157ee5fa6d/antenv/lib/python3.11/site-packages/openai/_base_client.py", line 1368, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}}"

Can anyone help me on this? I just need to know the correct way to update the api version.

**Comment by pamelafox** [comment]
I think it may be -preview, per https://learn.microsoft.com/en-us/azure/ai-services/openai/reference ?

**Comment by pamelafox** [comment]
We've now merged a PR that updates the version to the latest for everyone.
