### ISSUE TITLE
Need help deploying to locked-down Azure environment (w/ existing storage container)

### ISSUE THREAD

**Issue by DuboisABB** [Azure-Samples/azure-search-openai-demo#1361]
### This issue is for a: (mark with an `x`)
```
- [X] feature request
```

### Minimal steps to reproduce
Our company Azure instance does not allow Storage resources with public network access, so azd up fails. I would appreciate some help to get this to work. I wasn't sure how to modify the bicep files to change that (I had not seen #864) so I just commented out the creation of the storage in main.bicep and I created it manually in the portal instead (with private end points for all resources already created by previous azd up). 
I’m not clear on how to let the rest of the code base know that it should use the manually configured storage. Here are the steps that I took. 

I configured some variables as follows:
azd env set AZURE_STORAGE_ACCOUNT my_store_account
azd env set AZURE_STORAGE_CONTAINER my_store_container
azd env set AZURE_STORAGE_RESOURCE_GROUP my_resource_group

I then modified the main.parameters.json file to use these variables:
"storageAccountName": {
"value": "${AZURE_STORAGE_ACCOUNT}"
},
"storageResourceGroupName": {
"value": "${AZURE_STORAGE_RESOURCE_GROUP}"
},

I also modified the main.bicep file as follows:
param storageAccountName string = 'my_store_account'
param storageResourceGroupName string = 'my_resource_group'
param storageResourceGroupLocation string = 'westeurope'
param storageContainerName string = 'my_store_container'

Then I ran azd deploy and it deployed without errors but the web app doesn't work.

### Any log messages given by the failure
No errors in the deployment logs or Oryx logs. However, I see this in the Kudu default_docker.log from the log zip file:
2024-03-02T19:17:14.974662623Z [2024-03-02 19:17:14 +0000] [71] [INFO] Starting gunicorn 20.1.0
2024-03-02T19:17:14.982591938Z [2024-03-02 19:17:14 +0000] [71] [INFO] Listening at: http://0.0.0.0:8000 (71)
2024-03-02T19:17:14.983778070Z [2024-03-02 19:17:14 +0000] [71] [INFO] Using worker: uvicorn.workers.UvicornWorker
2024-03-02T19:17:15.011561322Z [2024-03-02 19:17:15 +0000] [72] [INFO] Booting worker with pid: 72
2024-03-02T19:17:15.094723475Z [2024-03-02 19:17:15 +0000] [73] [INFO] Booting worker with pid: 73
2024-03-02T19:17:15.252585252Z [2024-03-02 19:17:15 +0000] [74] [INFO] Booting worker with pid: 74
2024-03-02T19:18:09.390304927Z [2024-03-02 19:18:09 +0000] [74] [INFO] Started server process [74]
2024-03-02T19:18:09.400449360Z [2024-03-02 19:18:09 +0000] [74] [INFO] Waiting for application startup.
2024-03-02T19:18:09.400464060Z [2024-03-02 19:18:09 +0000] [73] [INFO] Started server process [73]
2024-03-02T19:18:09.401761790Z [2024-03-02 19:18:09 +0000] [73] [INFO] Waiting for application startup.
2024-03-02T19:18:09.418866083Z [2024-03-02 19:18:09 +0000] [72] [INFO] Started server process [72]
2024-03-02T19:18:09.419313293Z [2024-03-02 19:18:09 +0000] [72] [INFO] Waiting for application startup.
2024-03-02T19:18:09.438882442Z [2024-03-02 19:18:09 +0000] [74] [ERROR] 'AZURE_STORAGE_ACCOUNT'
2024-03-02T19:18:09.440569281Z [2024-03-02 19:18:09 +0000] [73] [ERROR] 'AZURE_STORAGE_ACCOUNT'
2024-03-02T19:18:09.440585382Z [2024-03-02 19:18:09 +0000] [72] [ERROR] 'AZURE_STORAGE_ACCOUNT'
2024-03-02T19:18:09.458112984Z [2024-03-02 19:18:09 +0000] [73] [ERROR] Application startup failed. Exiting.
2024-03-02T19:18:09.475260778Z [2024-03-02 19:18:09 +0000] [74] [ERROR] Application startup failed. Exiting.
2024-03-02T19:18:09.532576194Z [2024-03-02 19:18:09 +0000] [74] [INFO] Worker exiting (pid: 74)
2024-03-02T19:18:09.532598694Z [2024-03-02 19:18:09 +0000] [72] [ERROR] Application startup failed. Exiting.
2024-03-02T19:18:09.532605394Z [2024-03-02 19:18:09 +0000] [73] [INFO] Worker exiting (pid: 73)
2024-03-02T19:18:09.532618095Z [2024-03-02 19:18:09 +0000] [72] [INFO] Worker exiting (pid: 72)

I also see a bunch of KeyError in Application Insight.

### Expected/desired behavior
I'd like the app to run with manually configured storage and network set up with private end points. I have loaded 25 GB of documents in the storage container already so I'd highly prefer not to start over with a fresh storage, especially given that this app is part of a hackathon happening this week and time is short.

### OS and Version?
Windows 11

### azd version?
azd version 1.6.1 (commit eba2c978b5443fdb002c95add4011d9e63c2e76f)

### Versions
Repo cloned on 2024-02-28

**Comment by pamelafox** [comment]
Can you check what environment variables the bicep is setting for the web app? In main, it looks like:

    appSettings: {
      AZURE_STORAGE_ACCOUNT: storage.outputs.name
      AZURE_STORAGE_CONTAINER: storageContainerName

You'll need to make sure those reflect your parameters.

**Comment by DuboisABB** [comment]
Nice find, thanks. I had commented out those parameters temporarily, when I was just aiming to disable storage creation and get the deployment to succeed, without thinking too far ahead. I had forgotten to reenable them. I just did but unfortunately, I got the same error in the default_docker log.

Does the main.bicep file get used when just doing azd deploy? I guess not. I didn't really want to do azd up because if I remember correctly, it wiped all the custom settings I had done for my resources last time I did (mainly private endpoint and IP whitelisting).

So instead, I went into the app settings in the portal and I saw that both settings were missing. I added them manually and tried azd deploy again. This time I don't get the error about AZURE_STORAGE_ACCOUNT but I get this kind of log:

```
2024-03-03T02:49:51.312280297Z Python 3.11.4
2024-03-03T02:49:51.312284597Z Note: Any data outside '/home' is not persisted
2024-03-03T02:49:58.228600019Z Starting OpenBSD Secure Shell server: sshd.
2024-03-03T02:49:58.837781462Z Site's appCommandLine: python3 -m gunicorn main:app
2024-03-03T02:49:58.857041169Z Launching oryx with: create-script -appPath /home/site/wwwroot -output /opt/startup/startup.sh -virtualEnvName antenv -defaultApp /opt/defaultsite -userStartupCommand 'python3 -m gunicorn main:app'
2024-03-03T02:49:59.842214626Z Could not find build manifest file at '/home/site/wwwroot/oryx-manifest.toml'
2024-03-03T02:49:59.842272829Z Could not find operation ID in manifest. Generating an operation id...
2024-03-03T02:49:59.842279430Z Build Operation ID: 55e13089-3c9d-4708-bb02-567f8fdbfd0f
2024-03-03T02:50:02.787261678Z Oryx Version: 0.2.20230707.1, Commit: 0bd28e69919b5e8beba451e8677e3345f0be8361, ReleaseTagName: 20230707.1
2024-03-03T02:50:02.797821128Z Writing output script to '/opt/startup/startup.sh'
2024-03-03T02:50:02.797844929Z WARNING: Could not find virtual environment directory /home/site/wwwroot/antenv.
2024-03-03T02:50:02.797851130Z WARNING: Could not find package directory /home/site/wwwroot/__oryx_packages__.
2024-03-03T02:50:09.213248740Z [2024-03-03 02:50:09 +0000] [67] [INFO] Starting gunicorn 20.1.0
2024-03-03T02:50:09.248976785Z [2024-03-03 02:50:09 +0000] [67] [INFO] Listening at: http://0.0.0.0:8000 (67)
2024-03-03T02:50:09.250564467Z [2024-03-03 02:50:09 +0000] [67] [INFO] Using worker: sync
2024-03-03T02:50:09.357195872Z [2024-03-03 02:50:09 +0000] [70] [INFO] Booting worker with pid: 70
2024-03-03T02:50:09.448036362Z [2024-03-03 02:50:09 +0000] [70] [ERROR] Exception in worker process
2024-03-03T02:50:09.448092565Z Traceback (most recent call last):
2024-03-03T02:50:09.448099465Z   File "/opt/python/3/lib/python3.11/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
2024-03-03T02:50:09.448104666Z     worker.init_process()
2024-03-03T02:50:09.448109166Z   File "/opt/python/3/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
2024-03-03T02:50:09.448113866Z     self.load_wsgi()
2024-03-03T02:50:09.448118166Z   File "/opt/python/3/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
2024-03-03T02:50:09.448139567Z     self.wsgi = self.app.wsgi()
2024-03-03T02:50:09.448144468Z                 ^^^^^^^^^^^^^^^
2024-03-03T02:50:09.448148768Z   File "/opt/python/3/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
2024-03-03T02:50:09.448153268Z     self.callable = self.load()
2024-03-03T02:50:09.448157568Z                     ^^^^^^^^^^^
2024-03-03T02:50:09.448161869Z   File "/opt/python/3/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
2024-03-03T02:50:09.448166169Z     return self.load_wsgiapp()
2024-03-03T02:50:09.448170569Z            ^^^^^^^^^^^^^^^^^^^
2024-03-03T02:50:09.448174669Z   File "/opt/python/3/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
2024-03-03T02:50:09.448179170Z     return util.import_app(self.app_uri)
2024-03-03T02:50:09.448183470Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-03T02:50:09.448187870Z   File "/opt/python/3/lib/python3.11/site-packages/gunicorn/util.py", line 359, in import_app
2024-03-03T02:50:09.448192370Z     mod = importlib.import_module(module)
2024-03-03T02:50:09.448196670Z           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-03T02:50:09.448200971Z   File "/opt/python/3/lib/python3.11/importlib/__init__.py", line 126, in import_module
2024-03-03T02:50:09.448205371Z     return _bootstrap._gcd_import(name[level:], package, level)
2024-03-03T02:50:09.448209571Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-03T02:50:09.448213771Z   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
2024-03-03T02:50:09.448218572Z   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
2024-03-03T02:50:09.448223072Z   File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
2024-03-03T02:50:09.448227572Z ModuleNotFoundError: No module named 'main'
2024-03-03T02:50:09.525554964Z [2024-03-03 02:50:09 +0000] [70] [INFO] Worker exiting (pid: 70)
2024-03-03T02:50:10.065215525Z [2024-03-03 02:50:10 +0000] [67] [INFO] Shutting down: Master
2024-03-03T02:50:10.065698850Z [2024-03-03 02:50:10 +0000] [67] [INFO] Reason: Worker failed to boot.
```
Not sure how to troubleshoot this.

**Comment by DuboisABB** [comment]
I managed to make it work. I changed too many things mostly in the portal to be able to really summarize what really worked.
