### ISSUE TITLE
Error in environments with existing integrated vectorization enabled

### ISSUE THREAD

**Issue by pamelafox** [Azure-Samples/azure-search-openai-demo#1408]
This error happens when you re-run prepdocs.sh:

``
Traceback (most recent call last):
  File "/workspaces/azure-search-openai-demo/./scripts/prepdocs.py", line 483, in <module>
    loop.run_until_complete(main(ingestion_strategy, setup_index=not args.remove and not args.removeall))
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/workspaces/azure-search-openai-demo/./scripts/prepdocs.py", line 221, in main
    await strategy.setup()
  File "/workspaces/azure-search-openai-demo/scripts/prepdocslib/integratedvectorizerstrategy.py", line 159, in setup
    await ds_client.create_or_update_data_source_connection(data_source_connection)
  File "/workspaces/azure-search-openai-demo/scripts/.venv/lib/python3.11/site-packages/azure/core/tracing/decorator_async.py", line 77, in wrapper_use_tracer
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/azure-search-openai-demo/scripts/.venv/lib/python3.11/site-packages/azure/search/documents/indexes/aio/_search_indexer_client.py", line 367, in create_or_update_data_source_connection
    result = await self._client.data_sources.create_or_update(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/azure-search-openai-demo/scripts/.venv/lib/python3.11/site-packages/azure/core/tracing/decorator_async.py", line 77, in wrapper_use_tracer
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/azure-search-openai-demo/scripts/.venv/lib/python3.11/site-packages/azure/search/documents/indexes/_generated/aio/operations/_data_sources_operations.py", line 248, in create_or_update
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/workspaces/azure-search-openai-demo/scripts/.venv/lib/python3.11/site-packages/azure/core/exceptions.py", line 164, in map_error
    raise error
azure.core.exceptions.ResourceExistsError: () There was a conflicting update. No change was made to the resource from this request.
```

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce

Create an environment with integrated vectorization enabled
Re-run prepdocs.sh

**Comment by DuboisABB** [comment]
I'm also getting this error. Any tips for a workaround?

**Comment by pamelafox** [comment]
I typically just comment out those last few lines of code. I've asked @srbalakr to take a look, however.

**Comment by egor-yudkin** [comment]
Getting the same issue... @pamelafox which lines exactly do you comment out?

**Comment by Lawndemon** [comment]
would love an update on this one if possible

**Comment by srbalakr** [comment]
Sorry folks, I wasn't available in past months . Will take a look and keep posted.

**Comment by egor-yudkin** [comment]
I'd really like to switch my application to using embedded vectorization, but the only workaround for this issue I found is to delete the index, which is not a good option for live application.
@pamelafox - could you elaborate on your workaround please? I cannot figure out what lines to comment out.

**Comment by ShreyankaWebasto** [comment]
Hi @pamelafox  I would also like an update on this one

**Comment by pamelafox** [comment]
@ShreyankaWebasto You're getting exactly this error still?

```
azure.core.exceptions.ResourceExistsError: () There was a conflicting update. No change was made to the resource from this request.
```

Do you have the latest version of the code?

**Comment by pamelafox** [comment]
I am closing this issue since we are deprecating the previous integrated vectorization feature.

We have made a custom skillset that runs our own code instead, mirroring the local ingestion in Azure Functions. We recommend the new skillset approach for maximal compatibility with the repo features. 

Please try it out and raise any issues you run into. Thanks!
https://github.com/Azure-Samples/azure-search-openai-demo/releases/tag/2025-11-12
