### ISSUE TITLE
TypeError: "type" object is not subscriptable

### ISSUE THREAD

**Issue by smallbirds2** [Azure-Samples/azure-search-openai-demo#142]
Hey, I was trying to run this code locally. Using the the "./start.sh" script. It fails in deploying the backend script. I tried different versions of python, but I am facing the same issue.

Starting backend

Traceback (most recent call last):
  File "./app.py", line 12, in <module>
    from approaches.chatreadretrieveread import ChatReadRetrieveReadApproach
  File "/home/peter/azure-demo/azure-search-openai-demo/app/backend/approaches/chatreadretrieveread.py", line 10, in <module>
    class ChatReadRetrieveReadApproach(Approach):
  File "/home/peter/azure-demo/azure-search-openai-demo/app/backend/approaches/chatreadretrieveread.py", line 51, in ChatReadRetrieveReadApproach
    def run(self, history: list[dict], overrides: dict) -> any:
TypeError: 'type' object is not subscriptable
Failed to start backend

**Comment by scovin1109** [comment]
My python version is 3.8.8

I need to import " from typing import List,Dict,Any"

and rewrite "def run(self, history: List[Dict], overrides: Dict) -> Any:"

then It is work

**Comment by pamelafox** [comment]
We've decided to only support 3.9+, closing.
