### ISSUE TITLE
hit prepdocs.sh failed with xlsx filetype.

### ISSUE THREAD

**Issue by christ25442544** [Azure-Samples/azure-search-openai-demo#1457]
IF SUFFICIENT INFORMATION IS NOT PROVIDED VIA THE FOLLOWING TEMPLATE THE ISSUE MIGHT BE CLOSED WITHOUT FURTHER CONSIDERATION OR INVESTIGATION
-->
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Hello guys. I've tried to hit prepdocs.sh with xlsx file and it shows internal server error. Have you guys ever encountered any problem like this? 

### Any log messages given by the failure
>Unable to retrieve continuation token: cannot pickle '_io.BufferedReader' object
Traceback (most recent call last):
  File "/Users/teetatkaruhawanit/Documents/HD/json_utf_newver_chatbot/scripts/.venv/lib/python3.11/site-packages/azure/core/polling/async_base_polling.py", line 89, in run
    await self._poll()
  File "/Users/teetatkaruhawanit/Documents/HD/json_utf_newver_chatbot/scripts/.venv/lib/python3.11/site-packages/azure/core/polling/async_base_polling.py", line 121, in _poll
    raise OperationFailed("Operation failed or canceled")
azure.core.polling.base_polling.OperationFailed: Operation failed or canceled

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/teetatkaruhawanit/Documents/HD/json_utf_newver_chatbot/./scripts/prepdocs.py", line 483, in <module>
    loop.run_until_complete(main(ingestion_strategy, setup_index=not args.remove and not args.removeall))
  File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/teetatkaruhawanit/Documents/HD/json_utf_newver_chatbot/./scripts/prepdocs.py", line 222, in main
    await strategy.run()
  File "/Users/teetatkaruhawanit/Documents/HD/json_utf_newver_chatbot/scripts/prepdocslib/filestrategy.py", line 84, in run
    sections = await parse_file(file, self.file_processors, self.category, self.image_embeddings)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/teetatkaruhawanit/Documents/HD/json_utf_newver_chatbot/scripts/prepdocslib/filestrategy.py", line 26, in parse_file
    pages = [page async for page in processor.parser.parse(content=file.content)]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/teetatkaruhawanit/Documents/HD/json_utf_newver_chatbot/scripts/prepdocslib/filestrategy.py", line 26, in <listcomp>
    pages = [page async for page in processor.parser.parse(content=file.content)]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/teetatkaruhawanit/Documents/HD/json_utf_newver_chatbot/scripts/prepdocslib/pdfparser.py", line 57, in parse
    form_recognizer_results = await poller.result()
                              ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/teetatkaruhawanit/Documents/HD/json_utf_newver_chatbot/scripts/.venv/lib/python3.11/site-packages/azure/core/polling/_async_poller.py", line 179, in result
    await self.wait()
  File "/Users/teetatkaruhawanit/Documents/HD/json_utf_newver_chatbot/scripts/.venv/lib/python3.11/site-packages/azure/core/polling/_async_poller.py", line 191, in wait
    await self._polling_method.run()
  File "/Users/teetatkaruhawanit/Documents/HD/json_utf_newver_chatbot/scripts/.venv/lib/python3.11/site-packages/azure/core/polling/async_base_polling.py", line 104, in run
    raise HttpResponseError(response=self._pipeline_response.http_response, error=err) from err
azure.core.exceptions.HttpResponseError: (InternalServerError) An unexpected error occurred.
Code: InternalServerError
Message: An unexpected error occurred.
Exception Details:      (InternalServerError) An unexpected error occurred.
        Code: InternalServerError
        Message: An unexpected error occurred.
        Target: 0

### Expected/desired behavior
> It should be readable because document intelligence already support xlsx file.

### OS and Version?
> macOS Sonoma)

### azd version?
> azd version 1.7.0

### Mention any other details that might be useful
This is my dataframe information
<img width="494" alt="Screenshot 2567-03-25 at 14 03 55" src="https://github.com/Azure-Samples/azure-search-openai-demo/assets/124753618/66f7f140-955a-49ec-8fba-e4bb438d4fda">
<img width="1512" alt="Screenshot 2567-03-25 at 14 03 46" src="https://github.com/Azure-Samples/azure-search-openai-demo/assets/124753618/164b48d8-778e-412f-be40-19b0fa4698b1">
<!--
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
How large is your file? This might be a similar issue to https://github.com/Azure-Samples/azure-search-openai-demo/issues/485 or it might be a different issue.

**Comment by christ25442544** [comment]
my each individual file of xlsx is only about 1.3-1.5 MB approximately. 
This is how I exported xlsx file.
<img width="406" alt="Screenshot 2567-03-27 at 10 48 51" src="https://github.com/Azure-Samples/azure-search-openai-demo/assets/124753618/f6ceb8fe-b688-413d-b3c7-5ca1ae865815">
