### ISSUE TITLE
 gptkbindex not created during deployment (Auth failed)

### ISSUE THREAD

**Issue by javier-menendez-hitachi** [Azure-Samples/azure-search-openai-demo#158]
> Please provide us with the following information:
> ---------------------------------------------------------------
When I run the azd up command, just before azd deploy is executed I get this error:
`Running "prepdocs.py" Ensuring search index gptkbindex exists Traceback (most recent call last): File "C:\projects\azseopai-demo\scripts\prepdocs.py", line 299, in <module> create_search_index() File "C:\projects\azseopai-demo\scripts\prepdocs.py", line 237, in create_search_index if args.index not in index_client.list_index_names(): ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\projects\azseopai-demo\scripts\.venv\Lib\site-packages\azure\core\paging.py", line 124, in __next__ return next(self._page_iterator) ^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\projects\azseopai-demo\scripts\.venv\Lib\site-packages\azure\core\paging.py", line 76, in __next__ self._response = self._get_next(self.continuation_token) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\projects\azseopai-demo\scripts\.venv\Lib\site-packages\azure\search\documents\indexes\_generated\operations\_indexes_operations.py", line 520, in get_next raise HttpResponseError(response=response, model=error) azure.core.exceptions.HttpResponseError: () Authorization failed. Code: Message: Authorization failed.`

The App is deployed and running, but when I try to use it I always get:
`Error: () The index 'gptkbindex' for service 'gptkb-yueykj4gtm65m' was not found.`

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
Run `azd up` command

### Any log messages given by the failure
>
`Running "prepdocs.py" Ensuring search index gptkbindex exists Traceback (most recent call last): File "C:\projects\azseopai-demo\scripts\prepdocs.py", line 299, in <module> create_search_index() File "C:\projects\azseopai-demo\scripts\prepdocs.py", line 237, in create_search_index if args.index not in index_client.list_index_names(): ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\projects\azseopai-demo\scripts\.venv\Lib\site-packages\azure\core\paging.py", line 124, in __next__ return next(self._page_iterator) ^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\projects\azseopai-demo\scripts\.venv\Lib\site-packages\azure\core\paging.py", line 76, in __next__ self._response = self._get_next(self.continuation_token) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\projects\azseopai-demo\scripts\.venv\Lib\site-packages\azure\search\documents\indexes\_generated\operations\_indexes_operations.py", line 520, in get_next raise HttpResponseError(response=response, model=error) azure.core.exceptions.HttpResponseError: () Authorization failed. Code: Message: Authorization failed.`
### Expected/desired behavior
> Index creation and App working

### OS and Version?
> Microsoft Windows 10 Enterprise

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by javier-menendez-hitachi** [comment]
Find solution :) https://github.com/Azure-Samples/azure-search-openai-demo/issues/79
