### ISSUE TITLE
Can we get some examples for AZURE_ADLS_GEN2_FILESYSTEM_PATH and how to use it in documentation please

### ISSUE THREAD

**Issue by adp-douglaswross** [Azure-Samples/azure-search-openai-demo#1596]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

1. Trying to setup acls with gen2 storage, and struggling to get azd up to run without failure.
2. Requesting that there are some specific examples of what AZURE_ADLS_GEN2_FILESYSTEM_PATH should look like. Should it be "https://something.blob.core.windows.net/gptkbcontainer/" or not / or /* or am I completely missing the point? Sorry, I have tried a few and sort of punching in the dark now.
3. Also do not understand why prepdocs is looking for the old index gptkbindex and not the new gen2 index gptkbcontainer
4. Am I missing a step where I need to remove all the old index in the old storage before I can use the new gen2 storage. Sorry I little bit lost on where to go to understand how to correctly setup gen2 storage. Sorry if it is obvious as well.

### Any log messages given by the failure
>

running azd up ....

  (-) Skipped: Didn't find new changes.
Loading azd .env file from current environment...
Creating Python virtual environment "app/backend/.venv"...
Installing dependencies from "requirements.txt" into virtual environment (in quiet mode)...
Updating redirect URIs for client app ID 72821f3c-7d06-4dba-84ec-5692490d8d46...
Application update for client app id 72821f3c-7d06-4dba-84ec-5692490d8d46 complete.
Loading azd .env file from current environment...
Creating Python virtual environment "app/backend/.venv"...
Installing dependencies from "requirements.txt" into virtual environment (in quiet mode)...
Running "prepdocs.py"
Using Data Lake Gen2 Storage Account: stradpglobal
Ensuring search index gptkbindex exists
Search index gptkbindex already exists
Traceback (most recent call last):
  File "/Users/douglasross/Documents/Apps/github/com.adaptovategpt.au/./app/backend/prepdocs.py", line 494, in <module>
    loop.run_until_complete(main(ingestion_strategy, setup_index=not args.remove and not args.removeall))
  File "/opt/homebrew/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/douglasross/Documents/Apps/github/com.adaptovategpt.au/./app/backend/prepdocs.py", line 225, in main
    await strategy.run()
  File "/Users/douglasross/Documents/Apps/github/com.adaptovategpt.au/app/backend/prepdocslib/filestrategy.py", line 82, in run
    async for file in files:
  File "/Users/douglasross/Documents/Apps/github/com.adaptovategpt.au/app/backend/prepdocslib/listfilestrategy.py", line 144, in list
    async for path in self.list_paths():
  File "/Users/douglasross/Documents/Apps/github/com.adaptovategpt.au/app/backend/prepdocslib/listfilestrategy.py", line 134, in list_paths
    async for path in filesystem_client.get_paths(path=self.data_lake_path, recursive=True):
  File "/Users/douglasross/Documents/Apps/github/com.adaptovategpt.au/.venv/lib/python3.11/site-packages/azure/core/async_paging.py", line 142, in __anext__
    return await self.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/douglasross/Documents/Apps/github/com.adaptovategpt.au/.venv/lib/python3.11/site-packages/azure/core/async_paging.py", line 145, in __anext__
    self._page = await self._page_iterator.__anext__()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/douglasross/Documents/Apps/github/com.adaptovategpt.au/.venv/lib/python3.11/site-packages/azure/core/async_paging.py", line 94, in __anext__
    self._response = await self._get_next(self.continuation_token)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/douglasross/Documents/Apps/github/com.adaptovategpt.au/.venv/lib/python3.11/site-packages/azure/storage/filedatalake/aio/_list_paths_helper.py", line 162, in _get_next_cb
    process_storage_error(error)
  File "/Users/douglasross/Documents/Apps/github/com.adaptovategpt.au/.venv/lib/python3.11/site-packages/azure/storage/filedatalake/_deserialize.py", line 221, in process_storage_error
    exec("raise error from None")   # pylint: disable=exec-used # nosec
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
  File "/Users/douglasross/Documents/Apps/github/com.adaptovategpt.au/.venv/lib/python3.11/site-packages/azure/storage/filedatalake/aio/_list_paths_helper.py", line 154, in _get_next_cb
    return await self._command(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/douglasross/Documents/Apps/github/com.adaptovategpt.au/.venv/lib/python3.11/site-packages/azure/core/tracing/decorator_async.py", line 77, in wrapper_use_tracer
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/douglasross/Documents/Apps/github/com.adaptovategpt.au/.venv/lib/python3.11/site-packages/azure/storage/filedatalake/_generated/aio/operations/_file_system_operations.py", line 512, in list_paths
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/Users/douglasross/Documents/Apps/github/com.adaptovategpt.au/.venv/lib/python3.11/site-packages/azure/core/exceptions.py", line 164, in map_error
    raise error
azure.core.exceptions.ResourceNotFoundError: The specified path does not exist.
RequestId:5e577784-101f-0000-5871-a00c90000000
Time:2024-05-07T11:28:17.3814454Z
ErrorCode:PathNotFound

ERROR: failed running post hooks: 'postprovision' hook failed with exit code: '1', Path: '/var/folders/0l/3qv4b5j962sg3xbqlkr642vc0000gn/T/azd-postprovision-366134142.sh'. : exit code: 1

ERROR: error executing step command 'provision': failed running post hooks: 'postprovision' hook failed with exit code: '1', Path: '/var/folders/0l/3qv4b5j962sg3xbqlkr642vc0000gn/T/azd-postprovision-366134142.sh'. : exit code: 1

### Expected/desired behavior
>
azd up to finish without error

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Latest macosx

### azd version?
> run `azd version` and copy paste here.
Latest 1.8.2

### Versions
>
Latest from Main branch

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
@mattgotteiner Can you share your example environment setup? I haven't yet setup an environment using ADLS2 for ingestion.

**Comment by adp-douglaswross** [comment]
Hi, have tried the following as well using what I get from Gen2 storage:

AZURE_ADLS_GEN2_FILESYSTEM_PATH="abfss://gptkbcontainer@<storage_name>.dfs.core.windows.net/"

gptkbcontainer is what the code creates I believe and <storage_name> is the name of my Gen2 storage set up with Hierarchies.

Sorry still struggling...

Doug

**Comment by adp-douglaswross** [comment]
@mattgotteiner:  Most recent errors in azd up with Gen2 storage setup. Based on the code, I think that my filesystem path is completely wrong... or maybe something else? Thanks in advance for any help, examples etc. of the format of the path and anything else.

Gen 2 environment variables being used:

AZURE_ADLS_GEN2_FILESYSTEM="gptkbcontainer"
AZURE_ADLS_GEN2_FILESYSTEM_PATH="abfss://gptkbcontainer@<xxxxxxx>.dfs.core.windows.net/"
AZURE_ADLS_GEN2_STORAGE_ACCOUNT="<xxxxxx>"

ERROR running azd up:

Provisioning Azure resources (azd provision)
Provisioning Azure resources can take some time.

Subscription: xxxxxxxx
Location: xxxxxxxx

  (-) Skipped: Didn't find new changes.
Loading azd .env file from current environment...
Creating Python virtual environment "app/backend/.venv"...
Installing dependencies from "requirements.txt" into virtual environment (in quiet mode)...
Updating redirect URIs for client app ID xxxxxxxxxx...
Application update for client app id xxxxxxxxx complete.
Loading azd .env file from current environment...
Creating Python virtual environment "app/backend/.venv"...
Installing dependencies from "requirements.txt" into virtual environment (in quiet mode)...
Running "prepdocs.py"
Using Data Lake Gen2 Storage Account: <xxxxxxxx>
Ensuring search index gptkbindex exists
Search index gptkbindex already exists
Traceback (most recent call last):
  File "/Users/douglasross/Documents/Apps/github/com.adaptovate.ai/./app/backend/prepdocs.py", line 494, in <module>
    loop.run_until_complete(main(ingestion_strategy, setup_index=not args.remove and not args.removeall))
  File "/opt/homebrew/Cellar/python@3.11/3.11.9/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/douglasross/Documents/Apps/github/com.adaptovate.ai/./app/backend/prepdocs.py", line 225, in main
    await strategy.run()
  File "/Users/douglasross/Documents/Apps/github/com.adaptovate.ai/app/backend/prepdocslib/filestrategy.py", line 82, in run
    async for file in files:
  File "/Users/douglasross/Documents/Apps/github/com.adaptovate.ai/app/backend/prepdocslib/listfilestrategy.py", line 145, in list
    async for path in self.list_paths():
  File "/Users/douglasross/Documents/Apps/github/com.adaptovate.ai/app/backend/prepdocslib/listfilestrategy.py", line 135, in list_paths
    async for path in filesystem_client.get_paths(path=self.data_lake_path, recursive=True):
  File "/Users/douglasross/Documents/Apps/github/com.adaptovate.ai/.venv/lib/python3.11/site-packages/azure/core/async_paging.py", line 142, in __anext__
    return await self.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/douglasross/Documents/Apps/github/com.adaptovate.ai/.venv/lib/python3.11/site-packages/azure/core/async_paging.py", line 145, in __anext__
    self._page = await self._page_iterator.__anext__()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/douglasross/Documents/Apps/github/com.adaptovate.ai/.venv/lib/python3.11/site-packages/azure/core/async_paging.py", line 94, in __anext__
    self._response = await self._get_next(self.continuation_token)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/douglasross/Documents/Apps/github/com.adaptovate.ai/.venv/lib/python3.11/site-packages/azure/storage/filedatalake/aio/_list_paths_helper.py", line 162, in _get_next_cb
    process_storage_error(error)
  File "/Users/douglasross/Documents/Apps/github/com.adaptovate.ai/.venv/lib/python3.11/site-packages/azure/storage/filedatalake/_deserialize.py", line 221, in process_storage_error
    exec("raise error from None")   # pylint: disable=exec-used # nosec
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
  File "/Users/douglasross/Documents/Apps/github/com.adaptovate.ai/.venv/lib/python3.11/site-packages/azure/storage/filedatalake/aio/_list_paths_helper.py", line 154, in _get_next_cb
    return await self._command(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/douglasross/Documents/Apps/github/com.adaptovate.ai/.venv/lib/python3.11/site-packages/azure/core/tracing/decorator_async.py", line 77, in wrapper_use_tracer
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/douglasross/Documents/Apps/github/com.adaptovate.ai/.venv/lib/python3.11/site-packages/azure/storage/filedatalake/_generated/aio/operations/_file_system_operations.py", line 512, in list_paths
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/Users/douglasross/Documents/Apps/github/com.adaptovate.ai/.venv/lib/python3.11/site-packages/azure/core/exceptions.py", line 164, in map_error
    raise error
azure.core.exceptions.ResourceNotFoundError: The specified path does not exist.
RequestId:xxxxxxxxx
Time:2024-05-09T23:31:50.3695368Z
ErrorCode:PathNotFound

ERROR: error executing step command 'provision': failed running post hooks: 'postprovision' hook failed with exit code: '1', Path: '/var/folders/0l/xxxxxxxxxx/T/azd-postprovision-3648054177.sh'. : exit code: 1

**Comment by adp-douglaswross** [comment]
Worked out simply that AZURE_ADLS_GEN2_FILESYSTEM_PATH="/"

**Comment by christ25442544** [comment]
Can you share the process with me how to change from the old blob storage to data lake gen 2? I need to implement that to run it as a production. Thanks! :)

**Comment by dulalbert** [comment]
> Can you share the process with me how to change from the old blob storage to data lake gen 2? I need to implement that to run it as a production. Thanks! :)

You go to your storage account, then Data protection, then turn off "Enable soft delete for blobs". You go after to "Data Lake Gen2 upgrade" still in your container and you do the 3 steps.
