### ISSUE TITLE
New Deployment Failed

### ISSUE THREAD

**Issue by mirojs** [Azure-Samples/azure-search-openai-demo#1624]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
git clone
azd up

### Any log messages given by the failure
>

2024-05-16T13:51:50.898060210Z Writing output script to '/opt/startup/startup.sh'
2024-05-16T13:51:51.016543144Z WARNING: Could not find virtual environment directory /home/site/wwwroot/antenv.
2024-05-16T13:51:51.016580045Z WARNING: Could not find package directory /home/site/wwwroot/__oryx_packages__.
2024-05-16T13:51:52.405061416Z [2024-05-16 13:51:52 +0000] [54] [INFO] Starting gunicorn 21.2.0
2024-05-16T13:51:52.405893042Z [2024-05-16 13:51:52 +0000] [54] [INFO] Listening at: http://0.0.0.0:8000 (54)
2024-05-16T13:51:52.433453512Z [2024-05-16 13:51:52 +0000] [54] [INFO] Using worker: sync
2024-05-16T13:51:52.436088395Z [2024-05-16 13:51:52 +0000] [61] [INFO] Booting worker with pid: 61
2024-05-16T13:51:52.524627086Z [2024-05-16 13:51:52 +0000] [61] [ERROR] Exception in worker process
2024-05-16T13:51:52.524683288Z Traceback (most recent call last):
2024-05-16T13:51:52.524688488Z   File "/opt/python/3/lib/python3.11/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
2024-05-16T13:51:52.524692289Z     worker.init_process()
2024-05-16T13:51:52.524695289Z   File "/opt/python/3/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
2024-05-16T13:51:52.524699089Z     self.load_wsgi()
2024-05-16T13:51:52.524702089Z   File "/opt/python/3/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
2024-05-16T13:51:52.524716689Z     self.wsgi = self.app.wsgi()
2024-05-16T13:51:52.524719889Z                 ^^^^^^^^^^^^^^^
2024-05-16T13:51:52.524722789Z   File "/opt/python/3/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
2024-05-16T13:51:52.524732190Z     self.callable = self.load()
2024-05-16T13:51:52.524735390Z                     ^^^^^^^^^^^
2024-05-16T13:51:52.524738490Z   File "/opt/python/3/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
2024-05-16T13:51:52.524741690Z     return self.load_wsgiapp()
2024-05-16T13:51:52.524744590Z            ^^^^^^^^^^^^^^^^^^^
2024-05-16T13:51:52.524747590Z   File "/opt/python/3/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
2024-05-16T13:51:52.524750590Z     return util.import_app(self.app_uri)
2024-05-16T13:51:52.524753690Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-16T13:51:52.524756791Z   File "/opt/python/3/lib/python3.11/site-packages/gunicorn/util.py", line 371, in import_app
2024-05-16T13:51:52.524760091Z     mod = importlib.import_module(module)
2024-05-16T13:51:52.524763191Z           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-16T13:51:52.524766191Z   File "/opt/python/3/lib/python3.11/importlib/__init__.py", line 126, in import_module
2024-05-16T13:51:52.524769291Z     return _bootstrap._gcd_import(name[level:], package, level)
2024-05-16T13:51:52.524772291Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-16T13:51:52.524775191Z   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
2024-05-16T13:51:52.524778691Z   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
2024-05-16T13:51:52.524781991Z   File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
2024-05-16T13:51:52.524785291Z ModuleNotFoundError: No module named 'main'
2024-05-16T13:51:52.525492614Z [2024-05-16 13:51:52 +0000] [61] [INFO] Worker exiting (pid: 61)
2024-05-16T13:51:52.987981797Z [2024-05-16 13:51:52 +0000] [54] [ERROR] Worker (pid:61) exited with code 3
2024-05-16T13:51:52.996905679Z [2024-05-16 13:51:52 +0000] [54] [ERROR] Shutting down: Master
2024-05-16T13:51:52.998807239Z [2024-05-16 13:51:52 +0000] [54] [ERROR] Reason: Worker failed to boot.

### Expected/desired behavior
>
Full Deployment.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Linux (Ubuntu)

### azd version?
> run `azd version` and copy paste here.
Updated to 1.9.2
### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by mirojs** [comment]
It's back with the most recent update. Thanks.

**Comment by mirojs** [comment]
Could be. I run into an issue from the existing employment following the github update and tried to make a fresh new one to figure out the source of error. The new one did failed, which was also confirmed by the log. So I didn't go further from there. In the meanwhile, I found the github update itself got 3 failed deployments and I waited until a successful one was out. Giving it another shot with azd up didn't solve the issue through. The azd down --> azd up did.

On the other hand, upon looking at the log info., the previous failed deployment error was gone, which was the reason why I thought what you mentioned could be the case.

BTW, a side question here. It was mentioned that the Entra External ID (b2c) authentication/authorization would be worked up a few months back. I'm wondering if there's a near term plan on this? And I did figure out how to do that code wise but certain parameters was threaded deep into the few files, which would require quite some time to replace them altogether. A simple yes or no reply would make life easier. Thanks.

**Comment by mattgotteiner** [comment]
Entra External ID is still planned. We can't commit to a specific date as to when that would be ready unfortunately.

**Comment by mirojs** [comment]
@mattgotteiner This is a good enough answer, thanks.
