### ISSUE TITLE
raise error azure.core.exceptions.ServiceRequestError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate in certificate chain (_ssl.c:1002)

### ISSUE THREAD

**Issue by Mohit88489** [Azure-Samples/azure-search-openai-demo#183]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
x After running azd up it's should create the index and upload data into blob storage, yet it's not creating index and throwing the mentioned issue of certificate ( certificate verify failed: self signed certificate in certificaate in certificate chain (_ssl.c:1002)).

### Minimal steps to reproduce
> run the command **pwsh .\scripts\prepdocs.ps1** after **azd up**

### log messages given by the failure
Running "prepdocs.py"
Ensuring search index gptkbindex exists
Traceback (most recent call last):
  File "{localpath}\scripts\prepdocs.py", line 299, in <module>
    create_search_index()
  File "{localpath}\scripts\prepdocs.py", line 237, in create_search_index
    if args.index not in index_client.list_index_names():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "{localpath}\scripts\.venv\Lib\site-packages\azure\core\paging.py", line 124, in __next__
    return next(self._page_iterator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "{localpath}\scripts\.venv\Lib\site-packages\azure\core\paging.py", line 76, in __next__
    self._response = self._get_next(self.continuation_token)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "{localpath}\scripts\.venv\Lib\site-packages\azure\search\documents\indexes\_generated\operations\_indexes_operations.py", line 512, in get_next
    pipeline_response = self._client._pipeline.run(  # type: ignore # pylint: disable=protected-access
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "{localpath}\scripts\.venv\Lib\site-packages\azure\core\pipeline\_base.py", line 202, in run
    return first_node.send(pipeline_request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "{localpath}\scripts\.venv\Lib\site-packages\azure\core\pipeline\_base.py", line 70, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "{localpath}\scripts\.venv\Lib\site-packages\azure\core\pipeline\_base.py", line 70, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "{localpath}\scripts\.venv\Lib\site-packages\azure\core\pipeline\_base.py", line 70, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 2 more times]
  File "{localpath}\scripts\.venv\Lib\site-packages\azure\core\pipeline\policies\_redirect.py", line 156, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "{localpath}\scripts\.venv\Lib\site-packages\azure\core\pipeline\policies\_retry.py", line 470, in send
    raise err
  File "{localpath}\scripts\.venv\Lib\site-packages\azure\core\pipeline\policies\_retry.py", line 448, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "{localpath}\scripts\.venv\Lib\site-packages\azure\core\pipeline\policies\_authentication.py", line 110, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "{localpath}\scripts\.venv\Lib\site-packages\azure\core\pipeline\_base.py", line 70, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "{localpath}\scripts\.venv\Lib\site-packages\azure\core\pipeline\_base.py", line 70, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "{localpath}\scripts\.venv\Lib\site-packages\azure\core\pipeline\_base.py", line 70, in send
               ^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 1 more time]
  File "{localpath}\scripts\.venv\Lib\site-packages\azure\core\pipeline\_base.py", line 101, in send
    self._sender.send(request.http_request, **request.context.options),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "{localpath}\scripts\.venv\Lib\site-packages\azure\core\pipeline\transport\_requests_basic.py", line 364, 
in send in send raise error
azure.core.exceptions.ServiceRequestError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificaate in certificate chain (_ssl.c:1002)
>

### Expected/desired behavior
> its should create index and upload doc in blob storage.

### OS and Version?
> Windows 10

**Comment by jmgress** [comment]
Having the exact same issue

**Comment by pamelafox** [comment]
There may be an issue with SSL on your device, can you try the suggestions here? https://stackoverflow.com/a/43855394/1347623
Those have worked for me for similar errors.

**Comment by pamelafox** [comment]
Closing since there's nothing to fix on our end for this one.
