### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'content')

### ISSUE THREAD

**Issue by DSOTM-RSA** [Azure-Samples/azure-search-openai-demo#2068]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
**Azure Search SKU:** Basic
**Azure Semantic Ranker:** Free

**Chat Model:** gpt-4o-mini (2024-07-18)
**Embedding Model:** text-embedding-3-large

One particular query is causing a repeated `TypeError: Cannot read properties of undefined (reading 'content')` error when running. Many other queries work as expected using the Chat Approach, i.e. querying AI Search, and then the GPT for output.

All Developer Settings are standard. The following variations I have attempted to no avail.

-  "Upgrading" to use Azure Semantic Ranker @ Standard SKU
- Not using Semantic Re-Ranking
- Using Vector Search only

Logging messages suggest a "corrupted" Azure Open AI model output being passed to the stream.

### Any log messages given by the failure
> 2024-10-22T18:38:05.279160381Z 2024-10-22 18:38:05,278 - 169.254.130.5:44178 - "POST /chat/stream HTTP/1.1" 200
2024-10-22 18:38:04.626 +00:00 [Information] Microsoft.AspNetCore.Hosting.Diagnostics: Request starting HTTP/1.1 GET http://app-backend-XXXXXXXXXXX.azurewebsites.net/ - - -
2024-10-22 18:38:04.626 +00:00 [Debug] Microsoft.AspNetCore.Server.Kestrel.Connections: Connection id "0HN7HQUHVC18D" completed keep alive response.
2024-10-22 18:38:04.627 +00:00 [Information] Microsoft.AspNetCore.Hosting.Diagnostics: Request finished HTTP/1.1 GET https://app-backend-XXXXXXXXXXX.azurewebsites.net/ - 401 - - 0.6789ms
2024-10-22 18:38:05.260 +00:00 [Information] Microsoft.AspNetCore.Hosting.Diagnostics: Request starting HTTP/1.1 POST http://app-backend-XXXXXXXXXXX.azurewebsites.net/chat/stream - application/json 486
2024-10-22 18:38:05.261 +00:00 [Trace] Middleware: Request came in on normal port, sending to normal target http://169.254.130.3:8000/chat/stream
2024-10-22 18:38:05.261 +00:00 [Trace] Middleware: Forwarding request to http://169.254.130.3:8000/chat/stream
2024-10-22 18:38:05.262 +00:00 [Debug] Microsoft.AspNetCore.Server.Kestrel: Connection id "0HN7HQUHVC18D", Request id "0HN7HQUHVC18D:00000005": started reading request body.
2024-10-22 18:38:05.262 +00:00 [Debug] Microsoft.AspNetCore.Server.Kestrel: Connection id "0HN7HQUHVC18D", Request id "0HN7HQUHVC18D:00000005": done reading request body.
2024-10-22 18:38:05.279 +00:00 [Trace] Middleware: Forwarded request finished in 17.445ms 200 OK
2024-10-22 18:38:06.890 +00:00 [Debug] Microsoft.AspNetCore.Server.Kestrel.Connections: Connection id "0HN7HQUHVC18D" completed keep alive response.
2024-10-22 18:38:06.890 +00:00 [Information] Microsoft.AspNetCore.Hosting.Diagnostics: Request finished HTTP/1.1 POST https://app-backend-XXXXXXXXXXX.azurewebsites.net/chat/stream - 200 - application/json-lines 1630.0366ms
**2024-10-22T18:38:06.876391547Z 2024-10-22 18:38:06,854 - ERROR - Exception while generating response stream: Object of type bytes is not JSON serializable**
2024-10-22T18:38:06.876432447Z Traceback (most recent call last):
**2024-10-22T18:38:06.876438147Z   File "/tmp/8dcf1d5e014793d/app.py", line 211, in format_as_ndjson**
**2024-10-22T18:38:06.876441747Z     yield json.dumps(event, ensure_ascii=False, cls=JSONEncoder) + "\n"**
**2024-10-22T18:38:06.876464348Z           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^**
2024-10-22T18:38:06.876468348Z   File "/opt/python/3.11.8/lib/python3.11/json/__init__.py", line 238, in dumps
2024-10-22T18:38:06.876471748Z     **kw).encode(obj)
2024-10-22T18:38:06.876474748Z           ^^^^^^^^^^^
2024-10-22T18:38:06.876478048Z   File "/opt/python/3.11.8/lib/python3.11/json/encoder.py", line 200, in encode
2024-10-22T18:38:06.876481248Z     chunks = self.iterencode(o, _one_shot=True)
2024-10-22T18:38:06.876484448Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-22T18:38:06.876487448Z   File "/opt/python/3.11.8/lib/python3.11/json/encoder.py", line 258, in iterencode
2024-10-22T18:38:06.876490648Z     return _iterencode(o, 0)
2024-10-22T18:38:06.876493648Z            ^^^^^^^^^^^^^^^^^
2024-10-22T18:38:06.876496748Z   File "/tmp/8dcf1d5e014793d/app.py", line 204, in default
2024-10-22T18:38:06.876499948Z     return super().default(o)
2024-10-22T18:38:06.876503048Z            ^^^^^^^^^^^^^^^^^^
2024-10-22T18:38:06.876506048Z   File "/opt/python/3.11.8/lib/python3.11/json/encoder.py", line 180, in default
2024-10-22T18:38:06.876509248Z     raise TypeError(f'Object of type {o.__class__.__name__} '
2024-10-22T18:38:06.876512348Z TypeError: Object of type bytes is not JSON serializable
2024-10-22T18:38:06.896528922Z /opt/python/3.11.8/lib/python3.11/asyncio/events.py:84: RuntimeWarning: coroutine 'achat_wrapper' was never awaited
2024-10-22T18:38:06.896551222Z   self._context.run(self._callback, *self._args)
2024-10-22T18:38:06.896556322Z RuntimeWarning: Enable tracemalloc to get the object allocation traceback

### Expected/desired behavior
> Return a streamed response, assuming the response is within the bounds of the model context. How can I best debug this particular error, or use a method to catch these exceptions. I'm guessing perhaps digging through the logs from the Azure Open AI instance?

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
> 

### Mention any other details that might be useful

Wasn't an issue unitl about late last week, the application has been "live" for 3 weeks. **The system prompt is LARGE (>3000!) - could this be casuing an issue?**

> 

        # Allow client to replace the entire prompt, or to inject into the exiting prompt using >>>
        system_message = self.get_system_prompt(
            overrides.get("prompt_template"),
            self.follow_up_questions_prompt_content if overrides.get("suggest_followup_questions") else "",
        )

        response_token_limit = 1024
        messages = build_messages(
            model=self.chatgpt_model,
            system_prompt=system_message,
            past_messages=messages[:-1],
            # Model does not handle lengthy system messages well. Moving sources to latest user conversation to solve follow up questions prompt.
            new_user_content=original_user_query + "\n\nSources:\n" + content,
            max_tokens=self.chatgpt_token_limit - response_token_limit,
        )

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by DSOTM-RSA** [comment]
Context specific issues.
