### ISSUE TITLE
ErrorCode:ResourceNotFound || Document uploading to Blob Storage doesn't go through || Blob error

### ISSUE THREAD

**Issue by Citizen-XX** [Azure-Samples/azure-search-openai-demo#2095]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>Set the .env variables:
AZURE_ENV_NAME="azuresearchopenaidemo"
AZURE_LOCATION="eastus2"
AZURE_OPENAI_CHATGPT_DEPLOYMENT_CAPACITY=8
AZURE_OPENAI_CHATGPT_DEPLOYMENT_VERSION="turbo-2024-04-09"
AZURE_OPENAI_CHATGPT_MODEL="gpt-4"
AZURE_SUBSCRIPTION_ID="abcdefghijk"
DEPLOYMENT_TARGET="appservice"
USE_CHAT_HISTORY_BROWSER="true"
run 'azd up'

### Any log messages given by the failure
Running "prepdocs.py"
./app/backend/prepdocs.py "C:\AzureDemo/data/*" --verbose
Loading azd env from C:\AzureDemo\.azure\azuresearchopenaidemo\.env
Connecting to Azure services using the azd credential for tenant xxxxxx
Using local files: C:\AzureDemo/data/*
Checking whether search index gptkbindex exists...
Creating new search index gptkbindex
Including vectorizer for search index gptkbindex, using Azure OpenAI service cog-d2zur3a7jasps
Ingesting 'COHOUSING- VIABILIDAD SOCIOECONÓMICA DEL MODELO EN LIMA.pdf'
Extracting text from 'C:\AzureDemo/data\COHOUSING- VIABILIDAD SOCIOECONÓMICA DEL MODELO EN LIMA.pdf' using Azure Document Intelligence
Splitting 'COHOUSING- VIABILIDAD SOCIOECONÓMICA DEL MODELO EN LIMA.pdf' into sections
Section ends with unclosed table, starting next section with the table at page 3 offset 14499 table start 1079
Section ends with unclosed table, starting next section with the table at page 5 offset 22407 table start 282
Section ends with unclosed table, starting next section with the table at page 7 offset 29461 table start 858
Section ends with unclosed table, starting next section with the table at page 8 offset 32296 table start 532
Section ends with unclosed table, starting next section with the table at page 9 offset 34682 table start 723
Traceback (most recent call last):
  File "C:\AzureDemo\app\backend\prepdocs.py", line 422, in <module>
    loop.run_until_complete(main(ingestion_strategy, setup_index=not args.remove and not args.removeall))
  File "C:\Users\EAS Consulting\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\AzureDemo\app\backend\prepdocs.py", line 237, in main
    await strategy.run()
  File "C:\AzureDemo\app\backend\prepdocslib\filestrategy.py", line 86, in run
    blob_sas_uris = await self.blob_manager.upload_blob(file)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AzureDemo\app\backend\prepdocslib\blobmanager.py", line 53, in upload_blob
    await container_client.create_container()
  File "C:\AzureDemo\.venv\Lib\site-packages\azure\core\tracing\decorator_async.py", line 94, in wrapper_use_tracer
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AzureDemo\.venv\Lib\site-packages\azure\storage\blob\aio\_container_client_async.py", line 314, in create_container
    process_storage_error(error)
  File "C:\AzureDemo\.venv\Lib\site-packages\azure\storage\blob\_shared\response_handlers.py", line 186, in process_storage_error
    exec("raise error from None")   # pylint: disable=exec-used # nosec
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
  File "C:\AzureDemo\.venv\Lib\site-packages\azure\storage\blob\aio\_container_client_async.py", line 306, in create_container
    return await self._client.container.create( # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AzureDemo\.venv\Lib\site-packages\azure\core\tracing\decorator_async.py", line 94, in wrapper_use_tracer
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AzureDemo\.venv\Lib\site-packages\azure\storage\blob\_generated\aio\operations\_container_operations.py", line 159, in create
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "C:\AzureDemo\.venv\Lib\site-packages\azure\core\exceptions.py", line 161, in map_error
    raise error
azure.core.exceptions.ResourceNotFoundError: The specified resource does not exist.
RequestId:004bca49-c01e-003e-71e5-2a725c000000
Time:2024-10-30T16:05:08.4811789Z
ErrorCode:ResourceNotFound
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>ResourceNotFound</Code><Message>The specified resource does not exist.
RequestId:004bca49-c01e-003e-71e5-2a725c000000
Time:2024-10-30T16:05:08.4811789Z</Message></Error>

### Expected/desired behavior
Successfully running the 'azd up' command.
Successful uploading/indexing of documents from 'data' folder. (I believe this happens when I get to the deployment)

### OS and Version?
Windows 11 Pro

### azd version?
azd version 1.10.3 (commit 0595f33fe948ee6df3da492567e3e7943cb9a733)

### Versions
{
  "azure-cli": "2.65.0",
  "azure-cli-core": "2.65.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "init": "0.1.0"
  }
}
Bicep CLI version 0.30.23 (ec3612efc7)
PowerShell 7.4.6

### Mention any other details that might be useful
This error started to happen when I started to 'azd up' the demo into appservice and set the DEPLOYMENT_TARGET to 'appservice', and USE_CHAT_HISTORY_BROWSER to 'true', 
All resources were created correctly, but the problem came when splitting files with Document Intelligence, the file was .pdf format.
I've tested the data with local development, but never with the 2 new .env variables that I just set.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Citizen-XX** [comment]
Additional Error Information:
"level": "Error",
    "operationId": "373a25b6-1062-4c0c-b5e6-444a60cc2af6",
    "operationName": {
        "value": "Microsoft.CognitiveServices/accounts/listKeys/action",
        "localizedValue": "List Keys"
    },
    "resourceGroupName": "rg-azuresearchopenaidemo",
    "resourceProviderName": {
        "value": "Microsoft.CognitiveServices",
        "localizedValue": "Microsoft.CognitiveServices"
    },
    "resourceType": {
        "value": "Microsoft.CognitiveServices/accounts",
        "localizedValue": "Microsoft.CognitiveServices/accounts"
    },
    "resourceId": "/subscriptions/d488e441-4c7b-4499-9267-acd70f08343f/resourceGroups/rg-azuresearchopenaidemo/providers/Microsoft.CognitiveServices/accounts/cog-di-d2zur3a7jasps",
    "status": {
        "value": "Failed",
        "localizedValue": "Error"
    },
    "subStatus": {
        "value": "BadRequest",
        "localizedValue": "Solicitud incorrecta (código de estado HTTP: 400)"
    },
    "submissionTimestamp": "2024-10-30T18:08:00Z",
    "subscriptionId": "d488e441-4c7b-4499-9267-acd70f08343f",
    "tenantId": "f6d070a1-ac8b-4703-aeb9-bd3ec1cd1281",
    "properties": {
        "statusCode": "BadRequest",
        "serviceRequestId": null,
        "statusMessage": "{\"error\":{\"code\":\"BadRequest\",\"message\":\"Failed to list key. disableLocalAuth is set to be true\"}}"
        
Is there a .env variable that I should be setting?
I' never gotten this problem before.

**Comment by Citizen-XX** [comment]
I set the AZURE_AUTH_TENANT_ID with my tenant id and AZURE_USE_AUTHENTICATION (to 'true') and the error was gone.
