### ISSUE TITLE
httpx.ReadError during add_client_secret process

### ISSUE THREAD

**Issue by Citizen-XX** [Azure-Samples/azure-search-openai-demo#2096]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>Create a new env with 'azd env new'.
The initial .env variables set were:
AZURE_AUTH_TENANT_ID="my_auth_tenant_id"
AZURE_ENV_NAME="azuresearchopenaidemo"
AZURE_LOCATION="eastus2"
AZURE_OPENAI_CHATGPT_DEPLOYMENT_CAPACITY=8
AZURE_OPENAI_CHATGPT_DEPLOYMENT_VERSION="turbo-2024-04-09"
AZURE_OPENAI_CHATGPT_MODEL="gpt-4"
AZURE_SUBSCRIPTION_ID="my_subscriptio_id"
AZURE_USE_AUTHENTICATION="true"
DEPLOYMENT_TARGET="appservice"
USE_CHAT_HISTORY_BROWSER="true"
And run 'azd up'.

### Any log messages given by the failure
>Traceback (most recent call last):
  File "C:\AzureDemo\scripts\auth_init.py", line 213, in <module>
    asyncio.run(main())
  File "C:\Users\EAS Consulting\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\EAS Consulting\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\EAS Consulting\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\AzureDemo\scripts\auth_init.py", line 188, in main
    server_object_id, server_app_id, _ = await create_or_update_application_with_secret(
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AzureDemo\scripts\auth_init.py", line 68, in create_or_update_application_with_secret
    client_secret = await add_client_secret(graph_client, object_id)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AzureDemo\scripts\auth_init.py", line 43, in add_client_secret
    result = await graph_client.applications.by_application_id(app_id).add_password.post(request_password)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AzureDemo\.venv\Lib\site-packages\msgraph\generated\applications\item\add_password\add_password_request_builder.py", line 53, in post
    return await self.request_adapter.send_async(request_info, PasswordCredential, error_mapping)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AzureDemo\.venv\Lib\site-packages\kiota_http\httpx_request_adapter.py", line 176, in send_async
    response = await self.get_http_response_message(request_info, parent_span)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AzureDemo\.venv\Lib\site-packages\kiota_http\httpx_request_adapter.py", line 529, in get_http_response_message
    resp = await self._http_client.send(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AzureDemo\.venv\Lib\site-packages\httpx\_client.py", line 1661, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AzureDemo\.venv\Lib\site-packages\httpx\_client.py", line 1689, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AzureDemo\.venv\Lib\site-packages\httpx\_client.py", line 1726, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AzureDemo\.venv\Lib\site-packages\httpx\_client.py", line 1763, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AzureDemo\.venv\Lib\site-packages\msgraph_core\middleware\async_graph_transport.py", line 21, in handle_async_request
    response = await self.pipeline.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AzureDemo\.venv\Lib\site-packages\kiota_http\middleware\middleware.py", line 38, in send
    return await self._first_middleware.send(request, self._transport)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AzureDemo\.venv\Lib\site-packages\kiota_http\middleware\redirect_handler.py", line 77, in send
    response = await super().send(request, transport)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AzureDemo\.venv\Lib\site-packages\kiota_http\middleware\middleware.py", line 65, in send
    return await self.next.send(request, transport)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AzureDemo\.venv\Lib\site-packages\kiota_http\middleware\retry_handler.py", line 84, in send
    response = await super().send(request, transport)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AzureDemo\.venv\Lib\site-packages\kiota_http\middleware\middleware.py", line 65, in send
    return await self.next.send(request, transport)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AzureDemo\.venv\Lib\site-packages\kiota_http\middleware\parameters_name_decoding_handler.py", line 62, in send
    response = await super().send(request, transport)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AzureDemo\.venv\Lib\site-packages\kiota_http\middleware\middleware.py", line 65, in send
    return await self.next.send(request, transport)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AzureDemo\.venv\Lib\site-packages\kiota_http\middleware\url_replace_handler.py", line 44, in send
    response = await super().send(request, transport)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AzureDemo\.venv\Lib\site-packages\kiota_http\middleware\middleware.py", line 65, in send
    return await self.next.send(request, transport)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AzureDemo\.venv\Lib\site-packages\kiota_http\middleware\user_agent_handler.py", line 30, in send
    return await super().send(request, transport)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AzureDemo\.venv\Lib\site-packages\kiota_http\middleware\middleware.py", line 65, in send
    return await self.next.send(request, transport)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AzureDemo\.venv\Lib\site-packages\kiota_http\middleware\headers_inspection_handler.py", line 54, in send
    response = await super().send(request, transport)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AzureDemo\.venv\Lib\site-packages\kiota_http\middleware\middleware.py", line 65, in send
    return await self.next.send(request, transport)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AzureDemo\.venv\Lib\site-packages\msgraph_core\middleware\telemetry.py", line 48, in send
    response = await super().send(request, transport)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AzureDemo\.venv\Lib\site-packages\kiota_http\middleware\middleware.py", line 62, in send
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AzureDemo\.venv\Lib\site-packages\httpx\_transports\default.py", line 372, in handle_async_request
    with map_httpcore_exceptions():
  File "C:\Users\EAS Consulting\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\AzureDemo\.venv\Lib\site-packages\httpx\_transports\default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadError

### Expected/desired behavior
> No errors before starting to create the resources.

### OS and Version?
> Windows 11 Pro

### azd version?
> azd version 1.10.3 (commit 0595f33fe948ee6df3da492567e3e7943cb9a733)

### Versions
>{
"azure-cli": "2.65.0",
"azure-cli-core": "2.65.0",
"azure-cli-telemetry": "1.1.0",
"extensions": {
"init": "0.1.0"
}
}
Bicep CLI version 0.30.23 (ec3612efc7)
PowerShell 7.4.6

### Mention any other details that might be useful
> After asking ChatGPT I got: "The httpx.ReadError indicates that the program encountered an issue while trying to read data from the network during the add_client_secret process. This may be due to network connectivity issues, a timeout, or a problem with the endpoint configuration."
This is an error that I had never encountered when doing 'azd up'.
 

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
According to the traceback, that error happened during a request to the Microsoft Graph SDK (https://github.com/microsoftgraph/msgraph-sdk-python) to set the password for the Entra application. I don't see any similar reports in the issue tracker, so my hope would be that it was an intermittent network issue. Do you repeatedly get the same issue, on the same line of code, each time you run `azd up`?

**Comment by Citizen-XX** [comment]
I tried running the azd up again and the error was gone, I believe your diagnosis was correct and the error was product of an intermittent netword issue.
Thank you for addressing this ticket.
