### ISSUE TITLE
Index is not created, error in prepdocs.py 

### ISSUE THREAD

**Issue by darkanita** [Azure-Samples/azure-search-openai-demo#2112]
### This issue is for a: (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> azd deploy and azd up

### Any log messages given by the failure
> from azure.identity.aio import AzureDeveloperCliCredential, get_bearer_token_provider

### Expected/desired behavior
> Running "prepdocs.py"
./app/backend/prepdocs.py "C:\Users\alopezmoreno\OneDrive - Microsoft\Desktop\acceleratorAI\azure-search-openai-demo/data/*" --verbose
Traceback (most recent call last):
  File "C:\Users\alopezmoreno\OneDrive - Microsoft\Desktop\acceleratorAI\azure-search-openai-demo\app\backend\prepdocs.py", line 9, in <module>
    from azure.identity.aio import AzureDeveloperCliCredential, get_bearer_token_provider
  File "C:\Users\alopezmoreno\OneDrive - Microsoft\Desktop\acceleratorAI\azure-search-openai-demo\.venv\lib\site-packages\azure\identity\__init__.py", line 10, in <module>
    from ._credentials import (
  File "C:\Users\alopezmoreno\OneDrive - Microsoft\Desktop\acceleratorAI\azure-search-openai-demo\.venv\lib\site-packages\azure\identity\_credentials\__init__.py", line 5, in <module>
    from .authorization_code import AuthorizationCodeCredential
  File "C:\Users\alopezmoreno\OneDrive - Microsoft\Desktop\acceleratorAI\azure-search-openai-demo\.venv\lib\site-packages\azure\identity\_credentials\authorization_code.py", line 9, in <module>
    from .._internal.aad_client import AadClient
  File "C:\Users\alopezmoreno\OneDrive - Microsoft\Desktop\acceleratorAI\azure-search-openai-demo\.venv\lib\site-packages\azure\identity\_internal\__init__.py", line 5, in <module>
    from .aad_client import AadClient
  File "C:\Users\alopezmoreno\OneDrive - Microsoft\Desktop\acceleratorAI\azure-search-openai-demo\.venv\lib\site-packages\azure\identity\_internal\aad_client.py", line 11, in <module>
    from .aad_client_base import AadClientBase
  File "C:\Users\alopezmoreno\OneDrive - Microsoft\Desktop\acceleratorAI\azure-search-openai-demo\.venv\lib\site-packages\azure\identity\_internal\aad_client_base.py", line 20, in <module>
    from .aadclient_certificate import AadClientCertificate
  File "C:\Users\alopezmoreno\OneDrive - Microsoft\Desktop\acceleratorAI\azure-search-openai-demo\.venv\lib\site-packages\azure\identity\_internal\aadclient_certificate.py", line 7, in <module>
    from cryptography import x509
  File "C:\Users\alopezmoreno\OneDrive - Microsoft\Desktop\acceleratorAI\azure-search-openai-demo\.venv\lib\site-packages\cryptography\x509\__init__.py", line 7, in <module>
    from cryptography.x509 import certificate_transparency, verification
  File "C:\Users\alopezmoreno\OneDrive - Microsoft\Desktop\acceleratorAI\azure-search-openai-demo\.venv\lib\site-packages\cryptography\x509\certificate_transparency.py", line 11, in <module>
    from cryptography.hazmat.bindings._rust import x509 as rust_x509
ImportError: DLL load failed while importing _rust: The specified procedure could not be found.

### OS and Version?
> Windows 11 Enterprise

### azd version?
> run `azd version` and copy paste here.
azd version 1.10.3
### Versions
> Python 3.11.10

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
That error usually indicated that you created a venv outside the devcontainer and then tried to use it inside the devcontainer, or vice versa. (Mismatch in the OS used in the venv) 

Can you remove the venv folder entirely and try again?
