### ISSUE TITLE
VSCode DevContainer issue

### ISSUE THREAD

**Issue by amirj** [Azure-Samples/azure-search-openai-demo#2125]
I have the latest versions of Docker (4.35.1) and Node (23) and trying to load the project in vscode:

`ERROR: Feature "Node.js (via nvm), yarn and pnpm" (ghcr.io/devcontainers/features/node) failed to install! Look at the documentation at https://github.com/devcontainers/features/tree/main/src/node for help troubleshooting this error.
`

The full log:

```
[2024-11-07T03:27:25.678Z] Dev Containers 0.390.0 in VS Code 1.95.1 (65edc4939843c90c34d61f4ce11704f09d3e5cb6).
[2024-11-07T03:27:25.678Z] Start: Resolving Remote
[2024-11-07T03:27:25.695Z] Setting up container for folder or workspace: /Users/test/codes/azure-search-openai-demo
[2024-11-07T03:27:25.695Z] Context: desktop-linux
[2024-11-07T03:27:25.696Z] Start: Check Docker is running
[2024-11-07T03:27:25.696Z] Start: Run: docker version
[2024-11-07T03:27:25.728Z] Client:
 Version:           27.3.1
 API version:       1.47
 Go version:        go1.22.7
 Git commit:        ce12230
 Built:             Fri Sep 20 11:38:18 2024
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

[2024-11-07T03:27:25.728Z] Server: Docker Desktop 4.35.1 (173168)
 Engine:
  Version:          27.3.1
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.22.7
  Git commit:       41ca978
  Built:            Fri Sep 20 11:41:19 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.7.21
  GitCommit:        472731909fa34bd7bc9c087e4c27943f9835f111
 runc:
  Version:          1.1.13
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
...
[2024-11-07T03:27:56.317Z]  > [dev_containers_target_stage 7/7] RUN --mount=type=bind,from=dev_containers_feature_content_source,source=node_2,target=/tmp/build-features-src/node_2     cp -ar /tmp/build-features-src/node_2 /tmp/dev-container-features  && chmod -R 0755 /tmp/dev-container-features/node_2  && cd /tmp/dev-container-features/node_2  && chmod +x ./devcontainer-features-install.sh  && ./devcontainer-features-install.sh  && rm -rf /tmp/dev-container-features/node_2:
0.172 ===========================================================================
[2024-11-07T03:27:56.317Z] 
0.172 Feature       : Node.js (via nvm), yarn and pnpm
0.172 Description   : Installs Node.js, nvm, yarn, pnpm, and needed dependencies.
0.172 Id            : ghcr.io/devcontainers/features/node
0.172 Version       : 1.6.1
0.172 Documentation : https://github.com/devcontainers/features/tree/main/src/node
[2024-11-07T03:27:56.317Z] 
0.172 Options       :
0.172     VERSION="18"
[2024-11-07T03:27:56.317Z] 
0.172     NODEGYPDEPENDENCIES="false"
[2024-11-07T03:27:56.317Z] 0.172     NVMINSTALLPATH="/usr/local/share/nvm"
0.172     PNPMVERSION="latest"
[2024-11-07T03:27:56.317Z] 
0.172     NVMVERSION="latest"
0.172     INSTALLYARNUSINGAPT="true"
[2024-11-07T03:27:56.317Z] 
[2024-11-07T03:27:56.317Z] 0.172 ===========================================================================
0.546 NVM_VERSION=0.40.1
[2024-11-07T03:27:56.317Z] 0.705 NVM already installed.
1.043 Version '18' not found - try `nvm ls-remote` to browse available versions.
[2024-11-07T03:27:56.317Z] 
1.044 ERROR: Feature "Node.js (via nvm), yarn and pnpm" (ghcr.io/devcontainers/features/node) failed to install! Look at the documentation at https://github.com/devcontainers/features/tree/main/src/node for help troubleshooting this error.
[2024-11-07T03:27:56.317Z] ------
[2024-11-07T03:27:56.321Z] Dockerfile.extended:44
--------------------
  43 |     ENV PATH="/usr/local/share/nvm/current/bin:${PATH}"
[2024-11-07T03:27:56.321Z]   44 | >>> RUN --mount=type=bind,from=dev_containers_feature_content_source,source=node_2,target=/tmp/build-features-src/node_2 \
[2024-11-07T03:27:56.321Z]   45 | >>>     cp -ar /tmp/build-features-src/node_2 /tmp/dev-container-features \
[2024-11-07T03:27:56.321Z]   46 | >>>  && chmod -R 0755 /tmp/dev-container-features/node_2 \
  47 | >>>  && cd /tmp/dev-container-features/node_2 \
  48 | >>>  && chmod +x ./devcontainer-features-install.sh \
  49 | >>>  && ./devcontainer-features-install.sh \
  50 | >>>  && rm -rf /tmp/dev-container-features/node_2
  51 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c cp -ar /tmp/build-features-src/node_2 /tmp/dev-container-features  && chmod -R 0755 /tmp/dev-container-features/node_2  && cd /tmp/dev-container-features/node_2  && chmod +x ./devcontainer-features-install.sh  && ./devcontainer-features-install.sh  && rm -rf /tmp/dev-container-features/node_2" did not complete successfully: exit code: 3
[2024-11-07T03:27:56.329Z] Stop (25444 ms): Run: docker buildx build --load --build-context dev_containers_feature_content_source=/var/folders/yz/s47qcn1d3dddsj_zbgj_n3c80000gp/T/devcontainercli/container-features/0.72.0-1730950046590 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/python:3.11 --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -f /var/folders/yz/s47qcn1d3dddsj_zbgj_n3c80000gp/T/devcontainercli/container-features/0.72.0-1730950046590/Dockerfile.extended -t vsc-azure-search-openai-demo-f684405374878321a4bfe34088f4a9fdf59681377fdab76db91665f20b9109bb-features /Users/test/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/empty-folder
[2024-11-07T03:27:56.330Z] Error: Command failed: docker buildx build --load --build-context dev_containers_feature_content_source=/var/folders/yz/s47qcn1d3dddsj_zbgj_n3c80000gp/T/devcontainercli/container-features/0.72.0-1730950046590 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/python:3.11 --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -f /var/folders/yz/s47qcn1d3dddsj_zbgj_n3c80000gp/T/devcontainercli/container-features/0.72.0-1730950046590/Dockerfile.extended -t vsc-azure-search-openai-demo-f684405374878321a4bfe34088f4a9fdf59681377fdab76db91665f20b9109bb-features /Users/test/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/empty-folder
[2024-11-07T03:27:56.331Z]     at ytA (/Users/test/.vscode/extensions/ms-vscode-remote.remote-containers-0.390.0/dist/spec-node/devContainersSpecCLI.js:465:1260)
[2024-11-07T03:27:56.331Z]     at bH (/Users/test/.vscode/extensions/ms-vscode-remote.remote-containers-0.390.0/dist/spec-node/devContainersSpecCLI.js:465:1002)
[2024-11-07T03:27:56.331Z]     at async TtA (/Users/test/.vscode/extensions/ms-vscode-remote.remote-containers-0.390.0/dist/spec-node/devContainersSpecCLI.js:482:3848)
[2024-11-07T03:27:56.331Z]     at async iB (/Users/test/.vscode/extensions/ms-vscode-remote.remote-containers-0.390.0/dist/spec-node/devContainersSpecCLI.js:482:4963)
[2024-11-07T03:27:56.331Z]     at async wrA (/Users/test/.vscode/extensions/ms-vscode-remote.remote-containers-0.390.0/dist/spec-node/devContainersSpecCLI.js:663:203)
[2024-11-07T03:27:56.331Z]     at async DrA (/Users/test/.vscode/extensions/ms-vscode-remote.remote-containers-0.390.0/dist/spec-node/devContainersSpecCLI.js:662:14830)
[2024-11-07T03:27:56.331Z]     at async /Users/test/.vscode/extensions/ms-vscode-remote.remote-containers-0.390.0/dist/spec-node/devContainersSpecCLI.js:482:1190
[2024-11-07T03:27:56.338Z] Stop (30470 ms): Run: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) /Users/test/.vscode/extensions/ms-vscode-remote.remote-containers-0.390.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/test/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-c923d0a8-6175-4054-9697-04ac6e7576001730950045272 --workspace-folder /Users/test/codes/azure-search-openai-demo --workspace-mount-consistency cached --gpu-availability detect --id-label devcontainer.local_folder=/Users/test/codes/azure-search-openai-demo --id-label devcontainer.config_file=/Users/test/codes/azure-search-openai-demo/.devcontainer/devcontainer.json --log-level debug --log-format json --config /Users/test/codes/azure-search-openai-demo/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root --include-configuration --include-merged-configuration
[2024-11-07T03:27:56.338Z] Exit code 1
[2024-11-07T03:27:56.342Z] Command failed: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) /Users/test/.vscode/extensions/ms-vscode-remote.remote-containers-0.390.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/test/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-c923d0a8-6175-4054-9697-04ac6e7576001730950045272 --workspace-folder /Users/test/codes/azure-search-openai-demo --workspace-mount-consistency cached --gpu-availability detect --id-label devcontainer.local_folder=/Users/test/codes/azure-search-openai-demo --id-label devcontainer.config_file=/Users/test/codes/azure-search-openai-demo/.devcontainer/devcontainer.json --log-level debug --log-format json --config /Users/test/codes/azure-search-openai-demo/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root --include-configuration --include-merged-configuration
[2024-11-07T03:27:56.342Z] Exit code 1
```

**Comment by amirj** [comment]
@pamelafox This thread might be relevant: https://github.com/microsoft/vscode-remote-release/issues/9126
