### ISSUE TITLE
Operation returned an invalid status 'Forbidden'

### ISSUE THREAD

**Issue by amirj** [Azure-Samples/azure-search-openai-demo#2135]
I can start the app locally and search; also can run preprdocs and index new documents.

Also I was able to deploy the app using azd deploy successfully, but once I'm submitting a sample query, I'm getting the following error:

```
2024-11-10T10:47:33.514990646Z 2024-11-10 10:47:33,514 - 169.254.129.1:61037 - "POST /chat/stream HTTP/1.1" 200
2024-11-10T10:47:35.823875842Z 2024-11-10 10:47:35,820 - ERROR - Exception while generating response stream: Operation returned an invalid status 'Forbidden'
2024-11-10T10:47:35.823911643Z Traceback (most recent call last):
2024-11-10T10:47:35.823918443Z   File "/tmp/8dd0173c9cb3074/app.py", line 200, in format_as_ndjson
2024-11-10T10:47:35.823923043Z     async for event in r:
2024-11-10T10:47:35.823926943Z   File "/tmp/8dd0173c9cb3074/approaches/chatapproach.py", line 113, in run_with_streaming
2024-11-10T10:47:35.823931143Z     extra_info, chat_coroutine = await self.run_until_final_call(
2024-11-10T10:47:35.823935143Z                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-10T10:47:35.823939043Z   File "/tmp/8dd0173c9cb3074/approaches/chatreadretrieveread.py", line 159, in run_until_final_call
2024-11-10T10:47:35.823945943Z     results = await self.search(
2024-11-10T10:47:35.823949743Z               ^^^^^^^^^^^^^^^^^^
2024-11-10T10:47:35.823962543Z   File "/tmp/8dd0173c9cb3074/approaches/approach.py", line 175, in search
2024-11-10T10:47:35.823967143Z     async for page in results.by_page():
2024-11-10T10:47:35.823970943Z   File "/tmp/8dd0173c9cb3074/antenv/lib/python3.11/site-packages/azure/core/async_paging.py", line 94, in __anext__
2024-11-10T10:47:35.823975344Z     self._response = await self._get_next(self.continuation_token)
2024-11-10T10:47:35.823979444Z                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-10T10:47:35.823983444Z   File "/tmp/8dd0173c9cb3074/antenv/lib/python3.11/site-packages/azure/search/documents/aio/_paging.py", line 109, in _get_next_cb
2024-11-10T10:47:35.823987444Z     return await self._client.documents.search_post(search_request=self._initial_query.request, **self._kwargs)
2024-11-10T10:47:35.823991744Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-10T10:47:35.825333161Z   File "/tmp/8dd0173c9cb3074/antenv/lib/python3.11/site-packages/azure/core/tracing/decorator_async.py", line 105, in wrapper_use_tracer
2024-11-10T10:47:35.825358261Z     return await func(*args, **kwargs)
2024-11-10T10:47:35.825364262Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-10T10:47:35.825368662Z   File "/tmp/8dd0173c9cb3074/antenv/lib/python3.11/site-packages/azure/search/documents/_generated/aio/operations/_documents_operations.py", line 409, in search_post
2024-11-10T10:47:35.825372762Z     raise HttpResponseError(response=response, model=error)
2024-11-10T10:47:35.825376662Z azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'Forbidden'
```

I setup the services (search, docintelligence,...) via azure portal, rather than azd up; so some permissions might be missed. Could you guide me what is missing in my deployed app? --please note that it runs perfectly in local!

**Comment by pamelafox** [comment]
All of your issues seem to be stemming from the same cause, the lack of identity and roles. I'll close this issue since I answered the other two with similar information.

**Comment by azadehgnia** [comment]
I got the same error, all the RBAC assignments were properly done.

In my case on the search service under API Access control setting (under keys), it only allowed key access and not RBAC. I changed it and it fixed the error.
