### ISSUE TITLE
why new storage account to enable user upload feature?

### ISSUE THREAD

**Issue by amirj** [Azure-Samples/azure-search-openai-demo#2196]
Hi,

The app is using two blob storage accounts, one of them named as [blob_container_client](https://github.com/Azure-Samples/azure-search-openai-demo/blob/69a26effff9a52bb919f93bc32b0bbf82356049b/app/backend/app.py#L507C5-L507C26) and the other one is [user_blob_container_client](https://github.com/Azure-Samples/azure-search-openai-demo/blob/69a26effff9a52bb919f93bc32b0bbf82356049b/app/backend/app.py#L539)

Two questions:
1. Could you help me to understand why we need two blobs and why not using the main blob since we're organising user's content in subfolders?
2. How to set AZURE_USERSTORAGE_ACCOUNT? --unfortunately I need to set it manually and not via bicep--

**Comment by amirj** [comment]
@pamelafox If I upgrade my main blob to ADL Gen2, can I use the same blob across the whole project?

**Comment by WannabDad** [comment]
Have you managed to resolve this, i dont have the upload file completely after deploying, was this the same issue you had?

**Comment by Cortex1-NeuroIQ-AI** [comment]
I can't see managed file upload option in the screen either.

**Comment by pamelafox** [comment]
For the user upload feature, you must enable both user login and user upload. Please make sure you've followed all the steps here:
https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/docs/deploy_features.md#enabling-user-document-upload
I recommend first enabling user login, confirming that works, and then enabling user upload.

@amirj  And sorry, I haven't had a chance to try to use ADSL2 everywhere. They have different SDKs, so I suspect you'd need to modify all the Python code that uses the standard blob SDK and have it use ADLS2 instead.

**Comment by Cortex1-NeuroIQ-AI** [comment]
@pamelafox  
 I set the USE_USER_UPLOAD="true" and did azd up. Now I can see the user file upload option. Thank you for the quick response.

**Comment by chris0connor** [comment]
I have the same issue - the USER_UPLOAD button is showing - but I get the same error.
Have tried to set permissions - but same errors (still) !

_python ./scripts/manageacl.py -v --acl-action enable_acls_

**Comment by pamelafox** [comment]
@chris0connor What error are you seeing exactly, in the server logs?

**Comment by kachihro** [comment]
Thanks - we're seeing an AUTH error ;
* This the log when attempting to upload
* Below is the "Get Recently Uploaded" 

This suggests that the permissions are not correct - but i can't work out what's needed for update ;

===================================================

2025-12-14T23:57:23.9450375Z stderr F 2025-12-14 23:57:23,944 - ERROR - Uploading file for user 06848942-9a73-46b7-95ed-00eaaf9305ff
2025-12-14T23:57:24.0014601Z stderr F 2025-12-14 23:57:24,001 - INFO - Creating directory path 06848942-9a73-46b7-95ed-00eaaf9305ff
2025-12-14T23:57:24.0351714Z stderr F 2025-12-14 23:57:24,034 - ERROR - Error uploading file: (AuthorizationFailure) This request is not authorized to perform this operation.
2025-12-14T23:57:24.0352168Z stderr F RequestId:36f3c5db-b01f-005d-2055-6d7030000000
2025-12-14T23:57:24.0352351Z stderr F Time:2025-12-14T23:57:24.0285793Z
2025-12-14T23:57:24.0352386Z stderr F **Code: AuthorizationFailure**
2025-12-14T23:57:24.0352409Z stderr F **Message: This request is not authorized to perform this operation.**
2025-12-14T23:57:24.0352433Z stderr F RequestId:36f3c5db-b01f-005d-2055-6d7030000000
2025-12-14T23:57:24.0352453Z stderr F Time:2025-12-14T23:57:24.0285793Z
2025-12-14T23:57:24.0359177Z stdout F 2025-12-14 23:57:24,035 - 100.100.209.4:0 - "POST /upload HTTP/1.1" 500

===================================================

2025-12-14T23:55:47.7849098Z stderr F 2025-12-14 23:55:47,780 - ERROR - Exception on request GET /list_uploaded
2025-12-14T23:55:47.7849098Z stdout F 2025-12-14 23:55:47,784 - 100.100.209.4:0 - "GET /list_uploaded HTTP/1.1" 500
2025-12-14T23:55:47.7849447Z stderr F Traceback (most recent call last):
2025-12-14T23:55:47.7849764Z stderr F   File "/usr/local/lib/python3.11/site-packages/quart/app.py", line 1464, in handle_request
2025-12-14T23:55:47.7849795Z stderr F     return await self.full_dispatch_request(request_context)
2025-12-14T23:55:47.7849814Z stderr F            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-12-14T23:55:47.7849840Z stderr F   File "/usr/local/lib/python3.11/site-packages/quart/app.py", line 1502, in full_dispatch_request
2025-12-14T23:55:47.7849863Z stderr F     result = await self.handle_user_exception(error)
2025-12-14T23:55:47.7849884Z stderr F              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-12-14T23:55:47.7849946Z stderr F   File "/usr/local/lib/python3.11/site-packages/quart/app.py", line 1059, in handle_user_exception
2025-12-14T23:55:47.7849967Z stderr F     raise error
2025-12-14T23:55:47.7849988Z stderr F   File "/usr/local/lib/python3.11/site-packages/quart/app.py", line 1500, in full_dispatch_request
2025-12-14T23:55:47.7850009Z stderr F     result = await self.dispatch_request(request_context)
2025-12-14T23:55:47.7850029Z stderr F              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-12-14T23:55:47.7850049Z stderr F   File "/usr/local/lib/python3.11/site-packages/quart/app.py", line 1597, in dispatch_request
2025-12-14T23:55:47.7850413Z stderr F     return await self.ensure_async(handler)(**request_.view_args)  # type: ignore[return-value]
2025-12-14T23:55:47.7850459Z stderr F            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-12-14T23:55:47.7850487Z stderr F   File "/app/decorators.py", line 56, in auth_handler
2025-12-14T23:55:47.7850508Z stderr F     return await route_fn(auth_claims, *args, **kwargs)
2025-12-14T23:55:47.7850548Z stderr F            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-12-14T23:55:47.7850569Z stderr F   File "/app/app.py", line 491, in list_uploaded
2025-12-14T23:55:47.7850590Z stderr F     files = await adls_manager.list_blobs(user_oid)
2025-12-14T23:55:47.7850610Z stderr F             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-12-14T23:55:47.7850630Z stderr F   File "/app/prepdocslib/blobmanager.py", line 369, in list_blobs
2025-12-14T23:55:47.7850652Z stderr F     await self._ensure_directory(directory_path=user_oid, user_oid=user_oid)
2025-12-14T23:55:47.7850672Z stderr F   File "/app/prepdocslib/blobmanager.py", line 170, in _ensure_directory
2025-12-14T23:55:47.7850694Z stderr F     await directory_client.create_directory()
2025-12-14T23:55:47.7850715Z stderr F   File "/usr/local/lib/python3.11/site-packages/azure/core/tracing/decorator_async.py", line 138, in wrapper_use_tracer
2025-12-14T23:55:47.7850737Z stderr F     return await func(*args, **kwargs)
2025-12-14T23:55:47.7850758Z stderr F            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-12-14T23:55:47.7850795Z stderr F   File "/usr/local/lib/python3.11/site-packages/azure/storage/filedatalake/aio/_data_lake_directory_client_async.py", line 178, in create_directory
2025-12-14T23:55:47.7850933Z stderr F     return await self._create('directory', metadata=metadata, **kwargs)
2025-12-14T23:55:47.7851007Z stderr F            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-12-14T23:55:47.7851055Z stderr F   File "/usr/local/lib/python3.11/site-packages/azure/storage/filedatalake/aio/_path_client_async.py", line 216, in _create
2025-12-14T23:55:47.7851085Z stderr F     process_storage_error(error)
2025-12-14T23:55:47.7851110Z stderr F   File "/usr/local/lib/python3.11/site-packages/azure/storage/filedatalake/_deserialize.py", line 224, in process_storage_error
2025-12-14T23:55:47.7851131Z stderr F     exec("raise error from None")   # pylint: disable=exec-used # nosec
2025-12-14T23:55:47.7851152Z stderr F     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-12-14T23:55:47.7851172Z stderr F   File "<string>", line 1, in <module>
2025-12-14T23:55:47.7851540Z stderr F azure.core.exceptions.HttpResponseError: (AuthorizationFailure) This request is not authorized to perform this operation.
2025-12-14T23:55:47.7851570Z stderr F RequestId:26225e8b-001f-002a-0555-6da5a4000000

===================================================
