### ISSUE TITLE
Upload Issue: Cannot find nested property 'oids' on the resource type 'search.documentFields'.

### ISSUE THREAD

**Issue by khallissey** [Azure-Samples/azure-search-openai-demo#2221]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Upload file after bootup with necessary environmental varibale changes such as AZURE_AUTH and the others detailed in the readme.

### Any log messages given by the failure
>
2024-12-10 18:29:01,105 - INFO - Ingesting 'Assessment Guide.pdf'
2024-12-10 18:29:01,107 - INFO - Extracting text from 'Level 1 CMMC SELF-Assessment Guide.pdf' using Azure Document Intelligence
 
2024-12-10 18:29:12,902 - INFO - Splitting 'Level 1 CMMC SELF-Assessment Guide.pdf' into sections
2024-12-10 18:29:12,947 - INFO - Section ends with unclosed figure, starting next section with the figure at page 2 offset 1684 figure start 840
2024-12-10 18:29:12,948 - INFO - Section ends with unclosed figure, starting next section with the figure at page 2 offset 3585 figure start 938
2024-12-10 18:29:12,968 - INFO - Section ends with unclosed figure, starting next section with the figure at page 52 offset 93012 figure start 860
 
2024-12-10 18:29:13,448 - INFO - Computed embeddings in batch. Batch size: 16, Token count: 4173
 
2024-12-10 18:29:13,686 - INFO - Computed embeddings in batch. Batch size: 16, Token count: 3703
 
2024-12-10 18:29:13,907 - INFO - Computed embeddings in batch. Batch size: 16, Token count: 3506
 
2024-12-10 18:29:14,126 - INFO - Computed embeddings in batch. Batch size: 16, Token count: 3708
 
2024-12-10 18:29:14,341 - INFO - Computed embeddings in batch. Batch size: 16, Token count: 3683
 
2024-12-10 18:29:14,545 - INFO - Computed embeddings in batch. Batch size: 16, Token count: 3455
 
2024-12-10 18:29:14,648 - INFO - Computed embeddings in batch. Batch size: 3, Token count: 1061
 
2024-12-10 18:29:15,132 - ERROR - Exception on request POST /upload
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/quart/app.py", line 1403, in handle_request
    return await self.full_dispatch_request(request_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/quart/app.py", line 1441, in full_dispatch_request
    result = await self.handle_user_exception(error)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/quart/app.py", line 1029, in handle_user_exception
    raise error
  File "/usr/local/lib/python3.11/site-packages/quart/app.py", line 1439, in full_dispatch_request
    result = await self.dispatch_request(request_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/quart/app.py", line 1535, in dispatch_request
    return await self.ensure_async(handler)(**request_.view_args)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/decorators.py", line 56, in auth_handler
    return await route_fn(auth_claims, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app.py", line 374, in upload
    await ingester.add_file(File(content=file_io, acls={"oids": [user_oid]}, url=file_client.url))
2024-12-10 18:29:15,140 - 50.217.99.14:0 - "POST /upload HTTP/1.1" 500
  File "/app/prepdocslib/filestrategy.py", line 144, in add_file
    await self.search_manager.update_content(sections, url=file.url)
  File "/app/prepdocslib/searchmanager.py", line 297, in update_content
    await search_client.upload_documents(documents)
  File "/usr/local/lib/python3.11/site-packages/azure/search/documents/aio/_search_client_async.py", line 578, in upload_documents
    results = await self.index_documents(batch, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/core/tracing/decorator_async.py", line 105, in wrapper_use_tracer
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/search/documents/aio/_search_client_async.py", line 677, in index_documents
    return await self._index_documents_actions(actions=batch.actions, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/search/documents/aio/_search_client_async.py", line 685, in _index_documents_actions
    batch_response = await self._client.documents.index(batch=batch, error_map=error_map, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/core/tracing/decorator_async.py", line 105, in wrapper_use_tracer
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/search/documents/_generated/aio/operations/_documents_operations.py", line 857, in index
    raise HttpResponseError(response=response, model=error)
azure.core.exceptions.HttpResponseError: () The request is invalid. Details: Cannot find nested property 'oids' on the resource type 'search.documentFields'.
Code: 
Message: The request is invalid. Details: Cannot find nested property 'oids' on the resource type 'search.documentFields'.

### Expected/desired behavior
>Just wanted to upload a document for a summary. 

### OS and Version?
> My laptop is Windows 11, but if that isn't the OS you're looking for let me know.

### azd version?
> run `azd version` and copy paste here.
azd version 1.11.0 (commit 5b92e0687e1fa96dfc8292f4b900c0c58610b6a5)

### Versions
>

### Mention any other details that might be useful
Was trying to upload document and got the error  in the popup. After a couple minutes the document popped up as if it had actually been successfully uploaded, but the model couldn't reference the document for inference.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Did you follow these steps from the docs after enabling the upload feature?


If you are enabling this feature on an existing index, you should also update your index to have the new `storageUrl` field:

```shell
python ./scripts/manageacl.py  -v --acl-action enable_acls
```

And then update existing search documents with the storage URL of the main Blob container:

```shell
python ./scripts/manageacl.py  -v --acl-action update_storage_urls --url <https://YOUR-MAIN-STORAGE-ACCOUNT.blob.core.windows.net/content/>
```

**Comment by khallissey** [comment]
That fixed it, my apologies. I didn't realize that was there. Sorry for wasting your time.

**Comment by pamelafox** [comment]
Great, no worries!
