### ISSUE TITLE
Operation returned an invalid status 'Unauthorized'

### ISSUE THREAD

**Issue by mca-d** [Azure-Samples/azure-search-openai-demo#276]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
Running the app locally
1. Run `azd login`
2. Change dir to `app`
3. Run `./start.sh`

I am using keys so I commented out the token mentions and set the keys as env variables
### Any log messages given by the failure
azure.core.exceptions.ClientAuthenticationError: Operation returned an invalid status 'Unauthorized'

### Expected/desired behavior
Being able to get a response when running the demo code

### OS and Version?

macOS Ventura

### azd version?
azd version 1.0.1 (commit e0cd1aca716fa5d08704beade7dcc734fe68f5f1)

### Versions
>

### Mention any other details that might be useful
I am using the documents provided by the demo.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by mca-d** [comment]
I am running it locally, not deploying it. If I run azd up I get the error that I don't have 'roleAssignments/write' (which is true)
After doing some digging i see that the error is coming from chatreadretrieveread.py, it completes step 1, but it fails when calling search_client...

**Comment by apvarana** [comment]
I am getting same issue while running locally, did u find a resolution

**Comment by mca-d** [comment]
> I am getting same issue while running locally, did u find a resolution

No :(

**Comment by mca-d** [comment]
missclick

**Comment by ZepposBE** [comment]
Getting this also while running locally:

`Error: Operation returned an invalid status 'Unauthorized'`

Also, same as @mca-d  

`ERROR:root:Exception in /ask
Traceback (most recent call last):
  File "C:\Projects\Azure Search OpenAI Demo\azure-search-openai-demo\app\backend\app.py", line 96, in ask
    r = impl.run(request.json["question"], request.json.get("overrides") or {})
  File "C:\Projects\Azure Search OpenAI Demo\azure-search-openai-demo\app\backend\approaches\retrievethenread.py", line 68, in run
    results = [doc[self.sourcepage_field] + ": " + nonewlines(doc[self.content_field]) for doc in r]
  File "C:\Projects\Azure Search OpenAI Demo\azure-search-openai-demo\app\backend\approaches\retrievethenread.py", line 68, in <listcomp>
    results = [doc[self.sourcepage_field] + ": " + nonewlines(doc[self.content_field]) for doc in r]
  File "C:\Projects\Azure Search OpenAI Demo\azure-search-openai-demo\app\backend\backend_env\lib\site-packages\azure\search\documents\_paging.py", 
line 54, in __next__
    return next(self._page_iterator)
  File "C:\Projects\Azure Search OpenAI Demo\azure-search-openai-demo\app\backend\backend_env\lib\site-packages\azure\core\paging.py", line 76, in __next__
    self._response = self._get_next(self.continuation_token)
  File "C:\Projects\Azure Search OpenAI Demo\azure-search-openai-demo\app\backend\backend_env\lib\site-packages\azure\search\documents\_paging.py", 
line 114, in _get_next_cb
    return self._client.documents.search_post(
  File "C:\Projects\Azure Search OpenAI Demo\azure-search-openai-demo\app\backend\backend_env\lib\site-packages\azure\core\tracing\decorator.py", line 76, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "C:\Projects\Azure Search OpenAI Demo\azure-search-openai-demo\app\backend\backend_env\lib\site-packages\azure\search\documents\_generated\operations\_documents_operations.py", line 780, in search_post
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "C:\Projects\Azure Search OpenAI Demo\azure-search-openai-demo\app\backend\backend_env\lib\site-packages\azure\core\exceptions.py", line 109, in map_error
    raise error
azure.core.exceptions.ClientAuthenticationError: Operation returned an invalid status 'Unauthorized'`

**Comment by marceloricciardi** [comment]
Same issue here too.

**Comment by marceloricciardi** [comment]
> Same issue here too.

This solved my problem: https://github.com/Azure-Samples/azure-search-openai-demo/issues/17#issuecomment-1472074150

**Comment by Aravind03** [comment]
Hi All,

In my case, my Architect have deployed the solution and I tried to integrate that with a different new Search Service(Free tier) created manually within the same subscription and received the same error.

When compared the settings, it was identified that the below configuration is the problem. Please check once in your environment.

In the Search service, select **Keys** under Settings in the left navigation. Now select **Both** radio button under 'API access control'

**Comment by connorwehrum** [comment]
Still getting this issue when **running locally** I am seeing a lot of solutions in the comments, but these have to do with deploying the solution to Azure unless I am misunderstanding.
