### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by phfontes** [Azure-Samples/azure-search-openai-demo#277]
> Please provide us with the following information:

![error](https://github.com/Azure-Samples/azure-search-openai-demo/assets/132704972/7243ee6a-1a6e-47b7-a851-c83571de5a23)

Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Upload the file and run azd up

### Any log messages given by the failure
>

### Expected/desired behavior
> Show page of the file

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

Windows 10

### azd version?
> run `azd version` and copy paste here.

1.0.0

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
@phfontes That error could have many causes. Have you tried looking at the Log stream or downloading the full logs?

## Log stream

Open the App Service resource up in the Azure Portal. Then under *Monitoring* on the sidebar, select *Log stream*.

You'll see something like:

![Screenshot of Log stream](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjyLtUogDjl2m7RmAeYEvw_L-RfpDyJGCOSFNKxc3_r6AK_Q1zLyT7Coxl9xH39Z1QchVtU9-DQAaA7kSHdEERXoHEemCrVzYq-4W80_BIJj6uCsepqCoN15AhISxw-j6VJHjPQbs82SZomH7UUyZ2atkz9W1dBnd3T9tMdpTdXpa4b62TEgQLChE8/s1600/Screenshot%202023-01-04%20at%2010.23.52%20AM.png)

## Full logs

If that doesn't show the cause of the error (as it sometimes gets truncated), you can download the full logs. Once again, in the portal for the App Service resource, find *Development tools* on the sidebar and select *Advanced tools*. 

When that website loads, find the Current Docker Logs link and select Download as zip next to it:

![Screenshot of Kudu website links](https://github.com/Azure-Samples/azure-search-openai-demo/assets/297042/b0546a64-ab5e-4fdc-bf47-7862d8bd8e53)

In the downloaded zip file, find the filename that starts with the most recent date and ends with "_default_docker.log":

![Screenshot of opened folder with log files](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiSqbwWWB-bLriZgZB5H7wvMdjUpxJVU5wgY2O6uHXN7wYQPCRzipjLoVXOx9_43ZOp8Y5gd3zslUVw8Z_0OKS4FVjHFg01kDDlKSqRSGBjTwa2MGHhsqDrBq1mt08Z7649cXPvftM0gefIhH6eh9SvSlQVnz4msAgeL-ccki3x8HFIsxqcuhWCm5I/s1600/Screenshot%202023-01-07%20at%2010.14.28%20AM.png)

Open that file to see the full logs, with the most recent logs at the bottom. There should hopefully be an obvious error causing the HTTP 500 in your screenshot.

**Comment by nlpmarc** [comment]
@pamelafox thanks for the hint with the log stream. I cleared my stream right before I opened the pdf in the app. I also got internal server error.


<img width="720" alt="Bildschirmfoto 2023-06-06 um 09 23 29" src="https://github.com/Azure-Samples/azure-search-openai-demo/assets/100695133/c7a6898f-b3e5-4879-ac54-f17ca67681ef">

log stream:

2023-06-06 07:19:14.843 +00:00 [Debug] Microsoft.AspNetCore.Server.Kestrel.Connections: Connection id "0HMR6BA9E8MFD" accepted.
2023-06-06 07:19:14.843 +00:00 [Debug] Microsoft.AspNetCore.Server.Kestrel.Connections: Connection id "0HMR6BA9E8MFD" started.
2023-06-06 07:19:14.843 +00:00 [Information] Microsoft.AspNetCore.Hosting.Diagnostics: Request starting HTTP/1.1 GET http://app-backend-azsqvlnkbegag.azurewebsites.net/ - -
2023-06-06 07:19:14.843 +00:00 [Trace] Middleware: Request came in on normal port, sending to normal target http://169.254.130.7:8000/
2023-06-06 07:19:14.843 +00:00 [Trace] Middleware: Forwarding request to http://169.254.130.7:8000/
2023-06-06 07:19:14.854 +00:00 [Trace] Middleware: Forwarded request finished in 11.059ms 200 OK
2023-06-06 07:19:14.856 +00:00 [Information] Microsoft.AspNetCore.Hosting.Diagnostics: Request finished HTTP/1.1 GET http://app-backend-azsqvlnkbegag.azurewebsites.net/ - - - 200 472 text/html;+charset=utf-8 12.8788ms
2023-06-06 07:19:14.856 +00:00 [Debug] Microsoft.AspNetCore.Server.Kestrel.Connections: Connection id "0HMR6BA9E8MFD" disconnecting.
2023-06-06 07:19:14.856 +00:00 [Debug] Microsoft.AspNetCore.Server.Kestrel.Connections: Connection id "0HMR6BA9E8MFD" stopped.
2023-06-06 07:19:14.862 +00:00 [Debug] Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets: Connection id "0HMR6BA9E8MFD" sending FIN because: "The Socket transport's send loop completed gracefully."
2023-06-06 07:19:15.058 +00:00 [Debug] Microsoft.AspNetCore.Server.Kestrel.Connections: Connection id "0HMR6BA9E8MFE" accepted.
2023-06-06 07:19:15.058 +00:00 [Debug] Microsoft.AspNetCore.Server.Kestrel.Connections: Connection id "0HMR6BA9E8MFE" started.
2023-06-06 07:19:15.078 +00:00 [Information] Microsoft.AspNetCore.Hosting.Diagnostics: Request starting HTTP/1.1 GET http://app-backend-azsqvlnkbegag.azurewebsites.net/content/GED - Elektroplus Kompakt Elektrische Schutzgeräte (2019-08)-1.pdf - -
2023-06-06 07:19:15.079 +00:00 [Trace] Middleware: Request came in on normal port, sending to normal target http://169.254.130.7:8000/content/GED%20-%20Elektroplus%20Kompakt%20Elektrische%20Schutzger%C3%A4te%20(2019-08)-1.pdf
2023-06-06 07:19:15.079 +00:00 [Trace] Middleware: Forwarding request to http://169.254.130.7:8000/content/GED - Elektroplus Kompakt Elektrische Schutzgeräte (2019-08)-1.pdf
2023-06-06 07:19:15.244 +00:00 [Trace] Middleware: Forwarded request finished in 165.777ms 200 INTERNAL SERVER ERROR
2023-06-06 07:19:15.255 +00:00 [Information] Microsoft.AspNetCore.Hosting.Diagnostics: Request finished HTTP/1.1 GET http://app-backend-azsqvlnkbegag.azurewebsites.net/content/GED - Elektroplus Kompakt Elektrische Schutzgeräte (2019-08)-1.pdf - - - 500 265 text/html;+charset=utf-8 176.1623ms
2023-06-06 07:19:15.255 +00:00 [Debug] Microsoft.AspNetCore.Server.Kestrel.Connections: Connection id "0HMR6BA9E8MFE" disconnecting.
2023-06-06 07:19:15.255 +00:00 [Debug] Microsoft.AspNetCore.Server.Kestrel.Connections: Connection id "0HMR6BA9E8MFE" stopped.
2023-06-06 07:19:15.256 +00:00 [Debug] Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets: Connection id "0HMR6BA9E8MFE" sending FIN because: "The Socket transport's send loop completed gracefully."

2023-06-06T07:19:14.863207730Z 169.254.130.8 - - [06/Jun/2023:07:19:14 +0000] "GET / HTTP/1.1" 200 0 "-" "AlwaysOn"
2023-06-06T07:19:15.236077286Z ERROR:app:Exception on /content/GED - Elektroplus Kompakt Elektrische Schutzgeräte (2019-08)-1.pdf [GET]
2023-06-06T07:19:15.236112986Z Traceback (most recent call last):
2023-06-06T07:19:15.236120886Z   File "/tmp/8db6659f698ac41/antenv/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
2023-06-06T07:19:15.236168487Z     response = self.full_dispatch_request()
2023-06-06T07:19:15.236174287Z   File "/tmp/8db6659f698ac41/antenv/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
2023-06-06T07:19:15.236179787Z     rv = self.handle_user_exception(e)
2023-06-06T07:19:15.236184887Z   File "/tmp/8db6659f698ac41/antenv/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-06-06T07:19:15.236190387Z     rv = self.dispatch_request()
2023-06-06T07:19:15.236195287Z   File "/tmp/8db6659f698ac41/antenv/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
2023-06-06T07:19:15.236200587Z     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-06-06T07:19:15.236216087Z   File "/tmp/8db6659f698ac41/app.py", line 78, in content_file
2023-06-06T07:19:15.236227087Z     blob = blob_container.get_blob_client(path).download_blob()
2023-06-06T07:19:15.236232287Z   File "/tmp/8db6659f698ac41/antenv/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 76, in wrapper_use_tracer
2023-06-06T07:19:15.236237487Z     return func(*args, **kwargs)
2023-06-06T07:19:15.236242387Z   File "/tmp/8db6659f698ac41/antenv/lib/python3.10/site-packages/azure/storage/blob/_blob_client.py", line 905, in download_blob
2023-06-06T07:19:15.236247587Z     return StorageStreamDownloader(**options)
2023-06-06T07:19:15.236252487Z   File "/tmp/8db6659f698ac41/antenv/lib/python3.10/site-packages/azure/storage/blob/_download.py", line 366, in __init__
2023-06-06T07:19:15.236257587Z     self._response = self._initial_request()
2023-06-06T07:19:15.236262387Z   File "/tmp/8db6659f698ac41/antenv/lib/python3.10/site-packages/azure/storage/blob/_download.py", line 466, in _initial_request
2023-06-06T07:19:15.236267587Z     process_storage_error(error)
2023-06-06T07:19:15.236272487Z   File "/tmp/8db6659f698ac41/antenv/lib/python3.10/site-packages/azure/storage/blob/_shared/response_handlers.py", line 185, in process_storage_error
2023-06-06T07:19:15.236277588Z     exec("raise error from None")   # pylint: disable=exec-used # nosec
2023-06-06T07:19:15.236282588Z   File "<string>", line 1, in <module>
2023-06-06T07:19:15.236288188Z   File "/tmp/8db6659f698ac41/antenv/lib/python3.10/site-packages/azure/storage/blob/_download.py", line 418, in _initial_request
2023-06-06T07:19:15.236293388Z     location_mode, response = self._clients.blob.download(
2023-06-06T07:19:15.236299388Z   File "/tmp/8db6659f698ac41/antenv/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 76, in wrapper_use_tracer
2023-06-06T07:19:15.236304488Z     return func(*args, **kwargs)
2023-06-06T07:19:15.236309288Z   File "/tmp/8db6659f698ac41/antenv/lib/python3.10/site-packages/azure/storage/blob/_generated/operations/_blob_operations.py", line 1599, in download
2023-06-06T07:19:15.236314388Z     map_error(status_code=response.status_code, response=response, error_map=error_map)
2023-06-06T07:19:15.236319388Z   File "/tmp/8db6659f698ac41/antenv/lib/python3.10/site-packages/azure/core/exceptions.py", line 109, in map_error
2023-06-06T07:19:15.236324388Z     raise error
2023-06-06T07:19:15.236329288Z azure.core.exceptions.ResourceNotFoundError: The specified blob does not exist.
2023-06-06T07:19:15.236334188Z RequestId:2a731680-601e-0048-3b47-980371000000
2023-06-06T07:19:15.236338988Z Time:2023-06-06T07:19:15.2083499Z
2023-06-06T07:19:15.236343788Z ErrorCode:BlobNotFound
2023-06-06T07:19:15.236348488Z Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
2023-06-06T07:19:15.236354288Z RequestId:2a731680-601e-0048-3b47-980371000000
2023-06-06T07:19:15.236364188Z Time:2023-06-06T07:19:15.2083499Z</Message></Error>
2023-06-06T07:19:15.254465856Z 169.254.130.8 - - [06/Jun/2023:07:19:15 +0000] "GET /content/GED%20-%20Elektroplus%20Kompakt%20Elektrische%20Schutzger%C3%A4te%20(2019-08)-1.pdf HTTP/1.1" 500 265 "https://app-backend-azsqvlnkbegag.azurewebsites.net/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5 Safari/605.1.15"

**Comment by pamelafox** [comment]
Okay, so we see there's a BlobNotFound error when hitting up this URL:
http://app-backend-azsqvlnkbegag.azurewebsites.net/content/GED - Elektroplus Kompakt Elektrische Schutzgeräte (2019-08)-1.pdf

I would suggest going into Azure Portal, into the Storage account, selecting Containers, selecting the 'content' container, and confirming you can actually see that filename exists.
Assuming so, then my speculative guess would be an issue with either the whitespace in the filename or the non-ASCII character (ä). I just did a test with a filename that had whitespace and it was alright, so my next guess would be the ä isn't being handled corectly.

**Comment by pamelafox** [comment]
I have replicated the issue with ä. I have an idea that might fix it (in app.py, in content_file function), will report back tomorrow.

**Comment by pamelafox** [comment]
You can see my proposed fix in https://github.com/Azure-Samples/azure-search-openai-demo/pull/283

**Comment by nlpmarc** [comment]
@pamelafox awesome, yes now it works! thanks so much for your instant help!

**Comment by phfontes** [comment]
@pamelafox Hello, thanks for the feedback.
I checked and did the tests, I believe that characters like ã also apply to the file content.
My file had bullet points, arrows and some formatting. I left only title and body text and the problem stopped

**Comment by Ehsan-Shams-Davodly** [comment]
Most likely, the reason for this problem is the validation issue. So you can connect with azure storage container directly through connection string (alter to token).

```
@app.route("/content/<path>")
def content_file(path):
    connection_string = 'DefaultEndpointsProtocol=...'
    container_name = 'content'

    blob_service_client = BlobServiceClient.from_connection_string(connection_string)
    blob_container = blob_service_client.get_container_client(container_name)
    
    blob = blob_container.get_blob_client(path).download_blob()
    mime_type = blob.properties["content_settings"]["content_type"]
    if mime_type == "application/octet-stream":
        mime_type = mimetypes.guess_type(path)[0] or "application/octet-stream"
    return blob.readall(), 200, {"Content-Type": mime_type, "Content-Disposition": f"inline; filename={path}"}
```
