### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: app/frontend/node_modules/vite/bin/vite.js

### ISSUE THREAD

**Issue by jimmyliao** [Azure-Samples/azure-search-openai-demo#31]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [V] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> azd up

### Any log messages given by the failure
>

> frontend@0.0.0 build <skip>/azure-search-openai-demo/app/frontend
> tsc && vite build

internal/modules/cjs/loader.js:1174
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: <skip>/azure-search-openai-demo/app/frontend/node_modules/vite/bin/vite.js
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1174:13)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'ERR_REQUIRE_ESM'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frontend@0.0.0 build: `tsc && vite build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the frontend@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     <skip>/.npm/_logs/2023-03-20T04_37_36_756Z-debug.log

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

macOS (13.2.1) with Powershell 7.3.3 or zsh

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by chuwik** [comment]
Could you please share the version of node and npm you're using?

You can find out running
```
node -v
npm -v
```

**Comment by jimmyliao** [comment]
it's node 12.x, upgrade to 18.x and resolved.
