### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED by running azd up or pwsh .\scripts\prepdocs.ps1

### ISSUE THREAD

**Issue by ayoubazaouyat** [Azure-Samples/azure-search-openai-demo#317]
> Please provide us with the following information:
by running `azd up` or `pwsh .\scripts\prepdocs.ps1` it says that there is an error with the certificate. I did try solutions in other issues. I did add owner to the ressource group but it still the same.
`Running "prepdocs.py"
Ensuring search index gptkbindex exists
Traceback (most recent call last):
  File "E:\Projects\sunrise\git\test\scripts\prepdocs.py", line 299, in <module>
    create_search_index()
  File "E:\Projects\sunrise\git\test\scripts\prepdocs.py", line 237, in create_search_index
    if args.index not in index_client.list_index_names():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\sunrise\git\test\scripts\.venv\Lib\site-packages\azure\core\paging.py", line 124, in __next__
    return next(self._page_iterator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\sunrise\git\test\scripts\.venv\Lib\site-packages\azure\core\paging.py", line 76, in __next__
    self._response = self._get_next(self.continuation_token)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\sunrise\git\test\scripts\.venv\Lib\site-packages\azure\search\documents\indexes\_generated\operations\_indexes_operations.py", line 512, in get_next
    pipeline_response = self._client._pipeline.run(  # type: ignore # pylint: disable=protected-access
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\sunrise\git\test\scripts\.venv\Lib\site-packages\azure\core\pipeline\_base.py", line 202, in run
    return first_node.send(pipeline_request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\sunrise\git\test\scripts\.venv\Lib\site-packages\azure\core\pipeline\_base.py", line 70, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\sunrise\git\test\scripts\.venv\Lib\site-packages\azure\core\pipeline\_base.py", line 70, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\sunrise\git\test\scripts\.venv\Lib\site-packages\azure\core\pipeline\_base.py", line 70, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 2 more times]
  File "E:\Projects\sunrise\git\test\scripts\.venv\Lib\site-packages\azure\core\pipeline\policies\_redirect.py", line 156, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\sunrise\git\test\scripts\.venv\Lib\site-packages\azure\core\pipeline\policies\_retry.py", line 470, in send
    raise err
  File "E:\Projects\sunrise\git\test\scripts\.venv\Lib\site-packages\azure\core\pipeline\policies\_retry.py", line 448, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\sunrise\git\test\scripts\.venv\Lib\site-packages\azure\core\pipeline\policies\_authentication.py", line 113, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\sunrise\git\test\scripts\.venv\Lib\site-packages\azure\core\pipeline\_base.py", line 70, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\sunrise\git\test\scripts\.venv\Lib\site-packages\azure\core\pipeline\_base.py", line 70, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\sunrise\git\test\scripts\.venv\Lib\site-packages\azure\core\pipeline\_base.py", line 70, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 1 more time]
  File "E:\Projects\sunrise\git\test\scripts\.venv\Lib\site-packages\azure\core\pipeline\_base.py", line 101, in send
    self._sender.send(request.http_request, **request.context.options),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\sunrise\git\test\scripts\.venv\Lib\site-packages\azure\core\pipeline\transport\_requests_basic.py", line 364, in send
    raise error
azure.core.exceptions.ServiceRequestError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1002)`
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Run `azd up` command

### Any log messages given by the failure
>`Running "prepdocs.py"
Ensuring search index gptkbindex exists
Traceback (most recent call last):
  File "E:\Projects\sunrise\git\test\scripts\prepdocs.py", line 299, in <module>
    create_search_index()
  File "E:\Projects\sunrise\git\test\scripts\prepdocs.py", line 237, in create_search_index
    if args.index not in index_client.list_index_names():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\sunrise\git\test\scripts\.venv\Lib\site-packages\azure\core\paging.py", line 124, in __next__
    return next(self._page_iterator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\sunrise\git\test\scripts\.venv\Lib\site-packages\azure\core\paging.py", line 76, in __next__
    self._response = self._get_next(self.continuation_token)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\sunrise\git\test\scripts\.venv\Lib\site-packages\azure\search\documents\indexes\_generated\operations\_indexes_operations.py", line 512, in get_next
    pipeline_response = self._client._pipeline.run(  # type: ignore # pylint: disable=protected-access
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\sunrise\git\test\scripts\.venv\Lib\site-packages\azure\core\pipeline\_base.py", line 202, in run
    return first_node.send(pipeline_request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\sunrise\git\test\scripts\.venv\Lib\site-packages\azure\core\pipeline\_base.py", line 70, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\sunrise\git\test\scripts\.venv\Lib\site-packages\azure\core\pipeline\_base.py", line 70, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\sunrise\git\test\scripts\.venv\Lib\site-packages\azure\core\pipeline\_base.py", line 70, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 2 more times]
  File "E:\Projects\sunrise\git\test\scripts\.venv\Lib\site-packages\azure\core\pipeline\policies\_redirect.py", line 156, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\sunrise\git\test\scripts\.venv\Lib\site-packages\azure\core\pipeline\policies\_retry.py", line 470, in send
    raise err
  File "E:\Projects\sunrise\git\test\scripts\.venv\Lib\site-packages\azure\core\pipeline\policies\_retry.py", line 448, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\sunrise\git\test\scripts\.venv\Lib\site-packages\azure\core\pipeline\policies\_authentication.py", line 113, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\sunrise\git\test\scripts\.venv\Lib\site-packages\azure\core\pipeline\_base.py", line 70, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\sunrise\git\test\scripts\.venv\Lib\site-packages\azure\core\pipeline\_base.py", line 70, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\sunrise\git\test\scripts\.venv\Lib\site-packages\azure\core\pipeline\_base.py", line 70, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 1 more time]
  File "E:\Projects\sunrise\git\test\scripts\.venv\Lib\site-packages\azure\core\pipeline\_base.py", line 101, in send
    self._sender.send(request.http_request, **request.context.options),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\sunrise\git\test\scripts\.venv\Lib\site-packages\azure\core\pipeline\transport\_requests_basic.py", line 364, in send
    raise error
azure.core.exceptions.ServiceRequestError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1002)`

### Expected/desired behavior
> Index creation and App working

### OS and Version?
> Windows 10

### azd version?
> run `azd version` and copy paste here.
azd version 1.0.2 
### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by PhysicsRJB** [comment]
I'm experiencing the exact same issue.

**Comment by FreddyStraub** [comment]
Same here, any solution? Is there a way to ignore it for testing?

**Comment by shulkx** [comment]
It seems that the error occurs due to the unstable of the connection.
I introduced the mechanism of retrying inside the `prepdocs.py` and works fine for now. When the certificate verify failed, it will pass in the second trial.
Here is what I have modified. `args.start_index` is set once the progress is shut down, I can continue the progress from specific index.

```python
def process_file(filename):
    if args.verbose: print(f"Processing '{filename}'")
    if args.remove:
        remove_blobs(filename)
        remove_from_index(filename)
    elif args.removeall:
        remove_blobs(None)
        remove_from_index(None)
    else:
        if not args.skipblobs:
            upload_blobs(filename)
        print(f"Processing '{filename}'")
        page_map = get_document_text(filename)
        sections = create_sections(os.path.basename(filename), page_map)
        index_sections(os.path.basename(filename), sections)

if args.removeall:
    remove_blobs(None)
    remove_from_index(None)
else:
    if not args.remove:
        create_search_index()
    
    print(f"Processing files...")
    # Recursively find all files in the directory
    filenames = glob.glob(args.files, recursive=True)

    # Filter out directories
    filenames = [f for f in filenames if os.path.isfile(f)]

    # Maximum number of retry attempts
    max_retry_attempts = 3
    args.start_index = 0

    start_index = args.start_index if hasattr(args, 'start_index') and args.start_index < len(filenames) else 0

    for i in tqdm.tqdm(range(start_index, len(filenames)), desc="Processing files", unit="file"):
        filename = filenames[i]
        if os.path.isfile(filename):
            retry_attempts = 0
            while retry_attempts < max_retry_attempts:
                try:
                    process_file(filename)
                    break  # Break the while loop if processing was successful
                except Exception as e:
                    print(f"Error processing file {filename}. Error: {str(e)}. Attempt {retry_attempts+1} of {max_retry_attempts}")
                    retry_attempts += 1
```
