### ISSUE TITLE
:( Application Error 　Cannot open the application.

### ISSUE THREAD

**Issue by ikka86** [Azure-Samples/azure-search-openai-demo#441]
:( Application Error
If you are the application administrator, you can access the [diagnostic resources]

Application Log
Application log contains errors or warnings

HTTP Server Errors
HTTP 5XX request detected

**Comment by pamelafox** [comment]
We cannot help you without more details. Please read this post for tips on finding helpful logs: http://blog.pamelafox.org/2023/06/tips-for-debugging-flask-deployments-to.html

**Comment by ikka86** [comment]
The following logs were retrieved from the log stream
This is the log when you try to launch the application.


2023-07-20T05:42:54.011Z ERROR - Container app-backend-lh2xkyvjajxzw_0_990d450a for site app-backend-lh2xkyvjajxzw did not start within expected time limit. Elapsed time = 234.8325185 sec
2023-07-20T05:42:54.015Z INFO  - Initiating warmup request to container app-backend-lh2xkyvjajxzw_0_990d450a_middleware for site app-backend-lh2xkyvjajxzw
2023-07-20 05:42:54.084 +00:00 [Debug] Microsoft.AspNetCore.Server.Kestrel.Connections: Connection id "0HMS8SGKV5G2M" accepted.
2023-07-20 05:42:54.091 +00:00 [Debug] Microsoft.AspNetCore.Server.Kestrel.Connections: Connection id "0HMS8SGKV5G2M" started.
2023-07-20 05:42:54.240 +00:00 [Information] Microsoft.AspNetCore.Hosting.Diagnostics: Request starting HTTP/1.1 GET http://169.254.130.30:8181/robots933456.txt - -
2023-07-20 05:42:54.352 +00:00 [Trace] Middleware: Request came in on normal port, sending to normal target http://169.254.130.28:8000/robots933456.txt
2023-07-20 05:42:54.352 +00:00 [Trace] Middleware: Forwarding request to http://169.254.130.28:8000/robots933456.txt
2023-07-20T05:43:25.454Z ERROR - Container app-backend-lh2xkyvjajxzw_0_990d450a_middleware for site app-backend-lh2xkyvjajxzw did not start within expected time limit. Elapsed time = 266.2756081 sec
2023-07-20T05:43:25.565Z ERROR - Container app-backend-lh2xkyvjajxzw_0_990d450a didn't respond to HTTP pings on port: 8000, failing site start. See container logs for debugging.
2023-07-20T05:39:04.590231099Z Updated CA certificates
2023-07-20 05:43:24.434 +00:00 [Debug] Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets: Connection id "0HMS8SGKV5G2M" received FIN.
2023-07-20 05:43:24.439 +00:00 [Debug] Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets: Connection id "0HMS8SGKV5G2M" sending FIN because: "The client closed the connection."
2023-07-20 05:43:24.467 +00:00 [Debug] Microsoft.AspNetCore.Server.Kestrel.Connections: Connection id "0HMS8SGKV5G2M" disconnecting.
2023-07-20T05:43:30.448Z INFO  - Stopping site app-backend-lh2xkyvjajxzw because it failed during startup.

**Comment by pamelafox** [comment]
Hm, I wonder if there are some logs from inside the container. Can you use "Advanced Tools" to download all the logs, and find the "default_docker" logs in the zip?

**Comment by ikka86** [comment]
[default_docker.txt](https://github.com/Azure-Samples/azure-search-openai-demo/files/12105138/default_docker.txt)
Thanks.
Default log attached.

**Comment by pamelafox** [comment]
Okay great. According to those logs, the most recent error is:

```
2023-07-20T10:38:52.600786727Z [2023-07-20 10:38:52 +0000] [70] [ERROR] Exception in worker process
2023-07-20T10:38:52.600822728Z Traceback (most recent call last):
2023-07-20T10:38:52.600830828Z   File "/opt/python/3.10.11/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
2023-07-20T10:38:52.600855128Z     worker.init_process()
2023-07-20T10:38:52.600861429Z   File "/opt/python/3.10.11/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
2023-07-20T10:38:52.650774411Z     self.load_wsgi()
2023-07-20T10:38:52.650835513Z   File "/opt/python/3.10.11/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
2023-07-20T10:38:52.650845413Z     self.wsgi = self.app.wsgi()
2023-07-20T10:38:52.650852613Z   File "/opt/python/3.10.11/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
2023-07-20T10:38:52.650859913Z     self.callable = self.load()
2023-07-20T10:38:52.650866813Z   File "/opt/python/3.10.11/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
2023-07-20T10:38:52.650873914Z     return self.load_wsgiapp()
2023-07-20T10:38:52.650880614Z   File "/opt/python/3.10.11/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
2023-07-20T10:38:52.650887514Z     return util.import_app(self.app_uri)
2023-07-20T10:38:52.650894314Z   File "/opt/python/3.10.11/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
2023-07-20T10:38:52.650901214Z     mod = importlib.import_module(module)
2023-07-20T10:38:52.650907814Z   File "/opt/python/3.10.11/lib/python3.10/importlib/__init__.py", line 126, in import_module
2023-07-20T10:38:52.650914715Z     return _bootstrap._gcd_import(name[level:], package, level)
2023-07-20T10:38:52.650921415Z   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
2023-07-20T10:38:52.650928615Z   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2023-07-20T10:38:52.650935615Z   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
2023-07-20T10:38:52.650942515Z   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2023-07-20T10:38:52.650950215Z   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2023-07-20T10:38:52.650957316Z   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2023-07-20T10:38:52.650964216Z   File "/tmp/8db88fe35f3c642/app.py", line 17, in <module>
2023-07-20T10:38:52.650970816Z     from approaches.chatreadretrieveread import ChatReadRetrieveReadApproach
2023-07-20T10:38:52.650977416Z   File "/tmp/8db88fe35f3c642/approaches/chatreadretrieveread.py", line 18
2023-07-20T10:38:52.650984216Z     """
2023-07-20T10:38:52.650990916Z IndentationError: unexpected indent
```

**Comment by ikka86** [comment]
thanks!
Is it because Python is 3.9?
By the way, I fixed the indentation.

**Comment by pamelafox** [comment]
Is there another error now that you've fixed the indentation? Re-deploy, download the logs, open the default docker file, scroll down to see the latest error message. Post here if you don't understand that message.

**Comment by ikka86** [comment]
[default_docker (2).txt](https://github.com/Azure-Samples/azure-search-openai-demo/files/12117375/default_docker.2.txt)
I have attached. thank you

**Comment by ikka86** [comment]
[chatreadretrieveread.txt](https://github.com/Azure-Samples/azure-search-openai-demo/files/12117717/chatreadretrieveread.txt)
chatreadretrieveread is here

**Comment by pamelafox** [comment]
@ikka86 It looks like there is another indentation error. Generally, you should fix syntax errors locally. The errors that happen on production are typically related to incorrect environment variable configuration. I recommend running the local server per the README instructions, fixing all the issues locally, and then deploying to production.

**Comment by pamelafox** [comment]
Closing since we haven't heard back, and the errors seemed resolvable.
