### ISSUE TITLE
ResourceNotFoundError: The specified blob does not exist.

### ISSUE THREAD

**Issue by GGSeven** [Azure-Samples/azure-search-openai-demo#456]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>always

### Any log messages given by the failure
>ResourceNotFoundError
azure.core.exceptions.ResourceNotFoundError: The specified blob does not exist.
RequestId:8b87720e-801e-0019-32a5-be3731000000
Time:2023-07-25T03:12:27.5090028Z
ErrorCode:BlobNotFound
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
RequestId:8b87720e-801e-0019-32a5-be3731000000
Time:2023-07-25T03:12:27.5090028Z</Message></Error>

Traceback (most recent call last)
File "/workspaces/azure-search-openai-demo/app/backend/backend_env/lib/python3.10/site-packages/flask/app.py", line 2552, in __call__
return self.wsgi_app(environ, start_response)
File "/workspaces/azure-search-openai-demo/app/backend/backend_env/lib/python3.10/site-packages/flask/app.py", line 2532, in wsgi_app
response = self.handle_exception(e)
File "/workspaces/azure-search-openai-demo/app/backend/backend_env/lib/python3.10/site-packages/flask/app.py", line 2529, in wsgi_app
response = self.full_dispatch_request()
File "/workspaces/azure-search-openai-demo/app/backend/backend_env/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/workspaces/azure-search-openai-demo/app/backend/backend_env/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
rv = self.dispatch_request()
File "/workspaces/azure-search-openai-demo/app/backend/backend_env/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
File "/workspaces/azure-search-openai-demo/app/backend/app.py", line 86, in content_file
blob = blob_container.get_blob_client(path).download_blob()
File "/workspaces/azure-search-openai-demo/app/backend/backend_env/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 76, in wrapper_use_tracer
return func(*args, **kwargs)
File "/workspaces/azure-search-openai-demo/app/backend/backend_env/lib/python3.10/site-packages/azure/storage/blob/_blob_client.py", line 905, in download_blob
return StorageStreamDownloader(**options)
File "/workspaces/azure-search-openai-demo/app/backend/backend_env/lib/python3.10/site-packages/azure/storage/blob/_download.py", line 366, in __init__
self._response = self._initial_request()
File "/workspaces/azure-search-openai-demo/app/backend/backend_env/lib/python3.10/site-packages/azure/storage/blob/_download.py", line 466, in _initial_request
process_storage_error(error)
File "/workspaces/azure-search-openai-demo/app/backend/backend_env/lib/python3.10/site-packages/azure/storage/blob/_shared/response_handlers.py", line 185, in process_storage_error
exec("raise error from None")   # pylint: disable=exec-used # nosec
File "<string>", line 1, in <module>
File "/workspaces/azure-search-openai-demo/app/backend/backend_env/lib/python3.10/site-packages/azure/storage/blob/_download.py", line 418, in _initial_request
location_mode, response = self._clients.blob.download(
File "/workspaces/azure-search-openai-demo/app/backend/backend_env/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 76, in wrapper_use_tracer
return func(*args, **kwargs)
File "/workspaces/azure-search-openai-demo/app/backend/backend_env/lib/python3.10/site-packages/azure/storage/blob/_generated/operations/_blob_operations.py", line 1599, in download
map_error(status_code=response.status_code, response=response, error_map=error_map)
File "/workspaces/azure-search-openai-demo/app/backend/backend_env/lib/python3.10/site-packages/azure/core/exceptions.py", line 112, in map_error
raise error
azure.core.exceptions.ResourceNotFoundError: The specified blob does not exist.
RequestId:8b87720e-801e-0019-32a5-be3731000000
Time:2023-07-25T03:12:27.5090028Z
ErrorCode:BlobNotFound
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
RequestId:8b87720e-801e-0019-32a5-be3731000000
Time:2023-07-25T03:12:27.5090028Z</Message></Error>
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object
Brought to you by DON'T PANIC, your friendly Werkzeug powered traceback interpreter.

### Expected/desired behavior
>Successfully displayed the reference source

### OS and Version?
> github codespace

### azd version?
> run `azd version` and copy paste here.

### Versions
>azd version 1.1.0 (commit ea9cb12575734ee6a5f99c4d415c1a51d6f32d3e)

### Mention any other details that might be useful

The citation source still shows this error on Microsoft's official website

![image](https://github.com/Azure-Samples/azure-search-openai-demo/assets/66481676/b6bf4152-1be3-4207-867c-f5329ccf26cc)

And I cannot display the reference when adding a PDF file under the data folder
![image](https://github.com/Azure-Samples/azure-search-openai-demo/assets/66481676/147ecda9-910d-459a-b44c-172e48463104)
![image](https://github.com/Azure-Samples/azure-search-openai-demo/assets/66481676/866d6e8b-b613-4165-923a-c9237c185a1d)

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
This looks like a language-related issue. What is the name of the file that it's trying to load? I see the UI displays non-Latin characters, is that the filename? (Typically it is, but I don't see non-latin filenames in your data/ folder)

**Comment by GGSeven** [comment]
> 这看起来像是与语言相关的问题。它尝试加载的文件的名称是什么？我看到 UI 显示非拉丁字符，这是文件名吗？（通常是这样，但我在您的数据/文件夹中看不到非拉丁文件名）
The file name is 2021e-book.pdf

**Comment by GGSeven** [comment]
I have modified the prompt of the application to always answer enterprise related questions in Chinese
