### ISSUE TITLE
Error on doc upload in Blob Storage

### ISSUE THREAD

**Issue by macalb69** [Azure-Samples/azure-search-openai-demo#46]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [X] regression (a behavior that used to work and stopped in a new release)
```

### Any log messages given by the failure

In the final phase of document uploading I receive the following error logs:

Running "prepdocs.py"
Ensuring search index gptkbindex exists
Search index gptkbindex already exists
Processing files...
Processing 'C:\OpenAITEST02/data\Benefit_Options.pdf'
        Uploading blob for page 0 -> Benefit_Options-0.pdf
Traceback (most recent call last):
  File "C:\OpenAITEST02\scripts\prepdocs.py", line 225, in <module>
    upload_blobs(pages)
  File "C:\OpenAITEST02\scripts\prepdocs.py", line 61, in upload_blobs
    blob_container.upload_blob(blob_name, f, overwrite=True)
  File "C:\OpenAITEST02\scripts\.venv\Lib\site-packages\azure\core\tracing\decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\OpenAITEST02\scripts\.venv\Lib\site-packages\azure\storage\blob\_container_client.py", line 1038, in upload_blob
    blob.upload_blob(
  File "C:\OpenAITEST02\scripts\.venv\Lib\site-packages\azure\core\tracing\decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\OpenAITEST02\scripts\.venv\Lib\site-packages\azure\storage\blob\_blob_client.py", line 742, in upload_blob
    return upload_block_blob(**options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OpenAITEST02\scripts\.venv\Lib\site-packages\azure\storage\blob\_upload_helpers.py", line 197, in upload_block_blob
    process_storage_error(error)
  File "C:\OpenAITEST02\scripts\.venv\Lib\site-packages\azure\storage\blob\_shared\response_handlers.py", line 185, in process_storage_error
    exec("raise error from None")   # pylint: disable=exec-used # nosec
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
azure.core.exceptions.HttpResponseError: This request is not authorized to perform this operation using this permission.
RequestId:6812ee97-601e-00eb-12e9-5cc898000000
Time:2023-03-22T18:10:59.8745023Z
ErrorCode:AuthorizationPermissionMismatch
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationPermissionMismatch</Code><Message>This request is not authorized to perform this operation using this permission.
RequestId:6812ee97-601e-00eb-12e9-5cc898000000
Time:2023-03-22T18:10:59.8745023Z</Message></Error>

### Expected/desired behavior
>

### OS and Version?
> Windows 11

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jongio** [comment]
Please run `azd provision --debug` and see if that tells you what failed.  Also look in the Azure portal for failed deployments.

**Comment by macalb69** [comment]
I've redeployed from a clean setup and worked now.

**Comment by macalb69** [comment]
solved , redeployng from a new clean repo
