### ISSUE TITLE
LLM is not working

### ISSUE THREAD

**Issue by timamay** [Azure-Samples/azure-search-openai-demo#492]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>Post deployment, I brought up the main web page and clicked on check deployment. Then I received an error message.

### Any log messages given by the failure
>Please check you have a deployment name dsa-text-ada-001 in your Azure OpenAI resource https://dsa-openaiservice-oai.openai.azure.com/.
If you are using an Instructions based deployment (text-davinci-003), please check you have an environment variable OPENAI_DEPLOYMENT_TYPE=Text or delete the environment variable OPENAI_DEPLOYMENT_TYPE.
If you are using a Chat based deployment (gpt-35-turbo or gpt-4-32k or gpt-4), please check you have an environment variable OPENAI_DEPLOYMENT_TYPE=Chat.
Then restart your application.

### Expected/desired behavior
>I did not expect any errors

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?) I am using Windows 10.

### azd version?
> run `azd version` and copy paste here. I am not using azd. As far as I know, I do not have any program that supports that command.

### Versions
>

### Mention any other details that might be useful
I also received this error right after the one above.

Traceback (most recent call last): File "/usr/local/src/myscripts/OpenAI_Queries.py", line 18, in check_deployment llm_helper.get_completion("Generate a joke!") File "/usr/local/src/myscripts/utilities/helper.py", line 227, in get_completion return self.llm(prompt) File "/usr/local/lib/python3.9/site-packages/langchain/llms/base.py", line 246, in call return self.generate([prompt], stop=stop).generations[0][0].text File "/usr/local/lib/python3.9/site-packages/langchain/llms/base.py", line 140, in generate raise e File "/usr/local/lib/python3.9/site-packages/langchain/llms/base.py", line 137, in generate output = self._generate(prompts, stop=stop) File "/usr/local/lib/python3.9/site-packages/langchain/llms/openai.py", line 292, in _generate response = completion_with_retry(self, prompt=_prompts, **params) File "/usr/local/lib/python3.9/site-packages/langchain/llms/openai.py", line 99, in completion_with_retry return _completion_with_retry(**kwargs) File "/usr/local/lib/python3.9/site-packages/tenacity/init.py", line 289, in wrapped_f return self(f, *args, **kw) File "/usr/local/lib/python3.9/site-packages/tenacity/init.py", line 379, in call do = self.iter(retry_state=retry_state) File "/usr/local/lib/python3.9/site-packages/tenacity/init.py", line 314, in iter return fut.result() File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 439, in result return self.__get_result() File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result raise self._exception File "/usr/local/lib/python3.9/site-packages/tenacity/init.py", line 382, in call result = fn(*args, **kwargs) File "/usr/local/lib/python3.9/site-packages/langchain/llms/openai.py", line 97, in _completion_with_retry return llm.client.create(**kwargs) File "/usr/local/lib/python3.9/site-packages/openai/api_resources/completion.py", line 25, in create return super().create(*args, **kwargs) File "/usr/local/lib/python3.9/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create response, _, api_key = requestor.request( File "/usr/local/lib/python3.9/site-packages/openai/api_requestor.py", line 226, in request resp, got_stream = self._interpret_response(result, stream) File "/usr/local/lib/python3.9/site-packages/openai/api_requestor.py", line 619, in _interpret_response self._interpret_response_line( File "/usr/local/lib/python3.9/site-packages/openai/api_requestor.py", line 682, in _interpret_response_line raise self.handle_error_response( openai.error.InvalidRequestError: This model's maximum context length is 2049 tokens, however you requested 4097 tokens (5 in your prompt; 4092 for the completion). Please reduce your prompt; or completion length.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by timamay** [comment]
I agree that it's not part of the codebase, but I suspect it was installed when all the packages were installed per the requirements.txt file. I think it comes from streamlit but not sure.

Thanks,
Tim
________________________________

**Comment by pamelafox** [comment]
@timamay This repo also does not include streamlit. Based on your error description, I think you've actually deployed https://github.com/ruoccofabrizio/azure-open-ai-embeddings-qna
Please post an issue in their tracker. Thanks!
