### ISSUE TITLE
HttpResponse Error: Unknown field 'embedding' in vector fields list

### ISSUE THREAD

**Issue by pamelafox** [Azure-Samples/azure-search-openai-demo#501]
If you see this error pop up, that means that you initially ran this sample *before* we introduced vector search and you created a Cognitive search index that didn't have an 'embedding' field. This sample now presumes an index that has an 'embedding' field, so it errors when it sees a search index without one.

Two possible fixes:

* Delete your index entirely and re-run prepdocs.py
* Change the retrieval mode from Hybrid to Text in Chat.tsx, if you don't wish to use vectors:

```
const [retrievalMode, setRetrievalMode] = useState<RetrievalMode>(RetrievalMode.Text);
```

**Comment by pamelafox** [comment]
Full traceback of the error, to help anyone searching:

```
ERROR:root:Exception in /chat
Traceback (most recent call last):
  File "/tmp/8db94ab5bb43eb9/app.py", line 115, in chat
    r = impl.run(request.json["history"], request.json.get("overrides") or {})
  File "/tmp/8db94ab5bb43eb9/approaches/chatreadretrieveread.py", line 127, in run
    results = [doc[self.sourcepage_field] + ": " + nonewlines(doc[self.content_field]) for doc in r]
  File "/tmp/8db94ab5bb43eb9/approaches/chatreadretrieveread.py", line 127, in <listcomp>
    results = [doc[self.sourcepage_field] + ": " + nonewlines(doc[self.content_field]) for doc in r]
  File "/tmp/8db94ab5bb43eb9/antenv/lib/python3.10/site-packages/azure/search/documents/_paging.py", line 54, in __next__
    return next(self._page_iterator)
  File "/tmp/8db94ab5bb43eb9/antenv/lib/python3.10/site-packages/azure/core/paging.py", line 75, in __next__
    self._response = self._get_next(self.continuation_token)
  File "/tmp/8db94ab5bb43eb9/antenv/lib/python3.10/site-packages/azure/search/documents/_paging.py", line 124, in _get_next_cb
    return self._client.documents.search_post(search_request=self._initial_query.request, **self._kwargs)
  File "/tmp/8db94ab5bb43eb9/antenv/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 87, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/tmp/8db94ab5bb43eb9/antenv/lib/python3.10/site-packages/azure/search/documents/_generated/operations/_documents_operations.py", line 793, in search_post
    raise HttpResponseError(response=response, model=error)
azure.core.exceptions.HttpResponseError: () Unknown field 'embedding' in vector field list.
Parameter name: vectorFields
Code:
Message: Unknown field 'embedding' in vector field list.
Parameter name: vectorFields
```

**Comment by PatrickGallucci** [comment]
@pamelafox 

I just completed a deployment and I am getting this same error message.  Looking at [#501 ](https://github.com/Azure-Samples/azure-search-openai-demo/issues/501) you state "before we introduced vector search" Is this still an issue? I interpreteed that as I should not have to do this, that the prepdocs would create that field for me if needed. 

Here are the changes I made during deployment:

azd env set USE_MULTIMODAL true
azd env set AZURE_SEARCH_INDEX multimodal-index
azd env set USE_CHAT_HISTORY_BROWSER true
azd env set USE_SPEECH_INPUT_BROWSER true
azd env set USE_SPEECH_OUTPUT_AZURE true
azd env set AZURE_SPEECH_SERVICE_VOICE en-US-AndrewMultilingualNeural
azd env set USE_FEATURE_INT_VECTORIZATION true

What did I do wrong? :)

2025-10-18T00:20:07.9792450Z stderr F Code: InvalidRequestParameter
2025-10-18T00:20:07.9792473Z stderr F Message: Unknown field 'images/embedding' in vector field list.
2025-10-18T00:20:07.9792496Z stderr F Exception Details:        (UnknownField) Unknown field 'images/embedding' in vector field list.
2025-10-18T00:20:07.9792519Z stderr F   Code: UnknownField
2025-10-18T00:20:07.9792543Z stderr F   Message: Unknown field 'images/embedding' in vector field list.

**Comment by pamelafox** [comment]
USE_MULTIMODAL and USE_FEATURE_INT_VECTORIZATION are not yet compatible, so you'll need to pick one or the other. Then searchmanager.py should set up the right fields.
I am working a branch right now so that you can use cloud-based ingestion with multimodal support.
