### ISSUE TITLE
Error Starting Quart app

### ISSUE THREAD

**Issue by vrajroutu** [Azure-Samples/azure-search-openai-demo#514]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>
2023-08-08T23:01:46.830663438Z [2023-08-08 23:01:46 +0000] [74] [ERROR] Error handling request /
2023-08-08T23:01:46.830706739Z Traceback (most recent call last):
2023-08-08T23:01:46.830722939Z   File "/opt/python/3.10.12/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 136, in handle
2023-08-08T23:01:46.830728639Z     self.handle_request(listener, req, client, addr)
2023-08-08T23:01:46.830733639Z   File "/opt/python/3.10.12/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
2023-08-08T23:01:46.830738439Z     respiter = self.wsgi(environ, resp.start_response)
2023-08-08T23:01:46.830742940Z TypeError: Quart.__call__() missing 1 required positional argument: 'send'
2023-08-08T23:01:46.831298148Z 169.254.129.4 - - [08/Aug/2023:23:01:46 +0000] "GET / HTTP/1.1" 500 0 "-" "-"
2023-08-08T23:01:46.918181427Z [2023-08-08 23:01:46 +0000] [74] [ERROR] Error handling request /favicon.ico
2023-08-08T23:01:46.918252128Z Traceback (most recent call last):
2023-08-08T23:01:46.918269928Z   File "/opt/python/3.10.12/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 136, in handle
2023-08-08T23:01:46.918275028Z     self.handle_request(listener, req, client, addr)
2023-08-08T23:01:46.918288029Z   File "/opt/python/3.10.12/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
2023-08-08T23:01:46.918292729Z     respiter = self.wsgi(environ, resp.start_response)
2023-08-08T23:01:46.918297129Z TypeError: Quart.__call__() missing 1 required positional argument: 'send'
2023-08-08T23:01:46.918406430Z 169.254.129.4 - - [08/Aug/2023:23:01:46 +0000] "GET /favicon.ico HTTP/1.1" 500 0 "-" "-"
2023-08-08T23:01:47.612863849Z [2023-08-08 23:01:47 +0000] [74] [ERROR] Error handling request /
2023-08-08T23:01:47.612925550Z Traceback (most recent call last):
2023-08-08T23:01:47.612932150Z   File "/opt/python/3.10.12/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 136, in handle
2023-08-08T23:01:47.612937150Z     self.handle_request(listener, req, client, addr)
2023-08-08T23:01:47.612941750Z   File "/opt/python/3.10.12/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
2023-08-08T23:01:47.612946350Z     respiter = self.wsgi(environ, resp.start_response)
2023-08-08T23:01:47.612950650Z TypeError: Quart.__call__() missing 1 required positional argument: 'send'
### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Are you sure youre using the updated gunicorn with the uvicorn worker?
https://github.com/Azure-Samples/azure-search-openai-demo/pull/503/files#diff-e7fff831ef0c84776a6511fa49ebe811af957f6e1f84569b0db9cc6772bde9e9

**Comment by pamelafox** [comment]
Your app command line also changes: https://github.com/Azure-Samples/azure-search-openai-demo/pull/503/files#diff-7ef659fc9cf6968e718894d300490b14ea7a52091e7d4bcffae3a5029ac721d4

**Comment by vrajroutu** [comment]
@pamelafox 

After confirming that all changes were incorporated, I noticed in the app service logs post-deployment that the Gunicorn configuration file `(gunicorn.conf.py)` is either not being utilized or that the worker_class setting within the configuration file is being overridden by another source.

2023-08-08T23:13:52.676374385Z    _____  
2023-08-08T23:13:52.676403186Z   /  _  \ __________ _________   ____  
2023-08-08T23:13:52.676409086Z  /  /_\  \\___   /  |  \_  __ \_/ __ \  
2023-08-08T23:13:52.676414086Z /    |    \/    /|  |  /|  | \/\  ___/  
2023-08-08T23:13:52.676418086Z \____|__  /_____ \____/ |__|    \___  >  
2023-08-08T23:13:52.676422586Z         \/      \/                  \/  
2023-08-08T23:13:52.676426286Z A P P   S E R V I C E   O N   L I N U X  
2023-08-08T23:13:52.676430386Z  
2023-08-08T23:13:52.676434586Z Documentation: http://aka.ms/webapp-linux  
2023-08-08T23:13:52.676438786Z Python 3.10.12  
2023-08-08T23:13:52.676442686Z Note: Any data outside '/home' is not persisted  
2023-08-08T23:13:53.016365330Z Starting OpenBSD Secure Shell server: sshd.  
2023-08-08T23:13:53.052660080Z App Command Line not configured, will attempt auto-detect  
2023-08-08T23:13:53.181666532Z Starting periodic command scheduler: cron.  
2023-08-08T23:13:53.181693432Z Launching oryx with: create-script -appPath /home/site/wwwroot -output /opt/startup/startup.sh -virtualEnvName antenv -defaultApp /opt/defaultsite  
2023-08-08T23:13:53.230377869Z Found build manifest file at '/home/site/wwwroot/oryx-manifest.toml'. Deserializing it...  
2023-08-08T23:13:53.234944638Z Build Operation ID: 7f89ee35c68bd8a6  
2023-08-08T23:13:53.236403860Z Output is compressed. Extracting it...  
2023-08-08T23:13:53.236435861Z Oryx Version: 0.2.20230707.1, Commit: 0bd28e69919b5e8beba451e8677e3345f0be8361, ReleaseTagName: 20230707.1  
2023-08-08T23:13:53.270102170Z Extracting '/home/site/wwwroot/output.tar.gz' to directory '/tmp/8db9864f56c5268'...  
2023-08-08T23:13:57.940415244Z App path is set to '/tmp/8db9864f56c5268'  
2023-08-08T23:13:58.012349533Z Detected an app based on Flask  
2023-08-08T23:13:58.012940142Z Generating `gunicorn` command for 'app:app'  
2023-08-08T23:13:58.040936666Z Writing output script to '/opt/startup/startup.sh'  
2023-08-08T23:13:58.154743288Z Using packages from virtual environment antenv located at /tmp/8db9864f56c5268/antenv.  
2023-08-08T23:13:58.154801089Z Updated PYTHONPATH to '/opt/startup/app_logs:/tmp/8db9864f56c5268/antenv/lib/python3.10/site-packages'  
2023-08-08T23:13:58.623732184Z [2023-08-08 23:13:58 +0000] [68] [INFO] Starting gunicorn 20.1.0  
2023-08-08T23:13:58.638439107Z [2023-08-08 23:13:58 +0000] [68] [INFO] Listening at: http://0.0.0.0:8000 (68)  
2023-08-08T23:13:58.638495308Z [2023-08-08 23:13:58 +0000] [68] [INFO] Using worker: sync  
2023-08-08T23:13:58.646227325Z [2023-08-08 23:13:58 +0000] [71] [INFO] Booting worker with pid: 71  
2023-08-08T23:14:03.825426154Z DEBUG:appServiceAppLogs:Waiting for the logs flag to be set  
2023-08-08T23:14:03.834954298Z INFO:appsvc_profiler.installer:Code Profiler Installer is starting up  
2023-08-08T23:14:03.836407720Z INFO:appsvc_profiler.installer:Cleaning up any existing status file which indicated signal handlers initialized status  
2023-08-08T23:14:03.842232508Z INFO:appsvc_profiler.installer:Attempting to delete the signal_handler status file for instance id a778cf73a5f4dede3c3ce2cf5dcb304d45fc7aeee2d76  
2023-08-08T23:14:03.844848148Z INFO:appsvc_profiler.installer:successfully deleted the status file  
2023-08-08T23:14:03.848552504Z DEBUG:appsvc_profiler.installer:APPSETTING_WEBSITE_ENABLE_DEFAULT_CODE_PROFILER : None  
2023-08-08T23:14:03.881929210Z INFO:appsvc_profiler.installer:Attempting to install the default code profiler.  
2023-08-08T23:14:03.883868639Z DEBUG:appsvc_profiler.installer:viztracer would save traces to /tmp/a778cf_profiler_trace.json  
2023-08-08T23:14:03.885418862Z INFO:appsvc_profiler.installer:Successfully installed code profiler.  
2023-08-08T23:14:03.902811626Z INFO:appsvc_profiler.installer:Signal Handlers SIGUSR for needed code-profiler have been initialized for gunicorn process on instance a778cf73a5f42c3cc3rcrc3cb24f298e9c804d45fc7aeee2d76  
2023-08-08T23:14:03.904034044Z DEBUG:appsvc_profiler.installer:Code Profiler Installer is exiting as installation is completed  
2023-08-08T23:14:03.908475412Z [2023-08-08 23:14:03 +0000] [71] [ERROR] Error handling request /robots933456.txt  
2023-08-08T23:14:03.908500212Z Traceback (most recent call last):  
2023-08-08T23:14:03.908506912Z   File "/opt/python/3.10.12/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 136, in handle  
2023-08-08T23:14:03.908511912Z     self.handle_request(listener, req, client, addr)  
2023-08-08T23:14:03.908517112Z   File "/opt/python/3.10.12/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 179, in handle_request  
2023-08-08T23:14:03.908560413Z     respiter = self.wsgi(environ, resp.start_response)  
2023-08-08T23:14:03.908565213Z TypeError: Quart.__call__() missing 1 required positional argument: 'send'  
2023-08-08T23:14:03.910167237Z 169.254.129.1 - - [08/Aug/2023:23:14:03 +0000] "GET /robots933456.txt HTTP/1.1" 500 0 "-" "-"

**Comment by pamelafox** [comment]
That looks like it's not using the override startup command line, can you double check what configuration shows in the Portal?

It should look like:

<img width="891" alt="Screenshot 2023-08-08 at 4 30 35 PM" src="https://github.com/Azure-Samples/azure-search-openai-demo/assets/297042/a89b6dd9-facc-478b-8aa4-e778a71df3b1">

**Comment by vrajroutu** [comment]
@pamelafox Yes, you're correct. Somehow, the `azd deploy` isn't updating the startup command configuration in the Azure Web App. I had to manually input the command, and that resolved the issue.

Thanks

**Comment by pamelafox** [comment]
azd deploy only deploys a new zip, it does not change configuration settings. You must either azd up or azd provision to update any Bicep changes.

**Comment by pamelafox** [comment]
Closing this issue as it's resolved.
