### ISSUE TITLE
GPT4 - The API deployment for this resource does not exist.

### ISSUE THREAD

**Issue by nickroseth** [Azure-Samples/azure-search-openai-demo#526]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
Previously worked
Changed to using gpt-4
Occurs when doing original azd up or running prepdocs. 

### Any log messages given by the failure
>
Traceback (most recent call last):
  File "/workspaces/azure-search-openai-demo/scripts/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "/workspaces/azure-search-openai-demo/./scripts/prepdocs.py", line 216, in compute_embedding
    return openai.Embedding.create(engine=args.openaideployment, input=text)["data"][0]["embedding"]
  File "/workspaces/azure-search-openai-demo/scripts/.venv/lib/python3.10/site-packages/openai/api_resources/embedding.py", line 33, in create
    response = super().create(*args, **kwargs)
  File "/workspaces/azure-search-openai-demo/scripts/.venv/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/workspaces/azure-search-openai-demo/scripts/.venv/lib/python3.10/site-packages/openai/api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/workspaces/azure-search-openai-demo/scripts/.venv/lib/python3.10/site-packages/openai/api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "/workspaces/azure-search-openai-demo/scripts/.venv/lib/python3.10/site-packages/openai/api_requestor.py", line 763, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspaces/azure-search-openai-demo/./scripts/prepdocs.py", line 367, in <module>
    index_sections(os.path.basename(filename), sections)
  File "/workspaces/azure-search-openai-demo/./scripts/prepdocs.py", line 262, in index_sections
    for s in sections:
  File "/workspaces/azure-search-openai-demo/./scripts/prepdocs.py", line 208, in create_sections
    section["embedding"] = compute_embedding(content)
  File "/workspaces/azure-search-openai-demo/scripts/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "/workspaces/azure-search-openai-demo/scripts/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "/workspaces/azure-search-openai-demo/scripts/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x7f5ebb9e8df0 state=finished raised InvalidRequestError>]

### Expected/desired behavior
>
Normal Functionality
OpenAi resource is active with model named gpt-4 

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.
azd version 1.1.0 (commit ea9cb12575734ee6a5f99c4d415c1a51d6f32d3e)

### Versions
>

### Mention any other details that might be useful
Front end app and all other resources deploy successfully. 

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
I fixed some bugs related to gpt-4 support in https://github.com/Azure-Samples/azure-search-openai-demo/pull/550/files , so can you try the latest? Or just make sure that AZURE_OPENAI_CHATGPT_MODEL is set to gpt-4 ?

**Comment by pamelafox** [comment]
Thanks for reporting this and sorry for the trouble. The error “The API deployment for this resource does not exist” usually indicates that the deployment name being used doesn’t match an existing deployment in your Azure OpenAI resource, or that an embedding call is being made against a chat model deployment.

We’ve made a number of changes since this issue was filed, including fixes for GPT‑4 support (see PR #550) and clearer separation of chat vs. embedding deployments via environment variables. Please try the latest main branch and verify the following:
- You have both a chat model and an embedding model deployed in your Azure OpenAI resource.
- Your environment variables point to existing deployments, e.g. AZURE_OPENAI_CHATGPT_MODEL/DEPLOYMENT for chat (e.g., gpt‑4 or successor) and AZURE_OPENAI_EMBEDDING_MODEL/DEPLOYMENT for embeddings (e.g., text-embedding-3-large or similar).
- Re-run azd up after updating env variables so the app picks up the correct values.

If you still see this with the current code, please open a new issue and include:
- The region and exact deployment names for both chat and embedding models
- Your relevant AZD/OpenAI env variables (redact keys)
- The exact command you ran (e.g., prepdocs) and full logs

Closing this as stale/obsolete, but we’re happy to investigate further with updated details.
