### ISSUE TITLE
prepdocs error

### ISSUE THREAD

**Issue by albandrod** [Azure-Samples/azure-search-openai-demo#558]
while trying to prepdocs in a existing installation, I'm receiving the following:

Running "prepdocs.py"
Ensuring search index gptkbindex exists
Search index gptkbindex already exists
Processing files...
Processing 'C:\Temp\OpenAIDemo/data\Benefit_Options.pdf'
        Uploading blob for page 0 -> Benefit_Options-0.pdf
        Uploading blob for page 1 -> Benefit_Options-1.pdf
        Uploading blob for page 2 -> Benefit_Options-2.pdf
        Uploading blob for page 3 -> Benefit_Options-3.pdf
Extracting text from 'C:\Temp\OpenAIDemo/data\Benefit_Options.pdf' using Azure Form Recognizer
Indexing sections from 'Benefit_Options.pdf' into search index 'gptkbindex'
Splitting 'C:\Temp\OpenAIDemo/data\Benefit_Options.pdf' into sections
Traceback (most recent call last):
  File "C:\Temp\OpenAIDemo\scripts\prepdocs.py", line 395, in <module>
    index_sections(os.path.basename(filename), sections)
  File "C:\Temp\OpenAIDemo\scripts\prepdocs.py", line 291, in index_sections
    results = search_client.upload_documents(documents=batch)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Temp\OpenAIDemo\scripts\.venv\Lib\site-packages\azure\search\documents\_search_client.py", line 553, in upload_documents
    results = self.index_documents(batch, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Temp\OpenAIDemo\scripts\.venv\Lib\site-packages\azure\core\tracing\decorator.py", line 76, in wrapper_use_tracer
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Temp\OpenAIDemo\scripts\.venv\Lib\site-packages\azure\search\documents\_search_client.py", line 651, in index_documents
    return self._index_documents_actions(actions=batch.actions, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Temp\OpenAIDemo\scripts\.venv\Lib\site-packages\azure\search\documents\_search_client.py", line 659, in _index_documents_actions
    batch_response = self._client.documents.index(batch=batch, error_map=error_map, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Temp\OpenAIDemo\scripts\.venv\Lib\site-packages\azure\core\tracing\decorator.py", line 76, in wrapper_use_tracer
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Temp\OpenAIDemo\scripts\.venv\Lib\site-packages\azure\search\documents\_generated\operations\_documents_operations.py", line 1270, in index
    raise HttpResponseError(response=response, model=error)
azure.core.exceptions.HttpResponseError: () The request is invalid. Details: parameters : Cannot find nested property 'embedding' on the resource type 'search.documentFields'.
Code:
Message: The request is invalid. Details: parameters : Cannot find nested property 'embedding' on the resource type 'search.documentFields'

**Comment by pamelafox** [comment]
Please see: https://github.com/Azure-Samples/azure-search-openai-demo/issues/501

**Comment by pamelafox** [comment]
Closing this issue as I'm assuming the issue was an incorrectly setup index. Please comment if you still need guidance.
