### ISSUE TITLE
Vite config fails to load during build process

### ISSUE THREAD

**Issue by jalfrey** [Azure-Samples/azure-search-openai-demo#601]
### This issue is for a: 
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [X] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
Execute 'npm run build' with npm ver. 10.0.0 - error is consistent across local and Azure environments. Switching to earlier npm versions does not resolve the issue. 

### Any log messages given by the failure
```
failed to load config from /Desktop/chatllms-dev/app/frontend/vite.config.ts
error during build:
TypeError: Cannot redefine property: File
    at Function.defineProperty (<anonymous>)
    at Object.<anonymous> (/Desktop/chatllms-dev/app/frontend/node_modules/@babel/core/lib/index.js:7:8)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/Desktop/chatllms-dev/app/frontend/node_modules/@babel/core/lib/config/helpers/config-api.js:16:9)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
```

### OS and Version?
Mac OS Ventura

### azd version? 
> azd version 1.2.0

**Comment by pamelafox** [comment]
This appears to be this Node regression? https://github.com/babel/babel/issues/15927
You said you changed npm versions, does that mean you also changed Node versions? It seems that pinning Node is the way to go. You can also use GitHub Codespaces as that uses an earlier version of Node.

**Comment by jalfrey** [comment]
> This appears to be this Node regression? [babel/babel#15927](https://github.com/babel/babel/issues/15927) You said you changed npm versions, does that mean you also changed Node versions? It seems that pinning Node is the way to go. You can also use GitHub Codespaces as that uses an earlier version of Node.

Rolling back to an earlier Node.js version seemed to resolve the issue. Thanks!
