### ISSUE TITLE
Getting invalid request error while deploying index

### ISSUE THREAD

**Issue by namratam30** [Azure-Samples/azure-search-openai-demo#625]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
Getting below error while updating index-
Rate limited on the OpenAI embeddings API, sleeping before retrying...
2023-09-13T07:39:32.2365420Z Traceback (most recent call last):
2023-09-13T07:39:32.2365744Z   File "/home/vsts/work/1/s/scripts/.venv/lib/python3.9/site-packages/tenacity/__init__.py", line 382, in __call__
2023-09-13T07:39:32.2365947Z     result = fn(*args, **kwargs)
2023-09-13T07:39:32.2366112Z   File "/home/vsts/work/1/s/./scripts/prepdocs.py", line 235, in compute_embedding
2023-09-13T07:39:32.2366340Z     return openai.Embedding.create(engine=args.openaideployment, input=text)["data"][0]["embedding"]
2023-09-13T07:39:32.2366710Z   File "/home/vsts/work/1/s/scripts/.venv/lib/python3.9/site-packages/openai/api_resources/embedding.py", line 33, in create
2023-09-13T07:39:32.2366921Z     response = super().create(*args, **kwargs)
2023-09-13T07:39:32.2367305Z   File "/home/vsts/work/1/s/scripts/.venv/lib/python3.9/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 149, in create
2023-09-13T07:39:32.2367516Z     ) = cls.__prepare_create_request(
2023-09-13T07:39:32.2367914Z   File "/home/vsts/work/1/s/scripts/.venv/lib/python3.9/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 83, in __prepare_create_request
2023-09-13T07:39:32.2368445Z     raise error.InvalidRequestError(
2023-09-13T07:39:32.2368831Z openai.error.InvalidRequestError: Must provide an 'engine' or 'deployment_id' parameter to create a <class 'openai.api_resources.embedding.Embedding'>
2023-09-13T07:39:32.2368980Z 
2023-09-13T07:39:32.2369120Z The above exception was the direct cause of the following exception:
2023-09-13T07:39:32.2369329Z 
2023-09-13T07:39:32.2369443Z Traceback (most recent call last):
2023-09-13T07:39:32.2369619Z   File "/home/vsts/work/1/s/./scripts/prepdocs.py", line 395, in <module>
2023-09-13T07:39:32.2369795Z     index_sections(os.path.basename(filename), sections)
2023-09-13T07:39:32.2369977Z   File "/home/vsts/work/1/s/./scripts/prepdocs.py", line 281, in index_sections
2023-09-13T07:39:32.2370142Z     for s in sections:
2023-09-13T07:39:32.2370298Z   File "/home/vsts/work/1/s/./scripts/prepdocs.py", line 226, in create_sections
2023-09-13T07:39:32.2370491Z     section["embedding"] = compute_embedding(content)
2023-09-13T07:39:32.2370814Z   File "/home/vsts/work/1/s/scripts/.venv/lib/python3.9/site-packages/tenacity/__init__.py", line 289, in wrapped_f
2023-09-13T07:39:32.2371014Z     return self(f, *args, **kw)
2023-09-13T07:39:32.2371315Z   File "/home/vsts/work/1/s/scripts/.venv/lib/python3.9/site-packages/tenacity/__init__.py", line 379, in __call__
2023-09-13T07:39:32.2371524Z     do = self.iter(retry_state=retry_state)
2023-09-13T07:39:32.2371831Z   File "/home/vsts/work/1/s/scripts/.venv/lib/python3.9/site-packages/tenacity/__init__.py", line 326, in iter
2023-09-13T07:39:32.2372020Z     raise retry_exc from fut.exception()
2023-09-13T07:39:32.2372225Z tenacity.RetryError: RetryError[<Future at 0x7fded6199130 state=finished raised InvalidRequestError>]
2023-09-13T07:39:32.3661723Z ##[error]Bash exited with code '1'.
2023-09-13T07:39:32.3670275Z ##[section]Finishing: Process Documents

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Please check the .azure/YOUR-ENV-NAME/.env file for the AZURE_OPENAI_EMB_DEPLOYMENT value. Mine looks like:

```
AZURE_OPENAI_EMB_DEPLOYMENT="embedding"
```

If it's missing:

* If you have an ada deployment, just add the variable with the name of the deployment
* If you don't have an ada deployment, you can re-provision to create one
* If you don't want to use vectors, modify prepdocs.ps1 or prepdocs.sh to disable vectors by passing in --novectors

**Comment by namratam30** [comment]
I am just running the prepdoc.py file index update in DevOps pipeline. I am using existing OpenAO service. Where should i defined "AZURE_OPENAI_EMB_DEPLOYMENT" parameter.

**Comment by pamelafox** [comment]
Whatever code is calling prepdoc.py should pass in openaideployment to prepdocs.py, like our prepdocs.ps1 and prepdocs.sh scripts do. For example:

--openaideployment "$AZURE_OPENAI_EMB_DEPLOYMENT" 

The value should be the name of the deployment from Azure OpenAI studio (*not* the name of the model).
