### ISSUE TITLE
Error try to run locally after successfully run the azd up and azd down

### ISSUE THREAD

**Issue by pmtang** [Azure-Samples/azure-search-openai-demo#643]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> template: azd up and then azd down and then run ./app/start.ps1

### Any log messages given by the failure
> Starting backend

 * Serving Quart app 'app'
 * Environment: production
 * Please use an ASGI server (e.g. Hypercorn) directly in production
 * Debug mode: False
 * Running on http://127.0.0.1:50505 (CTRL + C to quit)
ERROR:app:Exception
Traceback (most recent call last):
  File "C:\Users\USERUSER\project\ChatGPT\demo5\app\backend\backend_env\lib\site-packages\quart\app.py", line 1936, in startup
    await self.ensure_async(func)()
  File "C:\Users\USERUSER\project\ChatGPT\demo5\app\backend\app.py", line 145, in setup_clients
    AZURE_STORAGE_ACCOUNT = os.environ["AZURE_STORAGE_ACCOUNT"]
  File "C:\Users\USERUSER\AppData\Local\Programs\Python\Python310\lib\os.py", line 680, in __getitem__
    raise KeyError(key) from None
KeyError: 'AZURE_STORAGE_ACCOUNT'
Traceback (most recent call last):
  File "C:\Users\USERUSER\project\ChatGPT\demo5\app\backend\backend_env\lib\site-packages\quart\asgi.py", line 311, in __call__
    await self.app.startup()
  File "C:\Users\USERUSER\project\ChatGPT\demo5\app\backend\backend_env\lib\site-packages\quart\app.py", line 1936, in startup
    await self.ensure_async(func)()
  File "C:\Users\USERUSER\project\ChatGPT\demo5\app\backend\app.py", line 145, in setup_clients
    AZURE_STORAGE_ACCOUNT = os.environ["AZURE_STORAGE_ACCOUNT"]
  File "C:\Users\USERUSER\AppData\Local\Programs\Python\Python310\lib\os.py", line 680, in __getitem__
    raise KeyError(key) from None
KeyError: 'AZURE_STORAGE_ACCOUNT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USERUSER\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\USERUSER\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\USERUSER\project\ChatGPT\demo5\app\backend\backend_env\lib\site-packages\quart\__main__.py", line 6, in <module>        
    main()
  File "C:\Users\USERUSER\project\ChatGPT\demo5\app\backend\backend_env\lib\site-packages\quart\cli.py", line 771, in main
    cli.main()
  File "C:\Users\USERUSER\project\ChatGPT\demo5\app\backend\backend_env\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\USERUSER\project\ChatGPT\demo5\app\backend\backend_env\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\USERUSER\project\ChatGPT\demo5\app\backend\backend_env\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\USERUSER\project\ChatGPT\demo5\app\backend\backend_env\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\USERUSER\project\ChatGPT\demo5\app\backend\backend_env\lib\site-packages\click\decorators.py", line 92, in new_func     
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Users\USERUSER\project\ChatGPT\demo5\app\backend\backend_env\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\USERUSER\project\ChatGPT\demo5\app\backend\backend_env\lib\site-packages\quart\cli.py", line 662, in run_command        
    app.run(
  File "C:\Users\USERUSER\project\ChatGPT\demo5\app\backend\backend_env\lib\site-packages\quart\app.py", line 1423, in run
    loop.run_until_complete(asyncio.gather(*tasks))
  File "C:\Users\USERUSER\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\USERUSER\project\ChatGPT\demo5\app\backend\backend_env\lib\site-packages\hypercorn\asyncio\__init__.py", line 49, in serve
    await worker_serve(
  File "C:\Users\USERUSER\project\ChatGPT\demo5\app\backend\backend_env\lib\site-packages\hypercorn\asyncio\run.py", line 81, in worker_serve
    raise exception
  File "C:\Users\USERUSER\project\ChatGPT\demo5\app\backend\backend_env\lib\site-packages\hypercorn\asyncio\lifespan.py", line 43, in handle_lifespan
    await self.app(
  File "C:\Users\USERUSER\project\ChatGPT\demo5\app\backend\backend_env\lib\site-packages\hypercorn\app_wrappers.py", line 33, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\USERUSER\project\ChatGPT\demo5\app\backend\backend_env\lib\site-packages\quart\app.py", line 1902, in __call__
    await self.asgi_app(scope, receive, send)
  File "C:\Users\USERUSER\project\ChatGPT\demo5\app\backend\backend_env\lib\site-packages\opentelemetry\instrumentation\asgi\__init__.py", line 542, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\USERUSER\project\ChatGPT\demo5\app\backend\backend_env\lib\site-packages\quart\app.py", line 1928, in asgi_app
    await asgi_handler(receive, send)
  File "C:\Users\USERUSER\project\ChatGPT\demo5\app\backend\backend_env\lib\site-packages\quart\asgi.py", line 313, in __call__
    await send(
  File "C:\Users\USERUSER\project\ChatGPT\demo5\app\backend\backend_env\lib\site-packages\hypercorn\asyncio\lifespan.py", line 101, in asgi_send
    raise LifespanFailureError("startup", message.get("message", ""))
hypercorn.utils.LifespanFailureError: Lifespan failure in startup. ''AZURE_STORAGE_ACCOUNT''

### Expected/desired behavior
> deploy locally

### OS and Version?
> Windows 10 Enterprise

### azd version?
> azd version 1.3.0 (commit 6605c5768cb3ab6d9e0e6c2d892c9e8b49e1f720)

### Versions
>2023-09-18 latest

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Hm. Two questions:

1) Did you run app/start.ps1 directly or cd into app and run start.ps1 from there? Our readme recommends the latter.

2) The start.ps1 script copies AZURE_STORAGE_ACCOUNT from your current azd envirnment. Do you see AZURE_STORAGE_ACCOUNT in .azure/YOUR-ENV-NAME/.env? And do you see it when you run `azd env get-values`?

**Comment by mhalomari** [comment]
HI, I am not sure if I read the title right! did you run "azd down"?

**Comment by pamelafox** [comment]
Oh good catch! If you run azd down, then the resources will no longer exist. You should re-run azd up in that case.

**Comment by pmtang** [comment]
> Oh good catch! If you run azd down, then the resources will no longer exist. You should re-run azd up in that case.

I see. then what does it mean by running "locally" if the resources have to stay in the cloud?

**Comment by pamelafox** [comment]
It means that the web app runs from localhost on your machine. For this sample, you do need cloud resources, since there's no local version of the OpenAI APIs.

**Comment by pmtang** [comment]
> It means that the web app runs from localhost on your machine. For this sample, you do need cloud resources, since there's no local version of the OpenAI APIs.

Thanks a lot!

**Comment by sunnygambit** [comment]
**Getting same error:** I ran the app after navigating to app folder the ./start.ps1 
PS D:\azure_openai_service\app\backend> azd env get-values
AZURE_ENV_NAME="localenvsun"
AZURE_LOCATION="eastus2"
AZURE_SUBSCRIPTION_ID="27389ee2-2cfe-4ce5-a838-9b5141d6b4f2"

**Comment by pamelafox** [comment]
@sunnygambit You still need to run `azd up` before you can run it locally. The `azd init` step only copies the code locally, it doesn't do any provisioning or deploying. (It's basically doing a git clone of this repo).
