### ISSUE TITLE
Internal Server Error The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

### ISSUE THREAD

**Issue by lummy2020** [Azure-Samples/azure-search-openai-demo#668]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful
I'm getting Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application when I click on the citation provided for the document referenced in the answer. Does anyone have a fix? Thanks for the help.
![Internal Server Error](https://github.com/Azure-Samples/azure-search-openai-demo/assets/135025088/0cae2683-44a4-43a5-a163-5ba850205a48)
![Internal Server Error](https://github.com/Azure-Samples/azure-search-openai-demo/assets/135025088/e4a0e131-0ed6-4804-bfb6-b9a019dbeeb1)

> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Can you read the FAQ on "How can we view logs from the App Service app?" and share your logs?

https://github.com/Azure-Samples/azure-search-openai-demo#faq

**Comment by lummy2020** [comment]
[2023_09_25_lw0sdlwk00015X_default_docker.log](https://github.com/Azure-Samples/azure-search-openai-demo/files/12710103/2023_09_25_lw0sdlwk00015X_default_docker.log)


2023-09-25T00:41:35.462151296Z ERROR:app:Exception on request GET /content/A1 International Financial Reporting Standards Foundation _ DART – Deloitte Accounting Research Tool-0.pdf
2023-09-25T00:41:35.462906399Z Traceback (most recent call last):
2023-09-25T00:41:35.462919099Z   File "/tmp/8dbbd574aabb451/antenv/lib/python3.10/site-packages/quart/app.py", line 1650, in handle_request
2023-09-25T00:41:35.462935099Z     return await self.full_dispatch_request(request_context)
2023-09-25T00:41:35.462939399Z   File "/tmp/8dbbd574aabb451/antenv/lib/python3.10/site-packages/quart/app.py", line 1675, in full_dispatch_request
2023-09-25T00:41:35.462943899Z     result = await self.handle_user_exception(error)
2023-09-25T00:41:35.462947899Z   File "/tmp/8dbbd574aabb451/antenv/lib/python3.10/site-packages/quart/app.py", line 1107, in handle_user_exception
2023-09-25T00:41:35.462952099Z     raise error
2023-09-25T00:41:35.462955799Z   File "/tmp/8dbbd574aabb451/antenv/lib/python3.10/site-packages/quart/app.py", line 1673, in full_dispatch_request
2023-09-25T00:41:35.462959899Z     result = await self.dispatch_request(request_context)
2023-09-25T00:41:35.462963799Z   File "/tmp/8dbbd574aabb451/antenv/lib/python3.10/site-packages/quart/app.py", line 1718, in dispatch_request
2023-09-25T00:41:35.462967699Z     return await self.ensure_async(handler)(**request_.view_args)
2023-09-25T00:41:35.462971399Z   File "/tmp/8dbbd574aabb451/app.py", line 64, in content_file
2023-09-25T00:41:35.462975199Z     blob = await blob_container_client.get_blob_client(path).download_blob()
2023-09-25T00:41:35.462979099Z   File "/tmp/8dbbd574aabb451/antenv/lib/python3.10/site-packages/azure/core/tracing/decorator_async.py", line 88, in wrapper_use_tracer
2023-09-25T00:41:35.462982999Z     return await func(*args, **kwargs)
2023-09-25T00:41:35.462986599Z   File "/tmp/8dbbd574aabb451/antenv/lib/python3.10/site-packages/azure/storage/blob/aio/_blob_client_async.py", line 525, in download_blob
2023-09-25T00:41:35.462990599Z     await downloader._setup()  # pylint: disable=protected-access
2023-09-25T00:41:35.462994399Z   File "/tmp/8dbbd574aabb451/antenv/lib/python3.10/site-packages/azure/storage/blob/aio/_download_async.py", line 288, in _setup
2023-09-25T00:41:35.462998199Z     self._response = await self._initial_request()
2023-09-25T00:41:35.463001899Z   File "/tmp/8dbbd574aabb451/antenv/lib/python3.10/site-packages/azure/storage/blob/aio/_download_async.py", line 387, in _initial_request
2023-09-25T00:41:35.463005799Z     process_storage_error(error)
2023-09-25T00:41:35.463009599Z   File "/tmp/8dbbd574aabb451/antenv/lib/python3.10/site-packages/azure/storage/blob/_shared/response_handlers.py", line 185, in process_storage_error
2023-09-25T00:41:35.463358200Z     exec("raise error from None")   # pylint: disable=exec-used # nosec
2023-09-25T00:41:35.463393300Z   File "<string>", line 1, in <module>
2023-09-25T00:41:35.463398700Z   File "/tmp/8dbbd574aabb451/antenv/lib/python3.10/site-packages/azure/storage/blob/aio/_download_async.py", line 341, in _initial_request
2023-09-25T00:41:35.463402500Z     location_mode, response = await self._clients.blob.download(
2023-09-25T00:41:35.463405900Z   File "/tmp/8dbbd574aabb451/antenv/lib/python3.10/site-packages/azure/core/tracing/decorator_async.py", line 88, in wrapper_use_tracer
2023-09-25T00:41:35.463409500Z     return await func(*args, **kwargs)
2023-09-25T00:41:35.463412900Z   File "/tmp/8dbbd574aabb451/antenv/lib/python3.10/site-packages/azure/storage/blob/_generated/aio/operations/_blob_operations.py", line 198, in download
2023-09-25T00:41:35.463416500Z     map_error(status_code=response.status_code, response=response, error_map=error_map)
2023-09-25T00:41:35.463419900Z   File "/tmp/8dbbd574aabb451/antenv/lib/python3.10/site-packages/azure/core/exceptions.py", line 165, in map_error
2023-09-25T00:41:35.463423400Z     raise error
2023-09-25T00:41:35.463426800Z azure.core.exceptions.ResourceNotFoundError: The specified blob does not exist.
2023-09-25T00:41:35.463430200Z RequestId:8ea40918-501e-0054-2e49-efafa9000000
2023-09-25T00:41:35.463433500Z Time:2023-09-25T00:41:35.4339720Z
2023-09-25T00:41:35.463436800Z ErrorCode:BlobNotFound
2023-09-25T00:41:35.463440100Z Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
2023-09-25T00:41:35.463444500Z RequestId:8ea40918-501e-0054-2e49-efafa9000000
2023-09-25T00:41:35.463447800Z Time:2023-09-25T00:41:35.4339720Z</Message></Error>

2023-09-25T00:41:40.341365458Z ERROR:app:Exception on request GET /content/A1 International Financial Reporting Standards Foundation _ DART – Deloitte Accounting Research Tool-6.pdf
2023-09-25T00:41:40.341410659Z Traceback (most recent call last):
2023-09-25T00:41:40.341416459Z   File "/tmp/8dbbd574aabb451/antenv/lib/python3.10/site-packages/quart/app.py", line 1650, in handle_request
2023-09-25T00:41:40.341420359Z     return await self.full_dispatch_request(request_context)
2023-09-25T00:41:40.341424159Z   File "/tmp/8dbbd574aabb451/antenv/lib/python3.10/site-packages/quart/app.py", line 1675, in full_dispatch_request
2023-09-25T00:41:40.341436259Z     result = await self.handle_user_exception(error)
2023-09-25T00:41:40.341440959Z   File "/tmp/8dbbd574aabb451/antenv/lib/python3.10/site-packages/quart/app.py", line 1107, in handle_user_exception
2023-09-25T00:41:40.341444759Z     raise error
2023-09-25T00:41:40.341448159Z   File "/tmp/8dbbd574aabb451/antenv/lib/python3.10/site-packages/quart/app.py", line 1673, in full_dispatch_request
2023-09-25T00:41:40.341467859Z     result = await self.dispatch_request(request_context)
2023-09-25T00:41:40.341471659Z   File "/tmp/8dbbd574aabb451/antenv/lib/python3.10/site-packages/quart/app.py", line 1718, in dispatch_request
2023-09-25T00:41:40.341475159Z     return await self.ensure_async(handler)(**request_.view_args)
2023-09-25T00:41:40.341478659Z   File "/tmp/8dbbd574aabb451/app.py", line 64, in content_file
2023-09-25T00:41:40.341482859Z     blob = await blob_container_client.get_blob_client(path).download_blob()
2023-09-25T00:41:40.341486459Z   File "/tmp/8dbbd574aabb451/antenv/lib/python3.10/site-packages/azure/core/tracing/decorator_async.py", line 88, in wrapper_use_tracer
2023-09-25T00:41:40.341490059Z     return await func(*args, **kwargs)
2023-09-25T00:41:40.341493359Z   File "/tmp/8dbbd574aabb451/antenv/lib/python3.10/site-packages/azure/storage/blob/aio/_blob_client_async.py", line 525, in download_blob
2023-09-25T00:41:40.341497059Z     await downloader._setup()  # pylint: disable=protected-access
2023-09-25T00:41:40.341500459Z   File "/tmp/8dbbd574aabb451/antenv/lib/python3.10/site-packages/azure/storage/blob/aio/_download_async.py", line 288, in _setup
2023-09-25T00:41:40.341503959Z     self._response = await self._initial_request()
2023-09-25T00:41:40.341507459Z   File "/tmp/8dbbd574aabb451/antenv/lib/python3.10/site-packages/azure/storage/blob/aio/_download_async.py", line 387, in _initial_request
2023-09-25T00:41:40.341510959Z     process_storage_error(error)
2023-09-25T00:41:40.341514359Z   File "/tmp/8dbbd574aabb451/antenv/lib/python3.10/site-packages/azure/storage/blob/_shared/response_handlers.py", line 185, in process_storage_error
2023-09-25T00:41:40.341519859Z     exec("raise error from None")   # pylint: disable=exec-used # nosec
2023-09-25T00:41:40.341523459Z   File "<string>", line 1, in <module>
2023-09-25T00:41:40.341527459Z   File "/tmp/8dbbd574aabb451/antenv/lib/python3.10/site-packages/azure/storage/blob/aio/_download_async.py", line 341, in _initial_request
2023-09-25T00:41:40.341531059Z     location_mode, response = await self._clients.blob.download(
2023-09-25T00:41:40.341534459Z   File "/tmp/8dbbd574aabb451/antenv/lib/python3.10/site-packages/azure/core/tracing/decorator_async.py", line 88, in wrapper_use_tracer
2023-09-25T00:41:40.341538059Z     return await func(*args, **kwargs)
2023-09-25T00:41:40.341541359Z   File "/tmp/8dbbd574aabb451/antenv/lib/python3.10/site-packages/azure/storage/blob/_generated/aio/operations/_blob_operations.py", line 198, in download
2023-09-25T00:41:40.341544959Z     map_error(status_code=response.status_code, response=response, error_map=error_map)
2023-09-25T00:41:40.341548359Z   File "/tmp/8dbbd574aabb451/antenv/lib/python3.10/site-packages/azure/core/exceptions.py", line 165, in map_error
2023-09-25T00:41:40.341551859Z     raise error
2023-09-25T00:41:40.341555059Z azure.core.exceptions.ResourceNotFoundError: The specified blob does not exist.
2023-09-25T00:41:40.341558559Z RequestId:29162db0-101e-008e-5749-ef3648000000
2023-09-25T00:41:40.341573759Z Time:2023-09-25T00:41:40.3200124Z
2023-09-25T00:41:40.341577359Z ErrorCode:BlobNotFound
2023-09-25T00:41:40.341580659Z Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
2023-09-25T00:41:40.341584959Z RequestId:29162db0-101e-008e-5749-ef3648000000
2023-09-25T00:41:40.341588259Z Time:2023-09-25T00:41:40.3200124Z</Message></Error>
2023-09-25T00:41:43.580526192Z ERROR:app:Exception on request GET /content/A1 International Financial Reporting Standards Foundation _ DART – Deloitte Accounting Research Tool-1.pdf
2023-09-25T00:41:43.580568292Z Traceback (most recent call last):
2023-09-25T00:41:43.580574692Z   File "/tmp/8dbbd574aabb451/antenv/lib/python3.10/site-packages/quart/app.py", line 1650, in handle_request
2023-09-25T00:41:43.580588292Z     return await self.full_dispatch_request(request_context)
2023-09-25T00:41:43.580592392Z   File "/tmp/8dbbd574aabb451/antenv/lib/python3.10/site-packages/quart/app.py", line 1675, in full_dispatch_request
2023-09-25T00:41:43.580596892Z     result = await self.handle_user_exception(error)
2023-09-25T00:41:43.580600592Z   File "/tmp/8dbbd574aabb451/antenv/lib/python3.10/site-packages/quart/app.py", line 1107, in handle_user_exception
2023-09-25T00:41:43.580604792Z     raise error
2023-09-25T00:41:43.580608392Z   File "/tmp/8dbbd574aabb451/antenv/lib/python3.10/site-packages/quart/app.py", line 1673, in full_dispatch_request
2023-09-25T00:41:43.580612192Z     result = await self.dispatch_request(request_context)
2023-09-25T00:41:43.580615792Z   File "/tmp/8dbbd574aabb451/antenv/lib/python3.10/site-packages/quart/app.py", line 1718, in dispatch_request
2023-09-25T00:41:43.580619592Z     return await self.ensure_async(handler)(**request_.view_args)
2023-09-25T00:41:43.580623192Z   File "/tmp/8dbbd574aabb451/app.py", line 64, in content_file
2023-09-25T00:41:43.580626892Z     blob = await blob_container_client.get_blob_client(path).download_blob()
2023-09-25T00:41:43.580630592Z   File "/tmp/8dbbd574aabb451/antenv/lib/python3.10/site-packages/azure/core/tracing/decorator_async.py", line 88, in wrapper_use_tracer
2023-09-25T00:41:43.580634692Z     return await func(*args, **kwargs)
2023-09-25T00:41:43.580638292Z   File "/tmp/8dbbd574aabb451/antenv/lib/python3.10/site-packages/azure/storage/blob/aio/_blob_client_async.py", line 525, in download_blob
2023-09-25T00:41:43.580642092Z     await downloader._setup()  # pylint: disable=protected-access
2023-09-25T00:41:43.580645692Z   File "/tmp/8dbbd574aabb451/antenv/lib/python3.10/site-packages/azure/storage/blob/aio/_download_async.py", line 288, in _setup
2023-09-25T00:41:43.580649492Z     self._response = await self._initial_request()
2023-09-25T00:41:43.580653092Z   File "/tmp/8dbbd574aabb451/antenv/lib/python3.10/site-packages/azure/storage/blob/aio/_download_async.py", line 387, in _initial_request
2023-09-25T00:41:43.580669292Z     process_storage_error(error)
2023-09-25T00:41:43.580673392Z   File "/tmp/8dbbd574aabb451/antenv/lib/python3.10/site-packages/azure/storage/blob/_shared/response_handlers.py", line 185, in process_storage_error
2023-09-25T00:41:43.580690192Z     exec("raise error from None")   # pylint: disable=exec-used # nosec
2023-09-25T00:41:43.580694192Z   File "<string>", line 1, in <module>
2023-09-25T00:41:43.580698792Z   File "/tmp/8dbbd574aabb451/antenv/lib/python3.10/site-packages/azure/storage/blob/aio/_download_async.py", line 341, in _initial_request
2023-09-25T00:41:43.580702592Z     location_mode, response = await self._clients.blob.download(
2023-09-25T00:41:43.580706392Z   File "/tmp/8dbbd574aabb451/antenv/lib/python3.10/site-packages/azure/core/tracing/decorator_async.py", line 88, in wrapper_use_tracer
2023-09-25T00:41:43.580710092Z     return await func(*args, **kwargs)
2023-09-25T00:41:43.580713792Z   File "/tmp/8dbbd574aabb451/antenv/lib/python3.10/site-packages/azure/storage/blob/_generated/aio/operations/_blob_operations.py", line 198, in download
2023-09-25T00:41:43.580717592Z     map_error(status_code=response.status_code, response=response, error_map=error_map)
2023-09-25T00:41:43.580721292Z   File "/tmp/8dbbd574aabb451/antenv/lib/python3.10/site-packages/azure/core/exceptions.py", line 165, in map_error
2023-09-25T00:41:43.580725092Z     raise error
2023-09-25T00:41:43.580728692Z azure.core.exceptions.ResourceNotFoundError: The specified blob does not exist.
2023-09-25T00:41:43.580732292Z RequestId:8ea42e72-501e-0054-5449-efafa9000000
2023-09-25T00:41:43.580735992Z Time:2023-09-25T00:41:43.5682465Z
2023-09-25T00:41:43.580739593Z ErrorCode:BlobNotFound
2023-09-25T00:41:43.580743093Z Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
2023-09-25T00:41:43.580747693Z RequestId:8ea42e72-501e-0054-5449-efafa9000000
2023-09-25T00:41:43.580751393Z Time:2023-09-25T00:41:43.5682465Z</Message></Error>

**Comment by pamelafox** [comment]
Okay, it says BlobNotFound. Have you confirmed the Blob exists in your Azure storage container with the filename (with page numbers)? I've seen issues like this where people changed whether blobs had filenames, and I've also seen issues on our end with non-ASCII filenames (which I thought we'd fixed). Please take a look at your storage container and see where the disconnect is.

**Comment by lummy2020** [comment]
Thanks for the response. The blob exists in the Azure storage account. The weird thing is after a refresh of the website I’m able to view the same referenced file that was providing an error.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pamelafox** [comment]
That is strange, I'm not sure why it errored the first time. If it's no longer happening, please close this issue, as we wouldn't be able to make code improvements without more details on the cause.

**Comment by outlookinsight** [comment]
We experienced a similar issue with "Internal Server Error" responses to opening citations.  In our case, some of the PDF files had a space between the last word of the filename and the ".pdf" extension.  Once we PowerRenamed the documents and rebuilt the index without that space, our issues disappeared.  Weird, right?

**Comment by achandmsft** [comment]
Hi @lummy2020 I am Arun Sekhar, the Principal Product Manager for Azure AI Developer Experiences in Microsoft. I would love to chat with you to understand your requirements and get your feedback around our repo. Please email me at achand at microsoft dot com if you are ok to have a brief chat with me. Looking forward to chatting with you!

**Comment by pamelafox** [comment]
Thanks for the details you shared earlier. Given the age of this report and multiple changes since then (including fixes for citation/filename handling), I’m going to close this out as stale.

If you still hit this on the latest main, please open a new issue with: an example citation URL you clicked, the exact blob name/path it should map to, your storage setup (e.g., ADLS Gen2/second account), and logs showing the BlobNotFound.
