### ISSUE TITLE
Prepdocs.py :error  Unable to get resource information.

### ISSUE THREAD

**Issue by namratam30** [Azure-Samples/azure-search-openai-demo#687]
> Please provide us with the following information:
> ---------------------------------------------------------------
 I am getting below error -
Traceback (most recent call last):
  File "/home/vsts/work/1/s/scripts/.venv/lib/python3.9/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "/home/vsts/work/1/s/./scripts/prepdocs.py", line 235, in compute_embedding
    return openai.Embedding.create(engine=args.openaideployment, input=text)["data"][0]["embedding"]
  File "/home/vsts/work/1/s/scripts/.venv/lib/python3.9/site-packages/openai/api_resources/embedding.py", line 33, in create
    response = super().create(*args, **kwargs)
  File "/home/vsts/work/1/s/scripts/.venv/lib/python3.9/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/home/vsts/work/1/s/scripts/.venv/lib/python3.9/site-packages/openai/api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/home/vsts/work/1/s/scripts/.venv/lib/python3.9/site-packages/openai/api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "/home/vsts/work/1/s/scripts/.venv/lib/python3.9/site-packages/openai/api_requestor.py", line 763, in _interpret_response_line
    raise self.handle_error_response(
openai.error.APIError: Unable to get resource information. {"error":{"code":"InternalServerError","message": "Unable to get resource information."}} 500 {'error': {'code': 'InternalServerError', 'message': 'Unable to get resource information.'}} {'Content-Length': '89', 'Content-Type': 'application/json', 'x-ms-client-request-id': 'Not-Set', 'apim-request-id': '42116a58-9eab-4b8c-8804-f981df6ec76e', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload', 'x-content-type-options': 'nosniff', 'Date': 'Thu, 28 Sep 2023 10:10:55 GMT'}

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by namratam30** [comment]
I wanted to change the OpenAI model. Where to configure these parameters in Prepdocs.py

OPENAI_API_TYPE = "azure"
OPENAI_API_VERSION = "2023-07-01-preview"
OPENAI_API_KEY = ""
OPENAI_API_BASE = " https://openai.openai.azure.com/"

**Comment by pamelafox** [comment]
You can see prepdocs.sh or prepdocs.ps1 for examples of specifying those parameters.
