### ISSUE TITLE
PyCryptodome is required for AES algorithm - fails at prepdocs.py

### ISSUE THREAD

**Issue by buswrecker** [Azure-Samples/azure-search-openai-demo#73]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>azd up

### Any log messages given by the failure
>Processing './data/2022-annual-report_spreads.pdf'
Traceback (most recent call last):
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/julianlenewcompute/code/Users/julianle/openai-demo1232/./scripts/prepdocs.py", line 312, in <module>
    upload_blobs(filename)
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/julianlenewcompute/code/Users/julianle/openai-demo1232/./scripts/prepdocs.py", line 70, in upload_blobs
    reader = PdfReader(filename)
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/julianlenewcompute/code/Users/julianle/openai-demo1232/scripts/.venv/lib/python3.9/site-packages/pypdf/_reader.py", line 339, in __init__
    self._encryption.verify(pwd) == PasswordType.NOT_DECRYPTED
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/julianlenewcompute/code/Users/julianle/openai-demo1232/scripts/.venv/lib/python3.9/site-packages/pypdf/_encryption.py", line 998, in verify
    key, rc = self.verify_v4(pwd) if self.algV <= 4 else self.verify_v5(pwd)
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/julianlenewcompute/code/Users/julianle/openai-demo1232/scripts/.venv/lib/python3.9/site-packages/pypdf/_encryption.py", line 1049, in verify_v5
    key = AlgV5.verify_owner_password(
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/julianlenewcompute/code/Users/julianle/openai-demo1232/scripts/.venv/lib/python3.9/site-packages/pypdf/_encryption.py", line 650, in verify_owner_password
    AlgV5.calculate_hash(R, password, o_value[32:40], u_value[:48])
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/julianlenewcompute/code/Users/julianle/openai-demo1232/scripts/.venv/lib/python3.9/site-packages/pypdf/_encryption.py", line 695, in calculate_hash
    E = AES_CBC_encrypt(K[:16], K[16:32], K1 * 64)
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/julianlenewcompute/code/Users/julianle/openai-demo1232/scripts/.venv/lib/python3.9/site-packages/pypdf/_encryption.py", line 164, in AES_CBC_encrypt
    raise DependencyError("PyCryptodome is required for AES algorithm")
pypdf.errors.DependencyError: PyCryptodome is required for AES algorithm

### Expected/desired behavior
>Processing './data/2022-annual-report_spreads.pdf'
        Uploading blob for page 0 -> 2022-annual-report_spreads-0.pdf
        Uploading blob for page 1 -> 2022-annual-report_spreads-1.pdf
        Uploading blob for page 2 -> 2022-annual-report_spreads-2.pdf
        Uploading blob for page 3 -> 2022-annual-report_spreads-3.pdf
        Uploading blob for page 4 -> 2022-annual-report_spreads-4.pdf
        Uploading blob for page 5 -> 2022-annual-report_spreads-5.pdf
        Uploading blob for page 6 -> 2022-annual-report_spreads-6.pdf
        Uploading blob for page 7 -> 2022-annual-report_spreads-7.pdf
        Uploading blob for page 8 -> 2022-annual-report_spreads-8.pdf
        Uploading blob for page 9 -> 2022-annual-report_spreads-9.pdf

### OS and Version?
> Linux 

### Versions
>

### Mention any other details that might be useful
I've updated the requirements.txt file in scripts/requirements.txt to include
PyCryptodome==3.17

and appears to have clear itself up
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pablocastro** [comment]
@buswrecker I imagine this is because your content may be causing the PDF parsing library to pull more dependencies (e.g. PDFs that are encrypted). Since this is specific to the scenario, we'll leave it out so we don't make everyone pull that dependency. Feel free to reactive if you disagree.

**Comment by qudarr** [comment]
@buswrecker : Thank you so much. Your insight really helped me out a lot!

**Comment by texasdave2** [comment]
```
!pip install -qqq pycryptodome==3.15.0 --progress-bar off
```
worked for me
