### ISSUE TITLE
Container app-backend-### couldn't be started

### ISSUE THREAD

**Issue by don007git** [Azure-Samples/azure-search-openai-demo#733]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> the az up is successful with clean successful endpoint
> click the endpoint get ":( Application Error" page."
> look the diagnose page, it shows "container app-backend-### couldn't be started" with error captured below. 

### Any log messages given by the failure
>
Container app-backend-dn33npvkxysqs_0_2ac5daa7 couldn't be started: Logs = 2023-10-04T14:22:00.089783572Z    _____                               
2023-10-04T14:22:00.089840373Z   /  _  \ __________ _________   ____  
2023-10-04T14:22:00.089847473Z  /  /_\  \\___   /  |  \_  __ \_/ __ \ 
2023-10-04T14:22:00.089852073Z /    |    \/    /|  |  /|  | \/\  ___/ 
2023-10-04T14:22:00.089856573Z \____|__  /_____ \____/ |__|    \___  >
2023-10-04T14:22:00.089861173Z         \/      \/                  \/ 
2023-10-04T14:22:00.089865574Z A P P   S E R V I C E   O N   L I N U X
2023-10-04T14:22:00.089869774Z 
2023-10-04T14:22:00.089873674Z Documentation: http://aka.ms/webapp-linux
2023-10-04T14:22:00.089877774Z Python 3.10.12
2023-10-04T14:22:00.089881874Z Note: Any data outside '/home' is not persisted
2023-10-04T14:22:02.068123283Z Starting OpenBSD Secure Shell server: sshd.
2023-10-04T14:22:02.336896992Z Site's appCommandLine: python3 -m gunicorn main:app
2023-10-04T14:22:02.907228403Z Starting periodic command scheduler: cron.
2023-10-04T14:22:02.907259704Z Launching oryx with: create-script -appPath /home/site/wwwroot -output /opt/startup/startup.sh -virtualEnvName antenv -defaultApp /opt/defaultsite -userStartupCommand 'python3 -m gunicorn main:app'
2023-10-04T14:22:02.975888809Z Found build manifest file at '/home/site/wwwroot/oryx-manifest.toml'. Deserializing it...
2023-10-04T14:22:02.984749616Z Build Operation ID: c6a4c673cbbc7c12
2023-10-04T14:22:02.986537758Z Oryx Version: 0.2.20230707.1, Commit: 0bd28e69919b5e8beba451e8677e3345f0be8361, ReleaseTagName: 20230707.1
2023-10-04T14:22:02.987974592Z Output is compressed. Extracting it...
2023-10-04T14:22:02.995145959Z Extracting '/home/site/wwwroot/output.tar.gz' to directory '/tmp/8dbc45cb581a465'...
2023-10-04T14:22:35.626161917Z App path is set to '/tmp/8dbc45cb581a465'
2023-10-04T14:22:35.674904866Z Writing output script to '/opt/startup/startup.sh'
2023-10-04T14:22:36.323596372Z Using packages from virtual environment antenv located at /tmp/8dbc45cb581a465/antenv.
2023-10-04T14:22:36.326567181Z Updated PYTHONPATH to '/opt/startup/app_logs:/tmp/8dbc45cb581a465/antenv/lib/python3.10/site-packages'
2023-10-04T14:22:40.336020140Z [2023-10-04 14:22:40 +0000] [74] [INFO] Starting gunicorn 20.1.0
2023-10-04T14:22:40.340178053Z [2023-10-04 14:22:40 +0000] [74] [INFO] Listening at: http://0.0.0.0:8000 (74)
2023-10-04T14:22:40.341586258Z [2023-10-04 14:22:40 +0000] [74] [INFO] Using worker: uvicorn.workers.UvicornWorker
2023-10-04T14:22:40.360850921Z [2023-10-04 14:22:40 +0000] [75] [INFO] Booting worker with pid: 75
2023-10-04T14:22:40.394033329Z [2023-10-04 14:22:40 +0000] [76] [INFO] Booting worker with pid: 76
2023-10-04T14:22:40.552607047Z [2023-10-04 14:22:40 +0000] [77] [INFO] Booting worker with pid: 77
2023-10-04T14:23:07.797261116Z [2023-10-04 14:23:07 +0000] [77] [ERROR] Exception in worker process
2023-10-04T14:23:07.797698768Z Traceback (most recent call last):
2023-10-04T14:23:07.797721976Z   File "/opt/python/3.10.12/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
2023-10-04T14:23:07.797728079Z     worker.init_process()
2023-10-04T14:23:07.797732880Z   File "/tmp/8dbc45cb581a465/antenv/lib/python3.10/site-packages/uvicorn/workers.py", line 66, in init_process
2023-10-04T14:23:07.797737882Z     super(UvicornWorker, self).init_process()
2023-10-04T14:23:07.797749986Z   File "/opt/python/3.10.12/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
2023-10-04T14:23:07.797755388Z     self.load_wsgi()
2023-10-04T14:23:07.797759990Z   File "/opt/python/3.10.12/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
2023-10-04T14:23:07.797764891Z     self.wsgi = self.app.wsgi()
2023-10-04T14:23:07.797769393Z   File "/opt/python/3.10.12/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
2023-10-04T14:23:07.797774095Z     self.callable = self.load()
2023-10-04T14:23:07.797778596Z   File "/opt/python/3.10.12/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
2023-10-04T14:23:07.797783198Z     return self.load_wsgiapp()
2023-10-04T14:23:07.797787699Z   File "/opt/python/3.10.12/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
2023-10-04T14:23:07.797792701Z     return util.import_app(self.app_uri)
2023-10-04T14:23:07.797797203Z   File "/opt/python/3.10.12/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
2023-10-04T14:23:07.797801904Z     mod = importlib.import_module(module)
2023-10-04T14:23:07.797806406Z   File "/opt/python/3.10.12/lib/python3.10/importlib/__init__.py", line 126, in import_module
2023-10-04T14:23:07.797811108Z     return _bootstrap._gcd_import(name[level:], package, level)
2023-10-04T14:23:07.797815609Z   File "", line 1050, in _gcd_import
2023-10-04T14:23:07.797820711Z   File "", line 1027, in _find_and_load
2023-10-04T14:23:07.797825313Z   File "", line 1006, in _find_and_load_unlocked
2023-10-04T14:23:07.797830114Z   File "", line 688, in _load_unlocked
2023-10-04T14:23:07.797834716Z   File "", line 883, in exec_module
2023-10-04T14:23:07.797839417Z   File "", line 241, in _call_with_frames_removed
2023-10-04T14:23:07.797844219Z   File "/tmp/8dbc45cb581a465/main.py", line 1, in 
2023-10-04T14:23:07.797848921Z     from app import create_app
2023-10-04T14:23:07.797853322Z   File "/tmp/8dbc45cb581a465/app.py", line 18, in 
2023-10-04T14:23:07.797858124Z     from quart import (
2023-10-04T14:23:07.797865326Z   File "/tmp/8dbc45cb581a465/antenv/lib/python3.10/site-packages/quart/__init__.py", line 5, in 
2023-10-04T14:23:07.797875830Z     from .app import Quart as Quart
2023-10-04T14:23:07.797880532Z   File "/tmp/8dbc45cb581a465/antenv/lib/python3.10/site-packages/quart/app.py", line 46, in 
2023-10-04T14:23:07.797885433Z     from werkzeug.urls import url_quote
2023-10-04T14:23:07.797890035Z ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/tmp/8dbc45cb581a465/antenv/lib/python3.10/site-packages/werkzeug/urls.py)
2023-10-04T14:23:07.855597470Z [2023-10-04 14:23:07 +0000] [75] [ERROR] Exception in worker process
2023-10-04T14:23:07.855633583Z Traceback (most recent call last):
2023-10-04T14:23:07.855639785Z   File "/opt/python/3.10.12/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
2023-10-04T14:23:07.855644787Z     worker.init_process()
2023-10-04T14:23:07.855649489Z   File "/tmp/8dbc45cb581a465/antenv/lib/python3.10/site-packages/uvicorn/workers.py", line 66, in init_process
2023-10-04T14:23:07.855654290Z     super(UvicornWorker, self).init_process()
2023-10-04T14:23:07.855658892Z   File "/opt/python/3.10.12/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
2023-10-04T14:23:07.855663594Z     self.load_wsgi()
2023-10-04T14:23:07.855668095Z   File "/opt/python/3.10.12/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
2023-10-04T14:23:07.855672697Z     self.wsgi = self.app.wsgi()
2023-10-04T14:23:07.855677198Z   File "/opt/python/3.10.12/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
2023-10-04T14:23:07.855681800Z     self.callable = self.load()
2023-10-04T14:23:07.855686201Z   File "/opt/python/3.10.12/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
2023-10-04T14:23:07.855691403Z     return self.load_wsgiapp()
2023-10-04T14:23:07.855695805Z   File "/opt/python/3.10.12/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
2023-10-04T14:23:07.855700506Z     return util.import_app(self.app_uri)
2023-10-04T14:23:07.855704908Z   File "/opt/python/3.10.12/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
2023-10-04T14:23:07.855709510Z     mod = importlib.import_module(module)
2023-10-04T14:23:07.855714011Z   File "/opt/python/3.10.12/lib/python3.10/importlib/__init__.py", line 126, in import_module
2023-10-04T14:23:07.855718613Z     return _bootstrap._gcd_import(name[level:], package, level)
2023-10-04T14:23:07.855723114Z   File "", line 1050, in _gcd_import
2023-10-04T14:23:07.855728116Z   File "", line 1027, in _find_and_load
2023-10-04T14:23:07.855733418Z   File "", line 1006, in _find_and_load_unlocked
2023-10-04T14:23:07.855738120Z   File "", line 688, in _load_unlocked
2023-10-04T14:23:07.855754125Z   File "", line 883, in exec_module
2023-10-04T14:23:07.855759027Z   File "", line 241, in _call_with_frames_removed
2023-10-04T14:23:07.855763728Z   File "/tmp/8dbc45cb581a465/main.py", line 1, in 
2023-10-04T14:23:07.855768430Z     from app import create_app
2023-10-04T14:23:07.855772832Z   File "/tmp/8dbc45cb581a465/app.py", line 18, in 
2023-10-04T14:23:07.855777533Z     from quart import (
2023-10-04T14:23:07.855782835Z   File "/tmp/8dbc45cb581a465/antenv/lib/python3.10/site-packages/quart/__init__.py", line 5, in 
2023-10-04T14:23:07.855787737Z     from .app import Quart as Quart
2023-10-04T14:23:07.855792138Z   File "/tmp/8dbc45cb581a465/antenv/lib/python3.10/site-packages/quart/app.py", line 46, in 
2023-10-04T14:23:07.855796840Z     from werkzeug.urls import url_quote
2023-10-04T14:23:07.855801342Z ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/tmp/8dbc45cb581a465/antenv/lib/python3.10/site-packages/werkzeug/urls.py)
2023-10-04T14:23:07.855805943Z [2023-10-04 14:23:07 +0000] [76] [ERROR] Exception in worker process
2023-10-04T14:23:07.855810545Z Traceback (most recent call last):
2023-10-04T14:23:07.855814946Z   File "/opt/python/3.10.12/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
2023-10-04T14:23:07.855819548Z     worker.init_process()
2023-10-04T14:23:07.855823949Z   File "/tmp/8dbc45cb581a465/antenv/lib/python3.10/site-packages/uvicorn/workers.py", line 66, in init_process
2023-10-04T14:23:07.855828551Z     super(UvicornWorker, self).init_process()
2023-10-04T14:23:07.855833053Z   File "/opt/python/3.10.12/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
2023-10-04T14:23:07.855837554Z     self.load_wsgi()
2023-10-04T14:23:07.855841956Z   File "/opt/python/3.10.12/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
2023-10-04T14:23:07.855846457Z     self.wsgi = self.app.wsgi()
2023-10-04T14:23:07.855850859Z   File "/opt/python/3.10.12/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
2023-10-04T14:23:07.855855360Z     self.callable = self.load()
2023-10-04T14:23:07.855859762Z   File "/opt/python/3.10.12/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
2023-10-04T14:23:07.855864264Z     return self.load_wsgiapp()
2023-10-04T14:23:07.855868665Z   File "/opt/python/3.10.12/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
2023-10-04T14:23:07.855873267Z     return util.import_app(self.app_uri)
2023-10-04T14:23:07.855877668Z   File "/opt/python/3.10.12/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
2023-10-04T14:23:07.855882270Z     mod = importlib.import_module(module)
2023-10-04T14:23:07.855886671Z   File "/opt/python/3.10.12/lib/python3.10/importlib/__init__.py", line 126, in import_module
2023-10-04T14:23:07.855895174Z     return _bootstrap._gcd_import(name[level:], package, level)
2023-10-04T14:23:07.855899876Z   File "", line 1050, in _gcd_import
2023-10-04T14:23:07.855904478Z   File "", line 1027, in _find_and_load
2023-10-04T14:23:07.855909179Z   File "", line 1006, in _find_and_load_unlocked
2023-10-04T14:23:07.855913781Z   File "", line 688, in _load_unlocked
2023-10-04T14:23:07.855918783Z   File "", line 883, in exec_module
2023-10-04T14:23:07.855923584Z   File "", line 241, in _call_with_frames_removed
2023-10-04T14:23:07.855928186Z   File "/tmp/8dbc45cb581a465/main.py", line 1, in 
2023-10-04T14:23:07.855932787Z     from app import create_app
2023-10-04T14:23:07.855937289Z   File "/tmp/8dbc45cb581a465/app.py", line 18, in 
2023-10-04T14:23:07.855941791Z     from quart import (
2023-10-04T14:23:07.855946092Z   File "/tmp/8dbc45cb581a465/antenv/lib/python3.10/site-packages/quart/__init__.py", line 5, in 
2023-10-04T14:23:07.855950794Z     from .app import Quart as Quart
2023-10-04T14:23:07.855955195Z   File "/tmp/8dbc45cb581a465/antenv/lib/python3.10/site-packages/quart/app.py", line 46, in 
2023-10-04T14:23:07.855959797Z     from werkzeug.urls import url_quote
2023-10-04T14:23:07.855964198Z ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/tmp/8dbc45cb581a465/antenv/lib/python3.10/site-packages/werkzeug/urls.py)
2023-10-04T14:23:07.855968900Z [2023-10-04 14:23:07 +0000] [77] [INFO] Worker exiting (pid: 77)
2023-10-04T14:23:07.855973402Z [2023-10-04 14:23:07 +0000] [75] [INFO] Worker exiting (pid: 75)
2023-10-04T14:23:07.855977803Z [2023-10-04 14:23:07 +0000] [76] [INFO] Worker exiting (pid: 76)
2023-10-04T14:23:10.190105833Z [2023-10-04 14:23:10 +0000] [74] [WARNING] Worker with pid 76 was terminated due to signal 15
2023-10-04T14:23:10.190139833Z [2023-10-04 14:23:10 +0000] [74] [WARNING] Worker with pid 75 was terminated due to signal 15
2023-10-04T14:23:10.236745130Z [2023-10-04 14:23:10 +0000] [74] [INFO] Shutting down: Master
2023-10-04T14:23:10.236815230Z [2023-10-04 14:23:10 +0000] [74] [INFO] Reason: Worker failed to boot.

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
the run is performed on github codespace.
Linux codespaces-836ca0 6.2.0-1012-azure #12~22.04.1-Ubuntu SMP Thu Sep  7 14:07:14 UTC 2023 x86_64 GNU/Linux

### azd version?
> run `azd version` and copy paste here.
azd version 1.3.1 (commit b5030da0f29ffe98664c40450187fd8a4cb0d157)
### Versions
> node -v
v16.20.2
> npm -v
8.19.4

### Mention any other details that might be useful
I use free trial account, with OpenAI service approved, so all the initial steps are clean and successful, until I click the endpoint,
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Please see https://github.com/Azure-Samples/azure-search-openai-demo/issues/694

**Comment by don007git** [comment]
Thanks Pamelafox, it is good.
