### ISSUE TITLE
chat throws error on any message: TypeError: Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by PDiracDelta** [Azure-Samples/azure-search-openai-demo#814]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> send any message in the chat

### Any log messages given by the failure
> in the chat window: "TypeError: Cannot read properties of undefined (reading '0')"

### Expected/desired behavior
> no error; reply to chat

### OS and Version?
> Windows 10

### azd version?
> run `azd version` and copy paste here.
azd version 1.4.2 (commit 694107efa395b8562abcdf1f246792bbea72ad9c)

### Versions
> 69c41476f4f62485fa76569183474e4fd11c801f (Mon 16 oct)

### Mention any other details that might be useful
Docker default log: [2023_10_18_lw1sdlwk0000V6_default_docker.log](https://github.com/Azure-Samples/azure-search-openai-demo/files/12999511/2023_10_18_lw1sdlwk0000V6_default_docker.log)

![image](https://github.com/Azure-Samples/azure-search-openai-demo/assets/11943051/b764011f-c71d-4f0d-855c-320131d79ac3)

**Comment by Moin-Ud-Din** [comment]
@PDiracDelta I faced this issue when my Azure OpenAI service wasn't configured correctly so do check that.

**Comment by pamelafox** [comment]
Please check the App Service logs following the tip at the bottom of troubleshooting here: https://github.com/Azure-Samples/azure-search-openai-demo#troubleshooting
You can attach default_docker.log here if you need guidance interpreting the logs.

**Comment by PDiracDelta** [comment]
> Please check the App Service logs following the tip at the bottom of troubleshooting here: https://github.com/Azure-Samples/azure-search-openai-demo#troubleshooting You can attach default_docker.log here if you need guidance interpreting the logs.

Thanks Pamela! I found the logs but the error there seems unrelated. I attach them in this msg and in the bug report.

`
2023-10-18T08:40:14.598188543Z [2023-10-18 08:40:14 +0000] [77] [ERROR] Exception in ASGI application
2023-10-18T08:40:14.598693951Z Traceback (most recent call last):
2023-10-18T08:40:14.598702451Z   File "/tmp/8dbcf0ae01f781d/antenv/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
2023-10-18T08:40:14.598706451Z     result = await app(  # type: ignore[func-returns-value]
2023-10-18T08:40:14.598709851Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-10-18T08:40:14.598713151Z   File "/tmp/8dbcf0ae01f781d/antenv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
2023-10-18T08:40:14.598723451Z     return await self.app(scope, receive, send)
2023-10-18T08:40:14.598726952Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-10-18T08:40:14.598730352Z   File "/tmp/8dbcf0ae01f781d/antenv/lib/python3.11/site-packages/quart/app.py", line 1621, in __call__
2023-10-18T08:40:14.598733652Z     await self.asgi_app(scope, receive, send)
2023-10-18T08:40:14.598736852Z   File "/tmp/8dbcf0ae01f781d/antenv/lib/python3.11/site-packages/opentelemetry/instrumentation/asgi/__init__.py", line 596, in __call__
2023-10-18T08:40:14.598740252Z     await self.app(scope, otel_receive, otel_send)
2023-10-18T08:40:14.598743452Z   File "/tmp/8dbcf0ae01f781d/antenv/lib/python3.11/site-packages/quart/app.py", line 1647, in asgi_app
2023-10-18T08:40:14.598746752Z     await asgi_handler(receive, send)
2023-10-18T08:40:14.598749852Z   File "/tmp/8dbcf0ae01f781d/antenv/lib/python3.11/site-packages/quart/asgi.py", line 52, in __call__
2023-10-18T08:40:14.598753252Z     raise_task_exceptions(done)
2023-10-18T08:40:14.598756552Z   File "/tmp/8dbcf0ae01f781d/antenv/lib/python3.11/site-packages/quart/utils.py", line 187, in raise_task_exceptions
2023-10-18T08:40:14.598759952Z     raise task.exception()
2023-10-18T08:40:14.598763152Z   File "/tmp/8dbcf0ae01f781d/antenv/lib/python3.11/site-packages/quart/asgi.py", line 107, in handle_request
2023-10-18T08:40:14.598766552Z     await asyncio.wait_for(self._send_response(send, response), timeout=timeout)
2023-10-18T08:40:14.598769652Z   File "/opt/python/3.11.4/lib/python3.11/asyncio/tasks.py", line 442, in wait_for
2023-10-18T08:40:14.598772952Z     return await fut
2023-10-18T08:40:14.598775952Z            ^^^^^^^^^
2023-10-18T08:40:14.598779152Z   File "/tmp/8dbcf0ae01f781d/antenv/lib/python3.11/site-packages/quart/asgi.py", line 134, in _send_response
2023-10-18T08:40:14.598782552Z     async for data in response_body:
2023-10-18T08:40:14.598785852Z   File "/tmp/8dbcf0ae01f781d/app.py", line 109, in format_as_ndjson
2023-10-18T08:40:14.598789153Z     async for event in r:
2023-10-18T08:40:14.598792353Z   File "/tmp/8dbcf0ae01f781d/approaches/chatreadretrieveread.py", line 252, in run_with_streaming
2023-10-18T08:40:14.598797153Z     extra_info, chat_coroutine = await self.run_until_final_call(
2023-10-18T08:40:14.598800453Z                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-10-18T08:40:14.598803553Z   File "/tmp/8dbcf0ae01f781d/approaches/chatreadretrieveread.py", line 182, in run_until_final_call
2023-10-18T08:40:14.598806853Z     results = [doc[self.sourcepage_field] + ": " + nonewlines(doc[self.content_field]) async for doc in r]
2023-10-18T08:40:14.598810353Z               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-10-18T08:40:14.598813753Z   File "/tmp/8dbcf0ae01f781d/approaches/chatreadretrieveread.py", line 182, in <listcomp>
2023-10-18T08:40:14.598820553Z     results = [doc[self.sourcepage_field] + ": " + nonewlines(doc[self.content_field]) async for doc in r]
2023-10-18T08:40:14.598824053Z               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-10-18T08:40:14.598827353Z   File "/tmp/8dbcf0ae01f781d/antenv/lib/python3.11/site-packages/azure/search/documents/aio/_paging.py", line 26, in __anext__
2023-10-18T08:40:14.598830653Z     return await self.__anext__()
2023-10-18T08:40:14.598833653Z            ^^^^^^^^^^^^^^^^^^^^^^
2023-10-18T08:40:14.598836853Z   File "/tmp/8dbcf0ae01f781d/antenv/lib/python3.11/site-packages/azure/search/documents/aio/_paging.py", line 29, in __anext__
2023-10-18T08:40:14.598840253Z     self._page = await self._page_iterator.__anext__()
2023-10-18T08:40:14.598843553Z                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-10-18T08:40:14.598846753Z   File "/tmp/8dbcf0ae01f781d/antenv/lib/python3.11/site-packages/azure/core/async_paging.py", line 94, in __anext__
2023-10-18T08:40:14.598850153Z     self._response = await self._get_next(self.continuation_token)
2023-10-18T08:40:14.598853354Z                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-10-18T08:40:14.598856454Z   File "/tmp/8dbcf0ae01f781d/antenv/lib/python3.11/site-packages/azure/search/documents/aio/_paging.py", line 106, in _get_next_cb
2023-10-18T08:40:14.598859754Z     return await self._client.documents.search_post(search_request=self._initial_query.request, **self._kwargs)
2023-10-18T08:40:14.598862954Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-10-18T08:40:14.598866454Z   File "/tmp/8dbcf0ae01f781d/antenv/lib/python3.11/site-packages/azure/core/tracing/decorator_async.py", line 88, in wrapper_use_tracer
2023-10-18T08:40:14.598869854Z     return await func(*args, **kwargs)
2023-10-18T08:40:14.598873054Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-10-18T08:40:14.598876554Z   File "/tmp/8dbcf0ae01f781d/antenv/lib/python3.11/site-packages/azure/search/documents/_generated/aio/operations/_documents_operations.py", line 427, in search_post
2023-10-18T08:40:14.598879954Z     raise HttpResponseError(response=response, model=error)
2023-10-18T08:40:14.598883054Z azure.core.exceptions.HttpResponseError: (InvalidRequestParameter) Unknown field 'embedding' in vector field list.
2023-10-18T08:40:14.598886254Z Code: InvalidRequestParameter
2023-10-18T08:40:14.598889454Z Message: Unknown field 'embedding' in vector field list.
2023-10-18T08:40:14.598892754Z Exception Details:	(UnknownField) Unknown field 'embedding' in vector field list.
2023-10-18T08:40:14.598896154Z 	Code: UnknownField
2023-10-18T08:40:14.598899554Z 	Message: Unknown field 'embedding' in vector field list.
`
