### ISSUE TITLE
Error on check_md5 with folder

### ISSUE THREAD

**Issue by zaffaste** [Azure-Samples/azure-search-openai-demo#905]
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> just add some folder in data and add documents to these folders (e.g.: \data\SomeFolder\someDocument.pdf)

### Any log messages given by the failure
> Traceback (most recent call last):
  File "\scripts\prepdocs.py", line 256, in <module>
    loop.run_until_complete(main(file_strategy, azd_credential, args))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "\scripts\prepdocs.py", line 131, in main
    await strategy.run(search_info)
  File "\scripts\prepdocslib\filestrategy.py", line 54, in run
    async for file in files:
  File "\scripts\prepdocslib\listfilestrategy.py", line 82, in list
    if not self.check_md5(path):
  File "\scripts\prepdocslib\listfilestrategy.py", line 92, in check_md5
    with open(path, "rb") as file:
PermissionError: [Errno 13] Permission denied: 'rootPath/data\\SomeFolder'

### Mention any other details that might be useful
> A possibile fix is to add a check for directory like this on line 85 in listfilestrategy.py file:
    def check_md5(self, path: str) -> bool:
        # if path is a folder skip it
        if os.path.isdir(path):
            return True

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Thanks for report, will send PR with fix soon.
