### ISSUE TITLE
Internal server error (permissions issue) when getting document preview

### ISSUE THREAD

**Issue by ktschroeder-bp** [Azure-Samples/azure-search-openai-demo#980]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Run "azd up"
> Access remote website
> Make a request to the chatbot
> Click one of the source links (citations)
> This results in an internal server error inside the citation tab

### Any log messages given by the failure
> 2023-11-21T14:02:38.232875426Z ERROR:app:Exception on request GET /content/datamanagement/Data Management Training And Operations Guide-41.pdf
2023-11-21T14:02:38.232895926Z Traceback (most recent call last):
2023-11-21T14:02:38.232901326Z   File "/tmp/8dbea197830f7ca/antenv/lib/python3.11/site-packages/quart/app.py", line 1359, in handle_request
2023-11-21T14:02:38.232944427Z     return await self.full_dispatch_request(request_context)
2023-11-21T14:02:38.232948627Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-21T14:02:38.232952627Z   File "/tmp/8dbea197830f7ca/antenv/lib/python3.11/site-packages/quart/app.py", line 1397, in full_dispatch_request
2023-11-21T14:02:38.232968727Z     result = await self.handle_user_exception(error)
2023-11-21T14:02:38.232972427Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-21T14:02:38.232976027Z   File "/tmp/8dbea197830f7ca/antenv/lib/python3.11/site-packages/quart/app.py", line 1000, in handle_user_exception
2023-11-21T14:02:38.232979728Z     raise error
2023-11-21T14:02:38.232983228Z   File "/tmp/8dbea197830f7ca/antenv/lib/python3.11/site-packages/quart/app.py", line 1395, in full_dispatch_request
2023-11-21T14:02:38.232987528Z     result = await self.dispatch_request(request_context)
2023-11-21T14:02:38.232991628Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-21T14:02:38.232995128Z   File "/tmp/8dbea197830f7ca/antenv/lib/python3.11/site-packages/quart/app.py", line 1489, in dispatch_request
2023-11-21T14:02:38.233007628Z     return await self.ensure_async(handler)(**request_.view_args)
2023-11-21T14:02:38.233011228Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-21T14:02:38.233014728Z   File "/tmp/8dbea197830f7ca/app.py", line 78, in content_file
2023-11-21T14:02:38.233018328Z     blob = await blob_container_client.get_blob_client(path).download_blob()
2023-11-21T14:02:38.233021928Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-21T14:02:38.233025528Z   File "/tmp/8dbea197830f7ca/antenv/lib/python3.11/site-packages/azure/core/tracing/decorator_async.py", line 88, in wrapper_use_tracer
2023-11-21T14:02:38.233029528Z     return await func(*args, **kwargs)
2023-11-21T14:02:38.233032928Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-21T14:02:38.233036528Z   File "/tmp/8dbea197830f7ca/antenv/lib/python3.11/site-packages/azure/storage/blob/aio/_blob_client_async.py", line 541, in download_blob
2023-11-21T14:02:38.233040228Z     await downloader._setup()  # pylint: disable=protected-access
2023-11-21T14:02:38.233043729Z     ^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-21T14:02:38.233047229Z   File "/tmp/8dbea197830f7ca/antenv/lib/python3.11/site-packages/azure/storage/blob/aio/_download_async.py", line 288, in _setup
2023-11-21T14:02:38.233052529Z     self._response = await self._initial_request()
2023-11-21T14:02:38.233056129Z                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-21T14:02:38.233059729Z   File "/tmp/8dbea197830f7ca/antenv/lib/python3.11/site-packages/azure/storage/blob/aio/_download_async.py", line 383, in _initial_request
2023-11-21T14:02:38.233063329Z     process_storage_error(error)
2023-11-21T14:02:38.233067229Z   File "/tmp/8dbea197830f7ca/antenv/lib/python3.11/site-packages/azure/storage/blob/_shared/response_handlers.py", line 184, in process_storage_error
2023-11-21T14:02:38.233071029Z     exec("raise error from None")   # pylint: disable=exec-used # nosec
2023-11-21T14:02:38.233074629Z     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-21T14:02:38.233078129Z   File "<string>", line 1, in <module>
2023-11-21T14:02:38.233087329Z azure.core.exceptions.HttpResponseError: **This request is not authorized to perform this operation using this permission.**
2023-11-21T14:02:38.233091129Z RequestId:461e04ac-201e-0109-6283-1c4671000000
2023-11-21T14:02:38.233094729Z Time:2023-11-21T14:02:37.7668686Z
2023-11-21T14:02:38.233098229Z **ErrorCode:AuthorizationPermissionMismatch**
2023-11-21T14:02:38.233101829Z Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationPermissionMismatch</Code><Message>**This request is not authorized to perform this operation using this permission.**
2023-11-21T14:02:38.233106329Z RequestId:461e04ac-201e-0109-6283-1c4671000000
2023-11-21T14:02:38.233109930Z Time:2023-11-21T14:02:37.7668686Z</Message></Error>

### Expected/desired behavior
> A preview of the document is displayed in the website.

### OS and Version?
> Windows 10

### azd version?
> azd version 1.4.3 (commit d165bd2de96dae75de57604c0d8a5553ae214618)

### Versions
>

### Mention any other details that might be useful

1. It's notable that the app can apparently get text from the indices, but cannot get the files themselves. The chatbot gives a perfectly fine response.
2. When running locally, I am able to get the document previews without issue. There is only an error when doing this on a remote version of the website. It seems like this is surely due to the app service missing some permission for accessing the blobs; However, the app has every possibly relevant permission on the storage account: Storage Blob Data Contributor, Storage Blob Data Reader, and Storage Blob Delegator.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Hm, I notice the file is inside a folder in the path: "datamanagement/..."
I don't know if I've tried that in production myself, are there any files not inside a folder that you can try? I wonder if that's affecting the permissions.

**Comment by ktschroeder-bp** [comment]
> Hm, I notice the file is inside a folder in the path: "datamanagement/..." I don't know if I've tried that in production myself, are there any files not inside a folder that you can try? I wonder if that's affecting the permissions.

Thanks for your attention; That's the GET request path, but I am taking the second string (e.g. datamanagement) as the container from which to get the files. I have several chatbots with access to different containers in the storage account. The actual file path is the final string, and the files are not in folders. Aside from that, there are no changes to this function in app.py.

It might be obvious, but from adding logs I see that the exception is occurring on this line in that function:
`blob = await blob_container_client.get_blob_client(path).download_blob()`

For context, this is the function:
```
@bp.route("/content/<copilotType>/<path>")
async def content_file(copilotType, path):
    blob_container_client = copilot_blob_dict[copilotType]
    blob = await blob_container_client.get_blob_client(path).download_blob()
    if not blob.properties or not blob.properties.has_key("content_settings"):
        abort(404)
    mime_type = blob.properties["content_settings"]["content_type"]
    if mime_type == "application/octet-stream":
        mime_type = mimetypes.guess_type(path)[0] or "application/octet-stream"
    blob_file = io.BytesIO()
    await blob.readinto(blob_file)
    blob_file.seek(0)
    return await send_file(blob_file, mimetype=mime_type, as_attachment=False, attachment_filename=path)
```

**Comment by pamelafox** [comment]
Hm. You say the role is already there, but I'll share screenshots of what I see, so that you can compare:

<img width="1365" alt="Screenshot 2023-11-23 at 6 49 21 AM" src="https://github.com/Azure-Samples/azure-search-openai-demo/assets/297042/4e4e5cc5-cf92-401a-9f20-2c3a91d575c5">

More details:
<img width="1081" alt="Screenshot 2023-11-23 at 6 54 35 AM" src="https://github.com/Azure-Samples/azure-search-openai-demo/assets/297042/d0be17dd-bde5-47f6-8068-16496678cc5b">
<img width="1019" alt="Screenshot 2023-11-23 at 6 54 41 AM" src="https://github.com/Azure-Samples/azure-search-openai-demo/assets/297042/451f8d83-8b05-440a-9685-0d0263e781ee">
<img width="1309" alt="Screenshot 2023-11-23 at 6 55 17 AM" src="https://github.com/Azure-Samples/azure-search-openai-demo/assets/297042/0ef2e6f7-d7fa-4eb1-ae2e-60e711aae727">

**Comment by pamelafox** [comment]
Assuming the role is correct, one thing you can try is turning the APP_LOG_LEVEL to DEBUG. Then you can typically see the request made to blob storage and see if anything seems off.

**Comment by ktschroeder-bp** [comment]
Thank you again--I've verified that I have permissions set up as given in your screenshots, which they are. I also have the log level as DEBUG. Here is a full set of logs from one of these failures, in case anything jumps out. The first 3 lines are my own logs, and I've just redacted the base address/IP ("redacted" in lowercase, in the logs).

```
2023-11-27T22:29:01.723256240Z INFO:root:Getting doc preview: copilotType datamanagement, path Data Management Training And Operations Guide-37.pdf
2023-11-27T22:29:01.724588554Z INFO:root:Getting doc preview: flag 0
2023-11-27T22:29:01.725051159Z DEBUG:root:Getting doc preview: flag 0 debug
2023-11-27T22:29:01.930471569Z INFO:azure.core.pipeline.policies.http_logging_policy:Request URL: 'https://[redacted].blob.core.windows.net/datamanagement-content/Data%20Management%20Training%20And%20Operations%20Guide-37.pdf'
2023-11-27T22:29:01.930519069Z Request method: 'GET'
2023-11-27T22:29:01.930525869Z Request headers:
2023-11-27T22:29:01.930529869Z     'x-ms-range': 'REDACTED'
2023-11-27T22:29:01.930533669Z     'x-ms-version': 'REDACTED'
2023-11-27T22:29:01.930537369Z     'Accept': 'application/xml'
2023-11-27T22:29:01.930540969Z     'x-ms-date': 'REDACTED'
2023-11-27T22:29:01.930544769Z     'x-ms-client-request-id': '5d7bc4b6-8d74-11ee-9e1b-b2b92e1c6807'
2023-11-27T22:29:01.930548569Z     'User-Agent': 'azsdk-python-storage-blob/12.18.2 Python/3.11.4 (Linux-5.15.131.1-2.cm2-x86_64-with-glibc2.31)'
2023-11-27T22:29:01.930552370Z     'Authorization': 'REDACTED'
2023-11-27T22:29:01.930556070Z No body was attached to the request
2023-11-27T22:29:02.014225229Z INFO:azure.core.pipeline.policies.http_logging_policy:Response status: 403
2023-11-27T22:29:02.014332030Z Response headers:
2023-11-27T22:29:02.014346130Z     'Content-Length': '279'
2023-11-27T22:29:02.014350230Z     'Content-Type': 'application/xml'
2023-11-27T22:29:02.014353930Z     'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
2023-11-27T22:29:02.014357430Z     'x-ms-request-id': '2195de17-d01e-005e-6d81-21ab90000000'
2023-11-27T22:29:02.014361130Z     'x-ms-client-request-id': '5d7bc4b6-8d74-11ee-9e1b-b2b92e1c6807'
2023-11-27T22:29:02.014365230Z     'x-ms-version': 'REDACTED'
2023-11-27T22:29:02.014368830Z     'x-ms-error-code': 'AuthorizationPermissionMismatch'
2023-11-27T22:29:02.014372431Z     'Date': 'Mon, 27 Nov 2023 22:29:01 GMT'
2023-11-27T22:29:02.062536525Z DEBUG:azure.storage.blob._generated._serialization:Ran into a deserialization error. Ignoring since this is failsafe deserialization
2023-11-27T22:29:02.062608026Z Traceback (most recent call last):
2023-11-27T22:29:02.062614426Z   File "/tmp/8dbebac4995e92f/antenv/lib/python3.11/site-packages/azure/storage/blob/_generated/_serialization.py", line 1542, in failsafe_deserialize
2023-11-27T22:29:02.062619126Z     return self(target_obj, data, content_type=content_type)
2023-11-27T22:29:02.062623426Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-27T22:29:02.062627526Z   File "/tmp/8dbebac4995e92f/antenv/lib/python3.11/site-packages/azure/storage/blob/_generated/_serialization.py", line 1413, in __call__
2023-11-27T22:29:02.062631926Z     data = self._unpack_content(response_data, content_type)
2023-11-27T22:29:02.062635826Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-27T22:29:02.062646326Z   File "/tmp/8dbebac4995e92f/antenv/lib/python3.11/site-packages/azure/storage/blob/_generated/_serialization.py", line 1571, in _unpack_content
2023-11-27T22:29:02.062651726Z     raise ValueError("This pipeline didn't have the RawDeserializer policy; can't deserialize")
2023-11-27T22:29:02.062655827Z ValueError: This pipeline didn't have the RawDeserializer policy; can't deserialize
2023-11-27T22:29:02.168204011Z DEBUG:charset_normalizer:Encoding detection: utf_8 is most likely the one.
2023-11-27T22:29:02.177250204Z DEBUG:charset_normalizer:Encoding detection: utf_8 is most likely the one.
2023-11-27T22:29:02.193031666Z DEBUG:charset_normalizer:Encoding detection: utf_8 is most likely the one.
2023-11-27T22:29:02.196507202Z DEBUG:charset_normalizer:Encoding detection: utf_8 is most likely the one.
2023-11-27T22:29:02.220623349Z DEBUG:charset_normalizer:Encoding detection: utf_8 is most likely the one.
2023-11-27T22:29:02.235714904Z ERROR:app:Exception on request GET /content/datamanagement/Data Management Training And Operations Guide-37.pdf2023-11-27T22:29:02.235734905Z Traceback (most recent call last):
2023-11-27T22:29:02.235740605Z   File "/tmp/8dbebac4995e92f/antenv/lib/python3.11/site-packages/quart/app.py", line 1359, in handle_request
2023-11-27T22:29:02.235814505Z     return await self.full_dispatch_request(request_context)
2023-11-27T22:29:02.235822805Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-27T22:29:02.235826805Z   File "/tmp/8dbebac4995e92f/antenv/lib/python3.11/site-packages/quart/app.py", line 1397, in full_dispatch_request
2023-11-27T22:29:02.235831206Z     result = await self.handle_user_exception(error)
2023-11-27T22:29:02.235835106Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-27T22:29:02.235838906Z   File "/tmp/8dbebac4995e92f/antenv/lib/python3.11/site-packages/quart/app.py", line 1000, in handle_user_exception
2023-11-27T22:29:02.235843006Z     raise error
2023-11-27T22:29:02.235846706Z   File "/tmp/8dbebac4995e92f/antenv/lib/python3.11/site-packages/quart/app.py", line 1395, in full_dispatch_request
2023-11-27T22:29:02.235850806Z     result = await self.dispatch_request(request_context)
2023-11-27T22:29:02.235861506Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-27T22:29:02.235866306Z   File "/tmp/8dbebac4995e92f/antenv/lib/python3.11/site-packages/quart/app.py", line 1489, in dispatch_request
2023-11-27T22:29:02.235870406Z     return await self.ensure_async(handler)(**request_.view_args)
2023-11-27T22:29:02.235874306Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-27T22:29:02.235878206Z   File "/tmp/8dbebac4995e92f/app.py", line 81, in content_file
2023-11-27T22:29:02.235882206Z     blob = await blob_container_client.get_blob_client(path).download_blob()
2023-11-27T22:29:02.235886006Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-27T22:29:02.235890006Z   File "/tmp/8dbebac4995e92f/antenv/lib/python3.11/site-packages/azure/core/tracing/decorator_async.py", line 88, in wrapper_use_tracer
2023-11-27T22:29:02.235894206Z     return await func(*args, **kwargs)
2023-11-27T22:29:02.235898106Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-27T22:29:02.235901906Z   File "/tmp/8dbebac4995e92f/antenv/lib/python3.11/site-packages/azure/storage/blob/aio/_blob_client_async.py", line 541, in download_blob
2023-11-27T22:29:02.235906106Z     await downloader._setup()  # pylint: disable=protected-access
2023-11-27T22:29:02.235909906Z     ^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-27T22:29:02.235913806Z   File "/tmp/8dbebac4995e92f/antenv/lib/python3.11/site-packages/azure/storage/blob/aio/_download_async.py", line 288, in _setup
2023-11-27T22:29:02.235919106Z     self._response = await self._initial_request()
2023-11-27T22:29:02.235923106Z                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-27T22:29:02.235926907Z   File "/tmp/8dbebac4995e92f/antenv/lib/python3.11/site-packages/azure/storage/blob/aio/_download_async.py", line 383, in _initial_request
2023-11-27T22:29:02.235931107Z     process_storage_error(error)
2023-11-27T22:29:02.235934907Z   File "/tmp/8dbebac4995e92f/antenv/lib/python3.11/site-packages/azure/storage/blob/_shared/response_handlers.py", line 184, in process_storage_error
2023-11-27T22:29:02.235943907Z     exec("raise error from None")   # pylint: disable=exec-used # nosec
2023-11-27T22:29:02.235948207Z     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-27T22:29:02.235952007Z   File "<string>", line 1, in <module>
2023-11-27T22:29:02.235972207Z azure.core.exceptions.HttpResponseError: This request is not authorized to perform this operation using this permission.
2023-11-27T22:29:02.235976407Z RequestId:2195de17-d01e-005e-6d81-21ab90000000
2023-11-27T22:29:02.235980107Z Time:2023-11-27T22:29:02.0137280Z
2023-11-27T22:29:02.235983707Z ErrorCode:AuthorizationPermissionMismatch
2023-11-27T22:29:02.235987307Z Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationPermissionMismatch</Code><Message>This request is not authorized to perform this operation using this permission.
2023-11-27T22:29:02.235992107Z RequestId:2195de17-d01e-005e-6d81-21ab90000000
2023-11-27T22:29:02.235995707Z Time:2023-11-27T22:29:02.0137280Z</Message></Error>
2023-11-27 22:29:01.663 +00:00 [Debug] Microsoft.AspNetCore.Server.Kestrel.Connections: Connection id "0HMVBLK4N0R4M" accepted.
2023-11-27 22:29:01.663 +00:00 [Debug] Microsoft.AspNetCore.Server.Kestrel.Connections: Connection id "0HMVBLK4N0R4M" started.
2023-11-27 22:29:01.672 +00:00 [Information] Microsoft.AspNetCore.Hosting.Diagnostics: Request starting HTTP/1.1 GET http://[redacted address]/content/datamanagement/Data Management Training And Operations Guide-37.pdf - -
2023-11-27 22:29:01.697 +00:00 [Trace] Middleware: Request came in on normal port, sending to normal target http://[redacted IP]:8000/content/datamanagement/Data%20Management%20Training%20And%20Operations%20Guide-37.pdf
2023-11-27 22:29:01.698 +00:00 [Trace] Middleware: Forwarding request to http://[redacted IP]:8000/content/datamanagement/Data Management Training And Operations Guide-37.pdf
2023-11-27 22:29:02.264 +00:00 [Trace] Middleware: Forwarded request finished in 565.768ms 200 Internal Server Error
2023-11-27 22:29:02.264 +00:00 [Debug] Microsoft.AspNetCore.Server.Kestrel.Connections: Connection id "0HMVBLK4N0R4M" completed keep alive response.
2023-11-27 22:29:02.264 +00:00 [Information] Microsoft.AspNetCore.Hosting.Diagnostics: Request finished HTTP/1.1 GET http://[redacted address]/content/datamanagement/Data Management Training And Operations Guide-37.pdf - - - 500 265 text/html;+charset=utf-8 592.4094ms
2023-11-27 22:29:03.219 +00:00 [Information] Microsoft.AspNetCore.Hosting.Diagnostics: Request starting HTTP/1.1 GET http://[redacted address].azurewebsites.net/ - -
2023-11-27 22:29:03.225 +00:00 [Debug] Microsoft.AspNetCore.Server.Kestrel.Connections: Connection id "0HMVBLK4N0R4M" completed keep alive response.
2023-11-27 22:29:03.225 +00:00 [Information] Microsoft.AspNetCore.Hosting.Diagnostics: Request finished HTTP/1.1 GET http://[redacted address].azurewebsites.net/ - - - 401 - - 5.8062ms
```

**Comment by pamelafox** [comment]
Thanks for sharing. I do see there's an earlier error in the log about deserialization, but I believe that error is caught by the SDK itself, per discussion at https://github.com/Azure/azure-sdk-for-python/issues/25954

At this point, I'd suggest you go into SSH from the App Service portal. Open a Python REPL in there and attempt to download a blob using similar code as app.py. If that fails, try setting up the Azure credential a different way (like with a key) and see if it also fails. If it does work with keys but not with ManagedIdentity credential, then we know there's something amiss with the identity.

**Comment by ktschroeder-bp** [comment]
I deployed the app using a connection string for the BlobServiceClient, instead of the default Azure credentials, and it worked correctly in production/remotely. So, you must be right, that it's an issue of the managed identity. I'm not sure how that could be, if the identity has the proper permissions; but I don't mind simply using the connection string for this purpose. 

Thank you kindly for your help!
