### ISSUE TITLE
Search Service did not create search key with Owner previladge

### ISSUE THREAD

**Issue by Awadelrahman** [Azure-Samples/azure-search-openai-demo#984]
Search Service did not create search key.
My account has Owner previladge.
Noticed when running `azd up` the following log appears when it comes to the prepdocs part of the code:

Running "prepdocs.py"
Traceback (most recent call last):
  File "./scripts/prepdocs.py", line 9, in <module>
    from prepdocslib.blobmanager import BlobManager
  File "...........\scripts\prepdocslib\blobmanager.py", line 8, in <module>
    from .listfilestrategy import File
  File "..................\scripts\prepdocslib\listfilestrategy.py", line 16, in <module>
    class File:
  File ".......................\scripts\prepdocslib\listfilestrategy.py", line 22, in File
    def __init__(self, content: IO, acls: Optional[dict[str, list]] = None):
TypeError: 'type' object is not subscriptable

**Comment by pamelafox** [comment]
What version of Python are you using? That looks like a typing issue, not a key issue.

**Comment by Awadelrahman** [comment]
Thanks for the reply, pyhon 3.8.10

**Comment by Awadelrahman** [comment]
I got another error after upgrading python, and I still can not see any index on the Search service here is the error:

Ensuring search index gptkbindex exists
Traceback (most recent call last):
  File ".................\scripts\.venv\Lib\site-packages\aiohttp\connector.py", line 1155, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".................\scripts\.venv\Lib\site-packages\aiohttp\connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".................\scripts\.venv\Lib\site-packages\aiohttp\resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "..........................\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 867, in getaddrinfo
    return await self.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AwadelrahmanMohamede\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".....................\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "..................\scripts\.venv\Lib\site-packages\azure\core\pipeline\transport\_aiohttp.py", line 280, in send
    result = await self.session.request(  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".......................\scripts\.venv\Lib\site-packages\aiohttp\client.py", line 562, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "........................\scripts\.venv\Lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".........................\scripts\.venv\Lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".......................\scripts\.venv\Lib\site-packages\aiohttp\connector.py", line 1169, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host gptkb-lxgdctfchibfm.search.windows.net:443 ssl:default [getaddrinfo failed]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "......................\scripts\prepdocs.py", line 256, in <module>
    loop.run_until_complete(main(file_strategy, azd_credential, args))
  File ".....................\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "...................\scripts\prepdocs.py", line 129, in main
    await strategy.setup(search_info)
  File "....................\scripts\prepdocslib\filestrategy.py", line 48, in setup
    await search_manager.create_index()
  File "........................\scripts\prepdocslib\searchmanager.py", line 112, in create_index
    if self.search_info.index_name not in [name async for name in search_index_client.list_index_names()]:
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "................................\scripts\prepdocslib\searchmanager.py", line 112, in <listcomp>
    if self.search_info.index_name not in [name async for name in search_index_client.list_index_names()]:
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".......................\scripts\.venv\Lib\site-packages\azure\core\async_paging.py", line 142, in __anext__
    return await self.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "..................\scripts\.venv\Lib\site-packages\azure\core\async_paging.py", line 145, in __anext__
    self._page = await self._page_iterator.__anext__()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "......................\scripts\.venv\Lib\site-packages\azure\core\async_paging.py", line 94, in __anext__
    self._response = await self._get_next(self.continuation_token)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".............................\scripts\.venv\Lib\site-packages\azure\search\documents\indexes\_generated\aio\operations\_indexes_operations.py", line 295, in get_next
    pipeline_response: PipelineResponse = await self._client._pipeline.run(  # pylint: disable=protected-access
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "....................\scripts\.venv\Lib\site-packages\azure\core\pipeline\_base_async.py", line 221, in run
    return await first_node.send(pipeline_request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "....................\scripts\.venv\Lib\site-packages\azure\core\pipeline\_base_async.py", line 69, in send
    response = await self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "............................\scripts\.venv\Lib\site-packages\azure\core\pipeline\_base_async.py", line 69, in send
    response = await self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "......................\scripts\.venv\Lib\site-packages\azure\core\pipeline\_base_async.py", line 69, in send
    response = await self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 2 more times]
  File ".......................\scripts\.venv\Lib\site-packages\azure\core\pipeline\policies\_redirect_async.py", line 73, in send
    response = await self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "....................\scripts\.venv\Lib\site-packages\azure\core\pipeline\policies\_retry_async.py", line 205, in send
    raise err
  File ".................\scripts\.venv\Lib\site-packages\azure\core\pipeline\policies\_retry_async.py", line 179, in send
    response = await self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "................\scripts\.venv\Lib\site-packages\azure\core\pipeline\policies\_authentication_async.py", line 94, in send
    response = await self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".................\scripts\.venv\Lib\site-packages\azure\core\pipeline\_base_async.py", line 69, in send
    response = await self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "........................\scripts\.venv\Lib\site-packages\azure\core\pipeline\_base_async.py", line 69, in send
    response = await self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".....................\scripts\.venv\Lib\site-packages\azure\core\pipeline\_base_async.py", line 69, in send
    response = await self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 2 more times]
  File ".................\scripts\.venv\Lib\site-packages\azure\core\pipeline\_base_async.py", line 106, in send
    await self._sender.send(request.http_request, **request.context.options),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "..................\scripts\.venv\Lib\site-packages\azure\core\pipeline\transport\_aiohttp.py", line 317, in send
    raise ServiceRequestError(err, error=err) from err
azure.core.exceptions.ServiceRequestError: Cannot connect to host gptkb-lxgdctfchibfm.search.windows.net:443 ssl:default [getaddrinfo failed]

**Comment by Awadelrahman** [comment]
version 3.11 worked perfect, thanks
